### ISSUE TITLE
Provide version-less links to classes

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/cocoadocs.org#136]
If one wants to link from somewhere else to a specific classes documentation on CocoaDocs.org, the URL will be version-specific at the moment. IMHO, there should be redirects for the classes, just as there is one for the Pod's index page.

This could be achieved by deleting all old redirects in the Pods Classes folder for each update, then adding redirects for each class to the latest version's corresponding page.

**Comment by orta** [comment]
Calling this a no-go, just isn't really feasible from my perspective with appledoc.
