### ISSUE TITLE
How do I customize the appledoc command that generates the docs?

### ISSUE THREAD

**Issue by swisspol** [CocoaPods/cocoadocs.org#150]
I thought I saw how to do this somewhere but I absolutely cannot find it anymore.

You might wanna add this to the README.

**Comment by 0xced** [comment]
I have a new use case for that: appledoc's `--explicit-crossref` option. appledoc is a bit too aggressive in finding cross references that should not exist and my documentation is much better if I turn this option on.

Is there any chance to add that feature, maybe with a new key in the `.cocoadocs.yml` file?

**Comment by 0xced** [comment]
Implemented in ac7881872c9718e61b7a68341c875baffcf6686e, thanks @orta!

**Comment by 0xced** [comment]
For reference: [Controlling cross references detection](https://github.com/tomaz/appledoc/wiki/appledoc-docs-examples-advanced#controlling-cross-references-detection) is documented on appledoc’s wiki.
