### ISSUE TITLE
New Dash icon

### ISSUE THREAD

**Issue by Kapeli** [CocoaPods/cocoadocs.org#243]
Sorry @orta, I sent you an email about this and then I realised I should just make a GitHub issue.

So, the Dash icon has changed to:

![image](http://kapeli.com/dash_resources/256.png)

Preferably, the icon on CocoaDocs should be updated as well.

**Comment by orta** [comment]
This is in.

I'm planning on a re-doccing of everything for CocoaPods metadata so it will update to all the older ones too.

**Comment by Kapeli** [comment]
:+1:
