### ISSUE TITLE
Visusally indicate if a pod has been deprecated

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoadocs.org#247]
I think we should show some big red banner warning the user it's deprecated. Then also show what it's been deprecated for and possibly provide a link.

https://github.com/CocoaPods/cocoadocs.org/issues/242#issuecomment-57720463

**Comment by orta** [comment]
![screen shot 2015-01-20 at 22 46 53](https://cloud.githubusercontent.com/assets/49038/5830955/3e664264-a0f6-11e4-8892-2e5a52bbf4e9.png)

We take into account deprecated & deprecated_by now.

**Comment by orta** [comment]
it says library, not spec.
