### ISSUE TITLE
Issues with scrolling in new design

### ISSUE THREAD

**Issue by problame** [CocoaPods/cocoadocs.org#252]
The sidebar containing links to the different properties, methods and functions sticks to the left when scrolling the content. I think it is confusing since you can't quickly navigate through a Pod's classes.

Video: http://dl.cschwarz.com/bdd1dcebc28f39f488160b40668354f2.m4v
Pod in Video: http://cocoadocs.org/docsets/ReactiveCocoa/

**Comment by AliSoftware** [comment]
@orta hehe I reported the same problem to you in Slack some weeks ago about my own lib ;)

**Comment by neonichu** [comment]
I think it makes sense to scroll, ~15 methods fit if one has a full-screenish browser window on a 13" display and collapses the "Tasks" section. It isn't outlandish to have a low double digits list of methods.

**Comment by orta** [comment]
Perhaps I could add some JS to check if it's height is greater than the browser height and to allow scrolling then.

**Comment by AliSoftware** [comment]
I imagine two other solutions in order not to overcomplicate the logic by JS checks and all (well at least I imagine it would be simpler to implement, but maybe I'm wrong):

* Either scroll the TOC with the rest of the content. One can always scroll to top to get back to the top, it's not that bad. (We can even add a sticky div at the bottom with a like to "go back to top" in that case)
* Or have two different divs (one for TOC one for content) that have independent scrolling areas, so we can scroll the TOC without scrolling the content, and scroll the content while keeping the TOC visible.
