### ISSUE TITLE
Add documentation coverage badge

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/cocoadocs.org#263]
It would be cool if there were a badge a project could include in its readme file that shows how well-documented it is. I saw an example of [this project](https://github.com/mrackwitz/CLIntegracon), which was provided by [Inch CI](http://inch-ci.org), for Ruby projects. It's a nice subtle way of encouraging good documentation, and showing off once it's achieved.

Here's an example:
![Inch CI badge](https://cloud.githubusercontent.com/assets/1349578/4691941/f86b8d4c-573e-11e4-9501-a3cc9a172d33.png)

**Comment by mariusc** [comment]
Looks like you can get that from `https://img.shields.io/cocoapods/metrics/doc-percent/<your_pod_name>.svg`. 

Here's an example for Alamofire 
`[![Documentation](https://img.shields.io/cocoapods/metrics/doc-percent/Alamofire.svg)](http://cocoadocs.org/docsets/Alamofire/)`
rendered as 
[![Documentation](https://img.shields.io/cocoapods/metrics/doc-percent/Alamofire.svg)](http://cocoadocs.org/docsets/Alamofire/)

**Comment by orta** [comment]
Yeah, good point @mariusc - more docs here: http://shields.io

**Comment by abbeycode** [comment]
Awesome guys, thanks. I've added it to my projects' readme files.

**Comment by T-Pham** [comment]
Is there a way to specify the pod version in the badge url?
Since this issue #466 is not fixed yet, I would like to link to the documentation for a previous version of my pod.

**Comment by orta** [comment]
You can check out shields.io for that, we don't host them

**Comment by orta** [comment]
But I doubt it, I don't think we keep our database like that, I think docs etc is only per pod - rather than per pod-version

**Comment by T-Pham** [comment]
Apparently shields.io doesn't mention tag for the documentation coverage badge but yes, I should seek support from shields.io instead.

We can access the documentation for a specific version x.y.z like this http://cocoadocs.org/docsets/PodName/x.y.z/.

**Comment by orta** [comment]
You can get the docs, but it's not stored in our trunk database per version, which is what they'll be going off I think

**Comment by T-Pham** [comment]
Oh, I see.
