### ISSUE TITLE
No longer honors 'documentation_url'

### ISSUE THREAD

**Issue by jasperblues** [CocoaPods/cocoadocs.org#272]
Personally not bothered about this, but as an observation noticed that: 
- In the past CocoaDocs would honor a spec's 'documentation_url', sending the user there if set. 
- This is no longer the case.

**Comment by friedbunny** [comment]
The readme [continues to state](https://github.com/CocoaPods/cocoadocs.org/blame/8457eb82985c9ffa3433ced382c0dcbed3a916f0/README.md#L47) that `documentation_url` in a podspec will override CocoaDocs, though this remains broken.

**Comment by orta** [comment]
Assume this is on the CocoaDocs.org index? happy to take PRs on that, cocoapods.org should be doing it right

**Comment by friedbunny** [comment]
Hi @orta. 👋

Yeah, cocoapods.org [will use](https://github.com/CocoaPods/cocoapods.org/blob/5c65d2542bd8094c3d49b1c74e76fe3c683a75ed/assets/javascripts/search.config.js#L269) `documentation_url` if it’s provided.

I’m actually not clear what the intended behavior of `documentation_url` on cocoadocs.org is, though. Should it direct link to `documentation_url`, or continue to generate and locally host that pod’s docs?

(My personal preference would be the former, as we generate [custom jazzy docs](https://www.mapbox.com/ios-sdk/api/) for our written-in-ObjC framework and have put some effort into [our config](https://github.com/mapbox/mapbox-gl-native/blob/03ebae0f2ed0e5ff2c4fe284d8d3db8960ae4938/platform/ios/jazzy.yml).)

**Comment by orta** [comment]
Heyo 👋 

We do need to generate the documentation for making the CP QIs - http://blog.cocoapods.org/Stats-2015/#web-properties  - though until now, I hadn't really thought about _not_ uploading docs if there's already a documentation URL. Instead just generating it all locally, and not putting new ones up.

The CocoaDocs.org search should be the the same as CocoaPods' though given the traffic difference between the two indexes, all the focus is generally on CocoaPods'.
