### ISSUE TITLE
linkedin social media url breaks layout

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#275]
http://cocoadocs.org/docsets/BFKit/1.1.0/

**Comment by orta** [comment]
This won't break anymore, we have a hardcoded width limit in CSS. It can just mean showing less info.

**Comment by kylef** [comment]
![screen shot 2015-01-21 at 02 13 06](https://cloud.githubusercontent.com/assets/44164/5829478/11f590dc-a113-11e4-8e38-ddb4780018e3.png)

This is still broken?

**Comment by orta** [comment]
not redeployed it

**Comment by orta** [comment]
it'll get it with all the rest eventually

**Comment by kylef** [comment]
:shipit:

**Comment by orta** [comment]
This is fixed, at the core concept. Won't show anything longer than the domain now.
