### ISSUE TITLE
MPMoviePlayerController+XCDOverlayView documentation does not exist

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/cocoadocs.org#276]
Everything is in the title, the documentation of [MPMoviePlayerController+XCDOverlayView](http://cocoadocs.org/docsets/MPMoviePlayerController+XCDOverlayView) was not generated for some reason.

**Comment by orta** [comment]
working fine here?

**Comment by orta** [comment]
It looks like just the docs for [https://github.com/0xced/MPMoviePlayerController-XCDOverlayView/blob/master/MPMoviePlayerController%2BXCDOverlayView/MPMoviePlayerController%2BXCDOverlayView.h](MPMoviePlayerController+XCDOverlayView.h) -> http://cocoadocs.org/docsets/MPMoviePlayerController+XCDOverlayView/1.0.0/Categories/MPMoviePlayerController+XCDOverlayView.html

**Comment by 0xced** [comment]
Haha, I should have waited for the 5-10 minutes after I clicked the rebuild button. Sorry for the noise!

**Comment by orta** [comment]
:+1:
