### ISSUE TITLE
Code coverage  

### ISSUE THREAD

**Issue by dkhamsing** [CocoaPods/cocoadocs.org#277]
Not sure on how this occurred but code coverage for http://cocoadocs.org/docsets/DKScrollingTabController/1.1.2/ shows `$$$DOC_PERCENT$$$%`

CC @orta

**Comment by dkhamsing** [comment]
It now says `100%`

**Comment by kylef** [comment]
@dkhamsing I regenerated your documentation, forgot to update this issue. Must've been something wrong the first time it was generated.

**Comment by dkhamsing** [comment]
thx

**Comment by orta** [comment]
could be a race condition in that a template was being generated at the same time as yours which had been finished was used.
