### ISSUE TITLE
Not generating separate README files?

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#281]
From today:

http://cocoadocs.org/docsets/Doppelganger/1.2/README.html
http://cocoadocs.org/docsets/HYVFourPod/0.1/README.html
http://cocoadocs.org/docsets/URITemplate/1.0.1/README.html

**Comment by segiddins** [comment]
Are those Jazzy pods? That would explain it.

**Comment by kylef** [comment]
http://cocoadocs.org/docsets/URITemplate/1.0.1/ has been treated as an Objective-C pod (though it is a Swift pod). The front page is rendered with CP branding: http://cocoadocs.org/docsets/URITemplate/1.0.1/

**Comment by orta** [comment]
wonder what the output of cloc is on URITemplate, is there more objc file than swift/

**Comment by segiddins** [comment]
@orta, no, there's a cocoapods exception happening, so it's falling back to appledoc. I will investigate.

**Comment by segiddins** [comment]
This was removed (likely accidentally) in https://github.com/CocoaPods/cocoadocs.org/commit/92e7f10d61714248918b3088806309787caa3b2f, will fix right now.
