### ISSUE TITLE
Dash docset index not working for Jazzy docsets

### ISSUE THREAD

**Issue by Kapeli** [CocoaPods/cocoadocs.org#282]
The `Info.plist` contains the entry `dashIndexFilePath: index.html`.

However, `index.html` just contains a redirect:

```
<meta http-equiv='refresh' content='0; url=/docsets/Alamofire/1.1.3'>
```

This just causes Dash to show a 404 page.

**Comment by segiddins** [comment]
Fixed in https://github.com/realm/jazzy/commit/dcca3974bee0bd539b10df780367ef9776a27684, just need to deploy.

**Comment by segiddins** [comment]
Deployed.
