### ISSUE TITLE
README anchors incorrect

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/cocoadocs.org#286]
The [Nimble](http://cocoadocs.org/docsets/Nimble/0.3.0/) docket looks awesome, but the Table of Contents at the top of the README has links that don't work. For example, http://cocoadocs.org/docsets/Nimble/0.3.0/#installing-nimble-via-cocoapods is missing the `user-content-` prefix. Maybe we can use Nokogiri to modify the parsed markdown from the HTML to add this prefix?

**Comment by orta** [comment]
Interesting, yeah, that'd be nice, I think we're already doing something like this.

Also, pretty sure this is mostly a swift app, so I'm surprised it didn't use jazzy. /cc @segiddins
