### ISSUE TITLE
Add support for previewing docs for local repos/podspecs

### ISSUE THREAD

**Issue by armadsen** [CocoaPods/cocoadocs.org#287]
It would be very useful to be able to preview docs generated from a local repo. That way, e.g. .cocoadocs.yml can be validated before pushing to public master.

**Comment by kylef** [comment]
This is already possible, please see the section in the titled ["Previewing my library in CocoaDocs"](https://github.com/CocoaPods/cocoadocs.org#previewing-my-library-in-cocoadocs).

**Comment by armadsen** [comment]
Unless I missed something you can only preview docs generated from the public version (e.g. On Github) of a repo. This issue was opened per Orta's request: http://twitter.com/orta/status/558992585361215488

**Comment by orta** [comment]
This is in, the `preview` command now takes an extra argument which is used for the branch.
https://github.com/CocoaPods/cocoadocs.org/commit/972de892c71f5f80baa798282d0c990208b9d30a
