### ISSUE TITLE
Documentation not updating: VVJSONSchemaValidation

### ISSUE THREAD

**Issue by vlas-voloshin** [CocoaPods/cocoadocs.org#288]
Hi! It's been a few weeks since my pod `VVJSONSchemaValidation` has been updated from version 1.1.0 (which is currently present on cocoadocs) to version 1.2.0, but documentation is still stale. I've tried triggering the update manually, both from 404 page and directly via redeploy URL (as per documentation page), but those don't seem to have an effect. Redeploy URL, in particular, seems to timeout at all. Error URL also times out for either version.
I tried making a preview of documentation on my machine, at it was constructed correctly, though `appledoc` had this to say:
```
/Users/vlas/Projects/cocoadocs.org/activity/download/VVJSONSchemaValidation/1.2.0/VVJSONSchemaValidation/VVJSONSchemaValidation/NSArray\+VVJSONComparison.h 
<... a long, similar list of source files ...>
/Users/vlas/Projects/cocoadocs.org/activity/download/VVJSONSchemaValidation/1.2.0/VVJSONSchemaValidation/VVJSONSchemaValidation/VVJSONSchemaValidator.h failed!
```
Not sure if that's related – the documentation for that last source file was also generated correctly.

**Comment by orta** [comment]
the latest builds of appledoc _always_ fail, even when they have succeeded, I've debated removing the system checks for it but have just been living with it in th hopes that a new release will fix

**Comment by orta** [comment]
Tests and builds fine locally ( in the process it's updated `1.2.0` for you ) - thanks for the issue, will keep open until appledoc doesn't always fail :/

**Comment by vlas-voloshin** [comment]
Thanks for your help, @orta! Hopefully issues with appledoc will be resolved soon :smiley:

**Comment by ericleich** [comment]
Apologies for hijacking the issue, but I feel it's similar enough to be worth adding here. The [Google-Mobile-Ads-SDK](http://cocoadocs.org/docsets/Google-Mobile-Ads-SDK) defaults to 6.11.1, even though there are newer versions 6.12.0, 6.12.2, and 7.0.0.

For some reason unknown to me, 6.12.0 loads but can't load ObjC classes, 6.12.2 returns a 404, and 7.0.0 appears to work fine, but that's not the default version. Is this related to the appledoc problem?

**Comment by segiddins** [comment]
@ericleich 7.0.0 seems to be the default for me

**Comment by orta** [comment]
Working on the 7.0.0 redirect for me too, we'll be doing a full history re-run of CocoaDocs soon. 

That said, the original issue why we kept this issue open was resolved by @segiddins so I'm closing the issue.

**Comment by ericleich** [comment]
I'm seeing it default to 7.0.0 for me too now. Sweet.
