### ISSUE TITLE
CocoaDocs not generated for my CocoaPod 

### ISSUE THREAD

**Issue by hretarekar** [CocoaPods/cocoadocs.org#290]
Here is my github link: https://github.com/Espreccino/PepperTalkSDK-iOS. I keep on getting 404 even after couple of hours of pushing the pod spec to trunk.

**Comment by orta** [comment]
This is up, and I've improved the title around linked in addresses https://github.com/CocoaPods/cocoadocs.org/commit/72d89871ac84f80c73af86ba6b19ee17d85d0559
