### ISSUE TITLE
Official Facebook SDK (3.23.0) - cannot install pod, docs page is down too

### ISSUE THREAD

**Issue by matfin** [CocoaPods/cocoadocs.org#295]
On attempting to view the docs for the version of the Facebook iOS sdk, the page appears to be down. Please see - http://cocoadocs.org/docsets/Facebook-iOS-SDK/3.23.0

Adding this to my Podfile and running 'pod install' or 'pod update' results in a hang.

- pod 'Facebook-iOS-SDK', '~> 3.23.0'

Paste of verbose output from running pod install. 

matfin$ pod install --verbose
  Preparing

Analyzing dependencies

Updating spec repositories
  $ /usr/bin/git rev-parse  >/dev/null 2>&1
Updating spec repo `master`
  $ /usr/bin/git pull --ff-only

**Comment by orta** [comment]
This Pod is crashing appledoc, https://github.com/CocoaPods/cocoadocs.org/issues/284 - I'm keeping my eyes on the project to see when a new release comes out.

The pod issue should go on cocoapods/cocoapods really :+1:

**Comment by matfin** [comment]
Hey. Thanks for taking a look. Installing the latest prerelease version of Cocoapods (0.36.0.beta.2) fixed the issue with installing the Facebook SDK - no more hanging.

**Comment by orta** [comment]
awesome
