### ISSUE TITLE
Cocoadocs not generated

### ISSUE THREAD

**Issue by srinidhirao** [CocoaPods/cocoadocs.org#296]
Hi,
I published UnviredSDK.podspec an hour ago. Cocoadocs are not generated and no error information. Link to Podspec file: https://github.com/CocoaPods/Specs/tree/master/Specs/UnviredSDK. Can you guys check whats the issue with this?
Thank you.

**Comment by ayushn21** [comment]
I'm seeing the same issue. This is the link to my podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/ANRestOps/1.0.0/ANRestOps.podspec.json

**Comment by srinidhirao** [comment]
Got the cocoadocs generated after a day of submission. Thanks.
