### ISSUE TITLE
My Cocoadocs have stopped working

### ISSUE THREAD

**Issue by zzishdev** [CocoaPods/cocoadocs.org#297]
Hey guys. I'm new to the Cocoadocs world. I have had a few versions uploaded and docs have generally be generated. I'm now at 0.3.5 but since 0.3.1, it has stopped generating. I think it might be because I accidentally submitted 0.3.2 twice (stupid repo issue). Anyone have thoughts on this?

http://cocoadocs.org/docsets/ZzishSDK

Thanks

Samir

**Comment by orta** [comment]
Our Mac VPS went down over the weekend, I'm waiting on feedback on getting it back up. Will re-parse everything from the weekend. :+1:
