### ISSUE TITLE
404 for Dynamic-Yield-iOS-SDK Docs

### ISSUE THREAD

**Issue by idanoshri** [CocoaPods/cocoadocs.org#299]
i have uploaded version 1.2.3 and the docs button gives 404

only 1.2.0 works

http://cocoadocs.org/docsets/Dynamic-Yield-iOS-SDK/1.2.3

thanks for the help

**Comment by pronebird** [comment]
Same for http://cocoadocs.org/docsets/UIScrollView-InfiniteScroll/0.6.0

**Comment by lwburk** [comment]
Same for ForeSee 4.2.1

http://cocoadocs.org/docsets/ForeSee/4.2.1

Previous version works:

http://cocoadocs.org/docsets/ForeSee/4.1.0/

**Comment by orta** [comment]
Closing this, as it's a really old issue and I don't want people bringing it back up.
