### ISSUE TITLE
URLs to reparse docs and check for errors time out and don't appear to work

### ISSUE THREAD

**Issue by daniel-hall** [CocoaPods/cocoadocs.org#300]
Several days ago I pushed updates to a pod (PrestoData).  The current version shown on cocoapods.org is correct and matches what I pushed (0.2.3).

However, cocoadocs.org still shows the (not fully parsed) docs only for version 0.1.0 and returns a 404 error for all later versions, including the version that is linked to from cocoapods.org.

The buttons on the 404 page labeled "Alternatively click here to trigger a docs re-parse & wait 5-10 minutes." and "Potential error info" don't seem to have any effect when pressed. 

The URLs specified at http://cocoadocs.org/readme for reparsing and checking for errors all time out with no response from the server.

Example:

http://199.229.252.197:4567/redeploy/PrestoData/latest
http://199.229.252.197:4567/error/PrestoData/0.2.3

I tried substituting other Pod names / version numbers into the URLs, instead of my own, and I still get the same timeouts.

At the end of the day, the docs simply don't seem to parse or reparse.

**Comment by segiddins** [comment]
It's possible the server is down

**Comment by wessmith** [comment]
Seems the server has been down for about 3 days. I pushed a release on 2/15 and haven't seen the docs updated yet.

**Comment by daniel-hall** [comment]
I think I first saw this problem last Friday, so it's possible the service has been down for 5 days.

**Comment by orta** [comment]
Looks like the server has been having serious space issues, I'm struggling to get in. 
For the moment I've commandeered a Mac Mini in my office to re-run all documents it would have done in the last week, it's currently on specs beginning with D.

**Comment by daniel-hall** [comment]
Thanks @orta  - appreciate the interim solution!

**Comment by wessmith** [comment]
Yes! Thanks @orta. Our docs look great!

**Comment by orta** [comment]
:+1:
