### ISSUE TITLE
/docsets/PODNAME should redirect to latest stable release

### ISSUE THREAD

**Issue by mickeyreiss** [CocoaPods/cocoadocs.org#303]
http://cocoadocs.org/docsets/Braintree currently redirects to http://cocoadocs.org/docsets/Braintree/3.6.0-rc3 rather than the expected http://cocoadocs.org/docsets/Braintree/3.5.0/.

In my opinion, the default redirect should be the latest _stable_ release, just like `pod "Braintree"`.

@segiddins I thought you had prepared a fix for this, but it still seems to be the case on the cocoadocs.org live site.

**Comment by segiddins** [comment]
I did add a fix for this, but (a) I don't know if it was ever deployed and (b) to take effect, a new version of the pod will need to be documented.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/cocoadocs.org/commit/f89f86d7531c882ac04290dcc3d63381512a148a - relevant commit

**Comment by orta** [comment]
hrm, I'm pretty sure I'll have updated since then, but I'm in the process of getting the server working again, will ensure it's at HEAD

**Comment by mickeyreiss** [comment]
Thanks for investigating. New version of the pod was pushed to trunk today.

**Comment by orta** [comment]
Server is definitely at head now :+1:

**Comment by mickeyreiss** [comment]
:tangerine:
