### ISSUE TITLE
404 on Apple-clang-format

### ISSUE THREAD

**Issue by spacedrabbit** [CocoaPods/cocoadocs.org#304]
Attempted to download through Dash, and received the following message:

![screen shot 2015-02-27 at 12 37 12 pm](https://cloud.githubusercontent.com/assets/3860223/6417736/9452e82c-be7d-11e4-8ac7-57ab634d84ab.png)

This was mirrored when I tried to locate the same document through the Cocoadocs site

**Comment by orta** [comment]
![screen shot 2015-02-27 at 17 51 52](https://cloud.githubusercontent.com/assets/49038/6422728/e053281e-bea9-11e4-8582-c7419f63e5d2.png)

I couldn't find a Pod called this, unsure how it ends up in the search.
