### ISSUE TITLE
.cocoadocs.yml stopped working

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/cocoadocs.org#305]
I have the following .cocoadocs.yml file:
https://github.com/pronebird/PBPopinController/blob/master/.cocoadocs.yml

which worked perfectly fine for previous release:
http://cocoadocs.org/docsets/PBPopinController/0.1.2/

but then stopped working at version 0.2.0.

**Comment by k0nserv** [comment]
Is this still an issue? Seems to be working now. http://cocoadocs.org/docsets/PBPopinController/0.2.0/

**Comment by pronebird** [comment]
Not anymore.

**Comment by k0nserv** [comment]
:+1:
