### ISSUE TITLE
Error 404 for DFImageManager 

### ISSUE THREAD

**Issue by kean** [CocoaPods/cocoadocs.org#306]
Hi! 

There is a 404 for [DFImageManager 0.0.18](http://cocoadocs.org/docsets/DFImageManager/0.0.18), which was pushed several hours ago. Docs re-parse didn't help.

P.S. Appreciate your work on Cocoadocs, everything was perfect for previous 17 versions. Thank so much.

**Comment by orta** [comment]
No worries! Looks like Appledoc is crashing on your library,  :(

```
appledoc version: 2.2.1 (build 1333)

Caught: AppledocException: Path or file '/Users/orta/spiel/html/Strata/cocoadocs.org/activity/download/DFImageManager/0.0.18/DFImageManager/DFImageManager/Source/Fetchers/Assets' doesn't exist!
```

Ring a bell for you?

**Comment by kean** [comment]
There is an "Assets Library Fetcher" folder. I checked previous versions and there were no changes in DFImageManager/Source/Fetchers/ folder since version 0.0.15.

![screen shot 2015-03-02 at 3 08 48 pm](https://cloud.githubusercontent.com/assets/1567433/6454492/158ec2fe-c0ee-11e4-9a91-974fdf9123a0.png)

**Comment by kean** [comment]
Hi, it's 404 again for [0.2.0](http://cocoadocs.org/docsets/DFImageManager/0.2.0/) (uploaded 6 days ago) and [0.2.1](http://cocoadocs.org/docsets/DFImageManager/0.2.1/) (uploaded 4 days ago) :crying_cat_face:
