### ISSUE TITLE
ERROR 404 on GKGraphKit

### ISSUE THREAD

**Issue by danieldahan** [CocoaPods/cocoadocs.org#308]
Hey! This page is coming up as an error for some reason. http://cocoadocs.org/docsets/GKGraphKit/0.1.6

**Comment by orta** [comment]
Think this just got missed earlier, I did a 2 day docs re-parse, and this was included :+1:

**Comment by danieldahan** [comment]
Thank you :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
