### ISSUE TITLE
Never re-reading/parsing docs for Pod

### ISSUE THREAD

**Issue by fabioknoedt** [CocoaPods/cocoadocs.org#309]
I have a Pod that still has the documentation indexed from the first version (1.0) and it was never indexed again: http://cocoadocs.org/docsets/YCFirstTime/

I even tried to push a button to "re-parse" several times and after days, nothing.
Am I doing something wrong?

This is not happening, since I release like 5 version after the 1.0 and it was never reindexed:
"This triggers a process that will generate documentation for objective-c projects via appledoc and host them for the community. This process can take around 15 minutes after your Podspec is published via trunk."

Thanks!

**Comment by orta** [comment]
I re-ran this from ssh and everything worked fine, I don't think there's anything wrong with what you're doing. I think it's just some instability we're dealing with as CD scales.

**Comment by fabioknoedt** [comment]
Thanks a lot!

Can I also trigger that for my projects or just the cocoadocs admins?

**Comment by orta** [comment]
Yeah, you should have been able to re-trigger via that command on the 404 page, looks like the server was down this morning.

**Comment by fabioknoedt** [comment]
Alright, thanks!
