### ISSUE TITLE
"Class References" side bar missing (pod: JSQSystemSoundPlayer)

### ISSUE THREAD

**Issue by jessesquires** [CocoaPods/cocoadocs.org#312]
This is pretty strange. For `v2.0.0`, docs look fine. For `v2.0.1`, the "Class References" side bar is missing.

`JSQSystemSoundPlayer 2.0.0`
http://cocoadocs.org/docsets/JSQSystemSoundPlayer/2.0.0

`JSQSystemSoundPlayer 2.0.1`
http://cocoadocs.org/docsets/JSQSystemSoundPlayer/2.0.1

**Comment by orta** [comment]
Unsure as of yet.

**Comment by jessesquires** [comment]
Hey @orta - brief update for you.

I just pushed `3.0.0` and the issue persists.

Also of note, **all** versions after `1.1.0` are experiencing this issue. Though, if I remember correctly this wasn't always the case — that is, `2.0.0` used to display properly.

**Comment by orta** [comment]
So, I've reduced this down to: 

```
/**
 *  A completion block to be called after a system sound has finished playing.
 */
typedef void(^JSQSystemSoundPlayerCompletionBlock)(void);

```

Removing this line makes the docs work, looks like weird appledoc oddness

**Comment by orta** [comment]
moving it to the bottom of the header makes it work, not sure if that would compile though.

**Comment by jessesquires** [comment]
Ah... interesting! Thanks @orta !
