### ISSUE TITLE
The "See Also" fields are always empty

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/cocoadocs.org#314]
In recent docsets all *See Also* fields are empty. For example:
* [[AFURLSessionManager attemptsToRecreateUploadTasksForBackgroundSessions]](http://cocoadocs.org/docsets/AFNetworking/2.5.1/Classes/AFURLSessionManager.html#//api/name/attemptsToRecreateUploadTasksForBackgroundSessions)
* [[BITAuthenticator authenticationSecret]](http://cocoadocs.org/docsets/HockeySDK/3.6.2/Classes/BITAuthenticator.html#//api/name/authenticationSecret)
* [[XCDYouTubeClient languageIdentifier]](http://cocoadocs.org/docsets/XCDYouTubeKit/2.1.1/Classes/XCDYouTubeClient.html#//api/name/languageIdentifier)

It used to work in older docsets:
* [[AFURLSessionManager attemptsToRecreateUploadTasksForBackgroundSessions]](http://cocoadocs.org/docsets/AFNetworking/2.4.0/Classes/AFURLSessionManager.html#//api/name/attemptsToRecreateUploadTasksForBackgroundSessions)
* [[BITAuthenticator authenticationSecret]](http://cocoadocs.org/docsets/HockeySDK/3.5.0/Classes/BITAuthenticator.html#//api/name/authenticationSecret)
* [[XCDYouTubeClient languageIdentifier]](http://cocoadocs.org/docsets/XCDYouTubeKit/2.0.2/Classes/XCDYouTubeClient.html#//api/name/languageIdentifier)

**Comment by orta** [comment]
Got it, it was an issue from a manual migration to the new appledoc templating system - thanks @0xced

**Comment by 0xced** [comment]
Woot, that was fast! 💥

Any chance to regenerate those docsets?

**Comment by orta** [comment]
I'll be in my office on friday, and will re-trigger another run-through

**Comment by 0xced** [comment]
👍

**Comment by 0xced** [comment]
It looks like it worked fine for AFNetworking and HockeySDK but not for XCDYouTubeKit. 😞 The [first](http://cocoadocs.org/docsets/AFNetworking/2.5.1/Classes/AFURLSessionManager.html#//api/name/attemptsToRecreateUploadTasksForBackgroundSessions) [two](http://cocoadocs.org/docsets/HockeySDK/3.6.2/Classes/BITAuthenticator.html#//api/name/authenticationSecret) links now have their *see also* fields filled but it’s still empty for the [third](http://cocoadocs.org/docsets/XCDYouTubeKit/2.1.1/Classes/XCDYouTubeClient.html#//api/name/languageIdentifier).

**Comment by 0xced** [comment]
Well, it’s back in the [2.1.2 docset](http://cocoadocs.org/docsets/XCDYouTubeKit/2.1.2/Classes/XCDYouTubeClient.html#//api/name/languageIdentifier). 😃
