### ISSUE TITLE
Docs for ORSSerialPort won't update to 1.7.0

### ISSUE THREAD

**Issue by armadsen** [CocoaPods/cocoadocs.org#319]
I pushed a new version of ORSSerialPort, 1.7.0, yesterday morning. The docs on CocoaDocs.org haven't updated yet. I've tried triggering a re-parse via the button on http://cocoadocs.org/docsets/ORSSerialPort/1.7.0/ without success. The error info button doesn't do anything. I did test the documentation using CocoaDocs preview feature before pushing the updated podspec, and everything worked fine. The new version does show up on [CocoaPods.org](http://cocoapods.org/pods/ORSSerialPort).

**Comment by armadsen** [comment]
The docs have now updated. It isn't using my custom style from .cocoadocs.yml, but that's not a big deal.

**Comment by orta** [comment]
Sorry, in the process of migrating to a new server! Might be another day or tow before everything is up and running smoothly on the CocoaDocs side, had to get [this finished lately](http://blog.cocoapods.org/CocoaPods.org-Take-Two/).

**Comment by armadsen** [comment]
Having the same trouble with version 2.0.0, which I pushed on Monday.

**Comment by segiddins** [comment]
Cocoadocs is running through the backlog from the past couple of weeks right now.

**Comment by armadsen** [comment]
Thanks for the quick reply. I'll check back in a while.
