### ISSUE TITLE
Migrate to Button server

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#320]
Migrate to CocoaDocs Button"
- [x] Install zsh, appledoc, jazzy, s3cmd
- [x] Ensure the thumbnail generator works
- [x] Make api.cocoadocs.org point to the server
- [x] Update the CocoaDocs 404 js
- [x] Update the CocoaDocs README site
- [x] Update CocoaDocs online at http://status.cocoapods.org
- [x] Blog post

**Comment by orta** [comment]
Done. Will announce today.

**Comment by orta** [comment]
or today

**Comment by neonichu** [comment]
Awesome!

![](http://38.media.tumblr.com/ccb1db010b487cb45d05ab826bc43298/tumblr_mp5561k8T21sy3onao1_500.gif)
