### ISSUE TITLE
Images getting mangled in README

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#321]
Right: 
https://raw.githubusercontent.com/aws/aws-sdk-ios/2.1.0/readme-images/cocoapods-setup-02.png

Wrong: https://raw.github.com/aws/aws-sdk-ios/2.1.0/readme-images%2Fcocoapods-setup-02.png%3Fraw%3Dtrue

**Comment by orta** [comment]
see http://cocoapods.org/pods/AWSS3

**Comment by k0nserv** [comment]
Okay I looked a bit at this and it seems like `Octokit` and Github are not responsible. I suspect that something happens either when writing the markdown to disk or reading it on this [line](https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/readme_generator.rb#L32). I have yet to find the download part

**Comment by k0nserv** [comment]
Okay so this is the problem.
https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/readme_manipulator.rb#L43


This will escape `readme-images/cocoapods-setup-02.png?raw=true` and turn it into `readme-images%2Fcocoapods-setup-02.png%3Fraw%3Dtrue`

**Comment by orta** [comment]
^ fixed.
