### ISSUE TITLE
Jazzy READMEs include module name and title

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoadocs.org#324]
![screen shot 2015-04-07 at 10 56 46](https://cloud.githubusercontent.com/assets/44164/7020931/ceb8d372-dd14-11e4-99f0-2652f7432cae.png)

We should strip these, and it should look like this:

![screen shot 2015-04-07 at 10 57 20](https://cloud.githubusercontent.com/assets/44164/7020945/e2e74ffe-dd14-11e4-8df4-8e12d8940b98.png)

**Comment by orta** [comment]
Yeah definitely- though I don't know how we'd kill the JWT in this case?

**Comment by segiddins** [comment]
The duplicated title is being fixed in Jazzy already.

**Comment by orta** [comment]
:+1:
