### ISSUE TITLE
Documentation is not running

### ISSUE THREAD

**Issue by fnva** [CocoaPods/cocoadocs.org#327]
I've published a new version of the pod, but the documentation is not generated and there is no error:

The new pod is pushed correctly: https://cocoapods.org/pods/AdaptiveArpApi
There is no documentation: http://cocoadocs.org/docsets/AdaptiveArpApi/2.2.11
There is no error: http://api.cocoadocs.org:4567/error/AdaptiveArpApi/2.2.11

I don't have more clues to find the mistake. I hope someone could help me.

**Comment by orta** [comment]
Is it now swift 1.2? We've not migrated CocoaDocs to 1.2 yet.

**Comment by orta** [comment]
that said, I don't think the swift runtime support this solid error reporting yet

**Comment by fnva** [comment]
Yes, it's in Swift 1.2. OK, thanks for the answer!

I wait for the migration! :+1:
