### ISSUE TITLE
Search title cut off on ipad

### ISSUE THREAD

**Issue by squarefrog** [CocoaPods/cocoadocs.org#332]
![image](https://cloud.githubusercontent.com/assets/343450/7285292/6c62b098-e93b-11e4-9218-73b626a0b8e0.jpg)

I'll have a look and see if I can see what is causing this tomorrow

**Comment by orta** [comment]
You've done this on CocoaDocs not CocoaPods :+1:

**Comment by squarefrog** [comment]
I totally meant to do that. Honest. Luckily for me, the problem exists on cocoadocs too 

![image](https://cloud.githubusercontent.com/assets/343450/7285434/641fe2a6-e93c-11e4-8637-87a805d67eaf.jpg)

**Comment by orta** [comment]
haha, nice

**Comment by squarefrog** [comment]
This is weird. For some reason on iPad the search bar is rendering with a height of 1.2 ems. 

On iPhone, this height figure is overriden by (in `max-width: 768px`):

    #search form fieldset input[type=search] {
      height: 1.75em;
    }

But on iPad there isn't this override. It looks like you're pulling it Bootstrap somewhere, but I can't immediately see where you're importing it?

**Comment by squarefrog** [comment]
Ohhhhhh.... its in [search.scss.erb](https://github.com/CocoaPods/cocoapods.org/blob/master/assets/stylesheets/search.scss.erb#L561-L653) :+1:
