### ISSUE TITLE
Still getting 404 on my cocoapod

### ISSUE THREAD

**Issue by sseetal** [CocoaPods/cocoadocs.org#333]
http://cocoadocs.org/docsets/ZzishSDK/0.3.6

It's been a few months since this has worked...

Samir

**Comment by orta** [comment]
Do you have test file referenced in Xcode that don't exist in the file system? Clicking the "potential error button" gives this:

```
No such file or directory @ rb_sysopen - /Users/maddern/dev/cocoadocs.org/activity/download/ZzishSDK/0.3.6/ZzishSDK/Tests/Tests.m

/Users/maddern/dev/cocoadocs.org/classes/testing_idealist.rb:40:in `read'
/Users/maddern/dev/cocoadocs.org/classes/testing_idealist.rb:40:in `estimate_testingness_in_file'
/Users/maddern/dev/cocoadocs.org/classes/testing_idealist.rb:23:in `block (3 levels) in testimate'
/Users/maddern/dev/cocoadocs.org/classes/testing_idealist.rb:22:in `map'
/Users/maddern/dev/cocoadocs.org/classes/testing_idealist.rb:22:in `block (2 levels) in testimate'


```

**Comment by sseetal** [comment]
Hi Thanks for the reply. There was an "error" and I removed it and resubmitted. When I click on "Potential Error Info", i can't open it. In the console, it says

0.3.8:1 Refused to execute script from 'http://api.cocoadocs.org:4567/error/ZzishSDK/0.3.8' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
2015-04-23 13:51:17.920 0.3.8:43 Resource interpreted as Script but transferred with MIME type text/html: "http://api.cocoadocs.org:4567/error/ZzishSDK/0.3.8".

**Comment by sseetal** [comment]
Hey Orta, any thoughts on this?

Samir

**Comment by orta** [comment]
> Do you have test file referenced in Xcode that don't exist in the file system?

**Comment by sseetal** [comment]
I did but removed it.

**Comment by orta** [comment]
Interesting, well I'm adding support right now to check that the file exists before trying to read to it, which should fix the problem form the perspective of CocoaDocs. 

However it's the same error with 0.3.8 as for 0.3.6 - we have a reference to a test file that doesn't exist on the local filesystem.

**Comment by orta** [comment]
Cool, I've successfully re-parsed both 0.3.6 and 0.3.8 via the 404 page 👍
