### ISSUE TITLE
AdformAdvertising v. 2.0 Docs got 404

### ISSUE THREAD

**Issue by vladasdrejeris** [CocoaPods/cocoadocs.org#339]
I have updated AdformAdvertising to version 2.0, but docs haven't updated and only 1.0.1 are available.

Tried to trigger a docs re-parse, but it didn't help.

http://cocoadocs.org/docsets/AdformAdvertising/2.0

Thanks for the help.

**Comment by orta** [comment]
Thanks @vladasdrejeris - this looks like the symptom of a larger problem in CocoaDocs, which I think I've just got fixed and running a backlog of older docs.

http://cocoadocs.org/docsets/AdformAdvertising/2.0/
