### ISSUE TITLE
Specify Author

### ISSUE THREAD

**Issue by shortstuffsushi** [CocoaPods/cocoadocs.org#342]
This is a new feature request, not a bug or anything.

I'm working on the docs for the [Branch SDK](https://github.com/BranchMetrics/Branch-iOS-SDK). The first uploader is listed as the author of our repo, but isn't necessarily the primary point of contact at this point. Would it be possible to add a way to either specify an author, or perhaps pull from the Podspec in the repo?

**Comment by orta** [comment]
We get this from your [Podspec here](https://github.com/BranchMetrics/Branch-iOS-SDK/blob/master/Branch.podspec#L18), so you can change it to be anything you want.

**Comment by orta** [comment]
It's pretty common to just have the company there.

**Comment by shortstuffsushi** [comment]
Thanks @orta. I'm trying to do this with `preview` on a branch (`cocoadocs` in that repo, if you're curious). I changed it to the company, as I suspected it may be coming from the Podspec, but it didn't seem to have any effect. Is it only pulled from `master`, could that be the problem?

**Comment by orta** [comment]
Yeah, it looks up your podspec from the Specs repo then uses that with whatever branch you have. I'd never really considered that you'd want to use the Podspec from inside the library. Really should be a feature.

I wouldn't be too surprised if `ruby cocoadocs.rb cocoadocs doc https://raw.githubusercontent.com/BranchMetrics/Branch-iOS-SDK/cocoadocs/Branch.podspec` correctly previews with the right Podspec

**Comment by shortstuffsushi** [comment]
I gave that a shot just now, but it's reporting that it can't find the file for whatever reason. Either way, it's not a huge issue. It'd be a nice feature, but as long as it's pulling from the repo's podspec and not just the spec owner, that'll work for me :+1:
