### ISSUE TITLE
Docs not generating with redeploy API

### ISSUE THREAD

**Issue by shortstuffsushi** [CocoaPods/cocoadocs.org#344]
I tried to regenerate docs for the Branch SDK earlier today, but haven't seen any updates come through. The docs mentioned there could be as much as a 15 minute delay, but it's not been somewhere around an hour. For reference, [this is the url](http://api.cocoadocs.org:4567/redeploy/Branch/0.7.1) I accessed, and it responded with `{ parsing: true }`.

**Comment by shortstuffsushi** [comment]
Ahh, you know what? It's looking at the tag, at which point I hadn't added the docs. My mistake, sorry.

**Comment by orta** [comment]
👍
