### ISSUE TITLE
Multiline code blocks are shown on single line.

### ISSUE THREAD

**Issue by evgenyneu** [CocoaPods/cocoadocs.org#348]
#### 1. Write a multiline code block in comments.

```
/**
This is a sample text.

  Code line 1.
  Code line 2.
*/
```

Note: I use two-space tab widths in my project.

## Expected behaviour

The lines in the code block are displayed as separate lines.

## Actual behaviour

The lines of the code block is show as a single line.

## Example

Code: https://github.com/evgenyneu/moa/blob/master/Moa/Moa.swift
CocoaDocs: http://cocoadocs.org/docsets/moa/1.0.35/Classes/Moa.html

#### CocoaDocs:

![code_block_format_on_cocoadocs](https://cloud.githubusercontent.com/assets/880411/7895542/d7459dbc-06d7-11e5-8417-9873939b0e5d.png)

#### Xcode 6.4 (6E23):

![xcode_help](https://cloud.githubusercontent.com/assets/880411/7895549/34da01de-06d8-11e5-89ce-43652e6910e3.png)

**Comment by segiddins** [comment]
This is probably a bug in https://github.com/realm/jazzy, rather than CD itself -- @jpsim.

**Comment by evgenyneu** [comment]
Thanks you for pointing to the right place, @segiddins.

I have reposted this issue in jazzy repo https://github.com/realm/jazzy/issues/241
