### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by shortstuffsushi** [CocoaPods/cocoadocs.org#351]
Hi again. I'm a little confused about how coverage is generated on projects, and was hoping you might explain how that's supposed to be set up (or point me at a guide). I couldn't find one.

I did come across [this](https://github.com/CocoaPods/cocoadocs.org/blob/1e1f5dc0cbe7d08238c2751ceaf15d3e5828e20e/classes/testing_idealist.rb#L54) however. I know this is probably still first pass type stuff, but checking for the presence of `testExample` as a precursor for having no tests is probably not right :stuck_out_tongue:

**Comment by segiddins** [comment]
We also check if it's the same length as the Xcode default template...

**Comment by shortstuffsushi** [comment]
I suppose, but that still feels like a weird assumption to make. The presence of the example test doesn't imply a complete lack of tests, especially since you're just reading all the files in that directory. If it was the only file, perhaps.

**Comment by segiddins** [comment]
Pull requests to improve it are welcome :)

**Comment by shortstuffsushi** [comment]
OK. In the mean time, could you address the other question? Is coverage just determined by counting total occurrences of assertions? It seemed like it from what I could gather.

**Comment by orta** [comment]
Its not that weird of an assumption, we check the exact measurements for the single file, if it matches then you had to have deleted x amount of lines, then added x amount of lines and still kept the original string we're searching for. I can't really believe we have many false positives for that. This is only for one file too, it won't negate other files in the project which do have them.

And yes, coverage is only determined by counting assertions

**Comment by shortstuffsushi** [comment]
Ah, ok. I missed that it was only for a single file. That is probably fine then, I thought that was taking the presence of the example test to indicate there were no other tests present.

I thought I had seen at one point a way to include a "coverage" item to the Podspec, but I'm struggling to find that reference. And perhaps that doesn't belong in the Cocoadocs repo anyway.

**Comment by orta** [comment]
We check for the Travis-CI in the CocoaDocs pages: http://cocoadocs.org/docsets/ORStackView/3.0.1/
But haven't made too much movement towards measuring real code coverage via something like Coveralls, https://coveralls.io/r/orta/ORStackView?branch=master and cocoapods.org itself has no sense of the Travis CI work

**Comment by shortstuffsushi** [comment]
Got it, I guess I must have misread whatever it was. Thanks for clarifying.
