### ISSUE TITLE
Swift : misplaced documentation for `subscript`

### ISSUE THREAD

**Issue by groue** [CocoaPods/cocoadocs.org#352]
Hello,

In the http://cocoadocs.org/docsets/GRMustache.swift/0.9.2/Classes/Context.html page, the documentation for `subscript(_:)` is placed in the `Creating Contexts` context section, whereas it should appear under the `Fetching Values from the Context Stack` section, since the declaration of the subscript function is located below the `// MARK: - Fetching Values from the Context Stack` comment.

It looks that this bug is specific to subscript functions.

**Comment by orta** [comment]
This is a [Jazzy](https://github.com/realm/jazzy/) bug
