### ISSUE TITLE
Project not marked as "Independently builds through xcode"

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/cocoadocs.org#356]
A couple projects of mine ([UnzipKit](https://github.com/abbeycode/UnzipKit) for example) do have standalone Xcode support and build with Carthage, but are not [marked as such](https://cocoapods.org/pods/UnzipKit/quality).

I tried reproducing what the [`StatsGenerator.supports_carthage`](https://github.com/CocoaPods/cocoadocs.org/blob/2165b4c78f84896ea5313e48e247c84b1ce1cb3a/classes/stats_generator.rb#L90) method does by creating a new `Cartfile` pointing to a local checkout of my source like so:

```
git "file:///Users/Dov/Source%20Code/UnzipKit" "1.3.2"
```

I then ran `carthage bootstrap` from that directory, and I got the following file: `Carthage/Build/Mac/UnzipKit.framework`, as I expected. Is there anyplace I can view the cocoadocs log output as it handles my project?

**Comment by kylef** [comment]
@abbeycode Your project (UnzipKit) only offers a target for OS X, but the podspec says it's iOS compatible (https://github.com/abbeycode/UnzipKit/blob/master/UnzipKit.podspec#L9) so therefore it's not actually possible to independently all the available platforms (only OS X).

But it seems cocoadocs doesn't actually check this.

**Comment by abbeycode** [comment]
Exactly. I realize that, and I've got a branch now that builds both, but according to the cocoadocs source, that shouldn't matter.

**Comment by orta** [comment]
![screen shot 2015-06-17 at 1 42 27 pm](https://cloud.githubusercontent.com/assets/49038/8214367/b7f9b056-14f6-11e5-9a29-3b2f7c6dd41c.png)

Perhaps a missing tag?

**Comment by kylef** [comment]
@orta It would've failed to upload to trunk if the tag was missing. It's there: https://github.com/abbeycode/UnzipKit/blob/1.3.2/UnzipKit.podspec

**Comment by abbeycode** [comment]
Did it not clone the tag perhaps?

**Comment by orta** [comment]
Killing the cache https://github.com/CocoaPods/cocoadocs.org/commit/45528db3c91fa8e7f16ec5156c2af318e31f1f14 and re-parsing fixed it

![screen shot 2015-06-17 at 1 54 57 pm](https://cloud.githubusercontent.com/assets/49038/8214623/7ce28126-14f8-11e5-96f7-67d1a16eb6b8.png)

**Comment by abbeycode** [comment]
Great, thanks guys!
