### ISSUE TITLE
StatsGenerator::generated_download_size doesn't take into account excluded files

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/cocoadocs.org#358]
I have a library named [UnrarKit](https://github.com/abbeycode/UnrarKit), which only includes code files (no media assets) and totals around 1 MB in size. Running `du -sk` on its `Pods` directory gives me 1120. It's being flagged as a large "download size", though.

It looks like the threshold is [supposed to be](https://github.com/CocoaPods/cocoadocs-api/blob/0b4a416d3492eee478f93d92b622515e8ae99e26/quality_modifiers.rb#L102) 10,000 KB, though. Is the metric looking at the size of the entire repo? I have a bunch of large files that are in the repo just for the unit tests, that are excluded by the Podspec (the whole repo is about 143 MB).

**Comment by kylef** [comment]
@abbeycode It includes the whole size of the repository, since the whole repository will be cloned during `pod install`. It's suggested that you move unrelated assets out of the repository to shave the download size.

**Comment by segiddins** [comment]
It's because `UnrarKit`'s git repo is large, and hence a big download :)

**Comment by abbeycode** [comment]
Alright, that makes sense. The description of the quality modifier made it sound like it's trying to avoid making the app slower, rather than the CocoaPods install time.

**Comment by kylef** [comment]
@abbeycode Yes it is pretty ambiguous. If you have any ideas on how to improve the wording, a pull request would be very appreciated => https://github.com/CocoaPods/cocoadocs-api/blob/master/quality_modifiers.rb#L101

**Comment by abbeycode** [comment]
Done: https://github.com/CocoaPods/cocoadocs-api/pull/6

**Comment by orta** [comment]
Hrm, the actual metric I was looking for was the included files, so it feels more like a bug with the implementation detail. I think it's fine that a `pod install` can take a little bit longer. We should really only be checking the included files. I think the answer is to change the implementation to `du -sk Pods/MyLib`. 

Adding an arbitrary check on the repo size isn't the metric we wanted to check for.

**Comment by segiddins** [comment]
well, it is labeled as `download size`...

**Comment by orta** [comment]
hrrrmmmmmmm, looks like I'm contrarian on the issue.

**Comment by abbeycode** [comment]
@orta Since you merged the pull request, does that mean we're sticking with that definition (download size vs. installed size)?

**Comment by neonichu** [comment]
IMO, download size is the more meaningful metric. If there's a huge discrepancy between download vs. install size, the repo in question is not very well organised.

**Comment by orta** [comment]
The re-definition you offered was much better in general, even if we decide to change the underlying metric then having a better description is till then is a great idea :+1:
