### ISSUE TITLE
PLCrashReporter Crashes

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#359]
http://cocoadocs.org/docsets/PLCrashReporter/1.2.0/

![screen shot 2015-06-18 at 12 45 12 pm](https://cloud.githubusercontent.com/assets/49038/8236672/e25b1e18-15b7-11e5-8200-62f74021eede.png)

**Comment by segiddins** [comment]
@neonichu `PBXAppleScriptBuildPhase` sound familiar?

**Comment by neonichu** [comment]
![screen shot 2015-06-18 at 10 15 25](https://cloud.githubusercontent.com/assets/118992/8237284/03be6cbe-15a3-11e5-8118-b454fff83579.png)

**Comment by neonichu** [comment]
I'll make an Xcodeproj PR for this later in the week.

**Comment by orta** [comment]
Doesn't crash anymore - just given it a run: http://cocoadocs.org/docsets/PLCrashReporter/1.2.0/
