### ISSUE TITLE
Generating docs for BrightFutures fails

### ISSUE THREAD

**Issue by Thomvis** [CocoaPods/cocoadocs.org#361]
I've pushed a new version of my pod yesterday and since then, the documentation for it seems to have broken: http://cocoadocs.org/docsets/BrightFutures/2.0.0.

I tried running cocoadocs locally on my machine to see what is going wrong, but I was unable to have it select the new release (it would select 2.0.0-beta.2 instead of 2.0.0). Other than that, the documentation generated just fine.

I looked up the code corresponding to the stack trace, but didn't see any apparent bug/mistake in the code. If you need any more info, please let me know!

**Comment by segiddins** [comment]
I just pushed a fix to master, it just needs to be deployed.

**Comment by Thomvis** [comment]
That was _fast_! Thanks!
