### ISSUE TITLE
Support for mercurial

### ISSUE THREAD

**Issue by djbe** [CocoaPods/cocoadocs.org#363]
It appears that mercurial is not installed on the CocoaDocs server. Currently, when it tries to generate the documentation, I get the following error:

http://api.cocoadocs.org:4567/error/DJLocalization/1.1.1
```javascript
report_error({
	"message": "\u001b[31m[!] Unable to locate the executable `hg`\u001b[0m",
	"trace": [
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/executable.rb:52:in `execute_command'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:126:in `execute_command'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.0/lib/cocoapods-downloader/base.rb:152:in `block in executable'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.0/lib/cocoapods-downloader/mercurial.rb:42:in `download_revision!'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.0/lib/cocoapods-downloader/mercurial.rb:27:in `download!'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.0/lib/cocoapods-downloader/base.rb:80:in `block in download'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:143:in `block in ui_action'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.37.2/lib/cocoapods/downloader.rb:142:in `ui_action'",
		"/Users/maddern/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.0/lib/cocoapods-downloader/base.rb:78:in `download'",
		"/Users/maddern/dev/cocoadocs.org/classes/source_downloader.rb:36:in `block in download_pod_source_files'",
		"/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'",
		"/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'",
		"/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'",
		"/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'",
		"/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:106:in `timeout'",
		"/Users/maddern/dev/cocoadocs.org/classes/source_downloader.rb:34:in `download_pod_source_files'",
		"/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:393:in `document_spec'",
		"/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:513:in `document_spec_at_path'",
		"/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:155:in `block in doc'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:150:in `each'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:150:in `doc'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:222:in `block in cocoadocs_url'", "/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'", "/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'", "/Users/maddern/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:219:in `cocoadocs_url'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:170:in `cocoadocs'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:114:in `initialize'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:532:in `new'", "/Users/maddern/dev/cocoadocs.org/./cocoadocs.rb:532:in `<main>'"
	]
})
```

**Comment by orta** [comment]
oh, I can fix this :+1:

**Comment by orta** [comment]
It's on

**Comment by orta** [comment]
http://cocoadocs.org/docsets/DJLocalization/1.1.1/

**Comment by djbe** [comment]
It's broken again:

http://api.cocoadocs.org:4567/error/DJFetchedResultsController/1.0.0

	report_error({
	    "message": "\u001b[31m[!] Unable to locate the executable `hg`\u001b[0m",
	    "trace": [
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.38.2/lib/cocoapods/executable.rb:52:in `execute_command'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:128:in `execute_command'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:152:in `block in executable'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/mercurial.rb:42:in `download_revision!'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/mercurial.rb:27:in `download!'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:80:in `block in download'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:145:in `block in ui_action'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-0.38.2/lib/cocoapods/downloader.rb:144:in `ui_action'",
	        "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-downloader-0.9.3/lib/cocoapods-downloader/base.rb:78:in `download'",
	        "/Users/cocoadocs/cocoadocs.org/classes/source_downloader.rb:36:in `block in download_pod_source_files'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:35:in `catch'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/timeout.rb:106:in `timeout'",
	        "/Users/cocoadocs/cocoadocs.org/classes/source_downloader.rb:34:in `download_pod_source_files'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:402:in `document_spec'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:532:in `document_spec_at_path'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:165:in `block in doc'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:160:in `each'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:160:in `doc'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:232:in `block in cocoadocs_url'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'",
	        "/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:229:in `cocoadocs_url'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:180:in `cocoadocs'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:115:in `initialize'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:551:in `new'",
	        "/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:551:in `<main>'"
	    ]
	})
