### ISSUE TITLE
Tests not being correctly recognized for Xcode 7

### ISSUE THREAD

**Issue by joemasilotti** [CocoaPods/cocoadocs.org#364]
🌈I'm building [some helpers](https://github.com/joemasilotti/JAMTestHelper.git) for UI Testing in Xcode 7 and just pushed v0.0.1 to the trunk. The pod is tested with XCTest and uses the normal XCTAssert* macros. However, on cocoapods.org the [page notes that the pod does not include any tests](https://cocoapods.org/pods/JAMTestHelper).

> Moved from CocoaPods/CocoaPods#3776

**Comment by segiddins** [comment]
OK, so the issue here is that your project doesn't seem to have any test targets in it

**Comment by joemasilotti** [comment]
Interesting. Did the `JAMTestHelperUITests` target not get copied into the pod somehow?

**Comment by segiddins** [comment]
Nope -- it actually is a cocoadocs issue :) I should have a fix pushed shortly.

**Comment by segiddins** [comment]
OK, just pushed -- @orta will need to deploy it, though.

**Comment by orta** [comment]
deployed, thanks @segiddins

**Comment by orta** [comment]
![screen shot 2015-07-04 at 08 18 35](https://cloud.githubusercontent.com/assets/49038/8506950/4cc10cb2-2225-11e5-82eb-6c7d1950b7f2.png)

http://metrics.cocoapods.org/api/v1/pods/JAMTestHelper

**Comment by joemasilotti** [comment]
Awesome! Thanks guys. 



—
