### ISSUE TITLE
No tests shown on pod page

### ISSUE THREAD

**Issue by x2on** [CocoaPods/cocoadocs.org#365]
Hi,

on my pod project (https://cocoapods.org/pods/FSOpenInWhatsApp) is shown that there are no test available.

But there are test which also runs automatically with Travis CI.

Any ideas why this happens?

**Comment by segiddins** [comment]
We count 4 tests -- https://metrics.cocoapods.org/api/v1/pods/FSOpenInWhatsApp

**Comment by orta** [comment]
Hrm, I wonder if it makes sense to look in to whether there's `< 10` tests, and then compare the number of tests to the LOC in the pod in order to show that.

**Comment by x2on** [comment]
@segiddins @orta that means on cocoadocs there are only shown tests if there are more than 10 tests, or?

**Comment by orta** [comment]
It's 5, https://github.com/CocoaPods/cocoapods.org/blob/master/views/pod.slim#L9

**Comment by x2on** [comment]
Ok thanks for the info - i will add 1 more test then :) It's a really small helper :sunny:

**Comment by orta** [comment]
:dancers:  workarounds

**Comment by orta** [comment]
:D
