### ISSUE TITLE
SCSafariPageController does not get indexed for quality

### ISSUE THREAD

**Issue by stefanceriu** [CocoaPods/cocoadocs.org#370]
I'm not really sure where it all went wrong but I pushed the initial version of SCSafariPageController on Sunday and it still hasn't been indexed for quality or registered as a new pod.

It's worth mentioning that all CocoaPods related operations work just fine and the documentation looks right http://cocoadocs.org/docsets/SCSafariPageController/1.0.0/

```
pod trunk info SCSafariPageController

SCSafariPageController
    - Versions:
      - 1.0.0 (2015-07-12 20:23:53 UTC)
    - Owners:
      - Stefan Ceriu <stefan.ceriu@yahoo.com>
```

Thanks,
Stefan

**Comment by orta** [comment]
Hrm, interesting, I re-ran this just now and everything is working. I'm not sure what was going on here, but it's working on the site: http://cocoapods.org/pods/SCSafariPageController

**Comment by stefanceriu** [comment]
Well.. it's good enough for me :)

Thank you!
