### ISSUE TITLE
Multiple owners of a project with same name

### ISSUE THREAD

**Issue by x2on** [CocoaPods/cocoadocs.org#371]
Hi,

at https://cocoapods.org/pods/FSImageViewer there are three owners (all me) with the same name but different projects under the name. 
Any idea why this happens? And can i merge them?

Thanks a lot!

Felix

**Comment by orta** [comment]
You have three trunk accounts with access to push to the pod:

![screen shot 2015-07-15 at 07 19 08](https://cloud.githubusercontent.com/assets/49038/8692012/d0212c6e-2ac1-11e5-8de6-26f85d5d2338.png)

**Comment by orta** [comment]
You can pick one, and then [remove the other owners](https://guides.cocoapods.org/terminal/commands.html#pod_trunk_remove_owner).

**Comment by x2on** [comment]
Thanks a lot for the info - will do that :)
