### ISSUE TITLE
Documentation not generating and README not updated

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/cocoadocs.org#372]
I submitted a new version of a pod last night and, upon clicking Documentation, I've only ever gotten a 404 page. I have tried the re-parsing button. Additionally, the README on the main page does not reflect the most current README. Here's the pod for reference: https://cocoapods.org/pods/HNKGooglePlacesAutocomplete

**Comment by kean** [comment]
Same here http://cocoadocs.org/docsets/DFImageManager/0.5.0

**Comment by tarbrain** [comment]
Same here.
http://cocoadocs.org/docsets/TBStateMachine/5.5.0

**Comment by orta** [comment]
Yeah, looks like https://github.com/CocoaPods/cocoadocs.org/commit/531d35c244fd29b2f1a12a189c22815c336c4743 hit all of you, I'm going to re-parse the last weeks worth of docs. Should fix all of this.

**Comment by mats-claassen** [comment]
Hi @orta , I am seeing the same issue with the Readme not updating.
https://cocoapods.org/pods/GooglePlacesRow. Thanks

**Comment by mayankk2308** [comment]
I'm having this issue for **2.0.0** of my pod here: https://cocoapods.org/pods/MKDataDetector
Note that it is compiled in **Swift 4**.

**Comment by Fenil15** [comment]
@orta I am facing the same issue, ReadMe is not updating, any idea?
