### ISSUE TITLE
Pod Quality not marked "Independently builds through Xcode"

### ISSUE THREAD

**Issue by basvankuijck** [CocoaPods/cocoadocs.org#381]
Concerning [ESOpenSourceLicenses](https://cocoapods.org/pods/ESOpenSourceLicenses/quality).
It's not that big of a deal, but I was wondering why it's not.
If I run `carthage bootstrap` the build passes. Or is there something I'm doing wrong.

**Comment by orta** [comment]
<img width="582" alt="screen shot 2015-08-20 at 08 33 21" src="https://cloud.githubusercontent.com/assets/49038/9383317/27f3a7f8-4716-11e5-8a5e-ff27f0b79df9.png">

<img width="585" alt="screen shot 2015-08-20 at 08 32 16" src="https://cloud.githubusercontent.com/assets/49038/9383292/fcbeac9a-4715-11e5-8c4a-83c5ae388048.png">

I'm seeing it fail on CocoaDocs perhaps you have Swift 2.0 in there?

**Comment by basvankuijck** [comment]
No, the source is created / build in Xcode6.4 / iOS8.4
Could it be because Cocoadocs is using iOS8.3 / Xcode6.3.1 ?

But it's not a biggy, I was just wondering why

**Comment by orta** [comment]
Yeah, 8.4 did add nullability changes. Probably time for me to update Xcode over the weekend.

**Comment by orta** [comment]
turns out this was harder than I expected.

**Comment by orta** [comment]
This should all be working now, I've updated to 7.0 :+1:
