### ISSUE TITLE
Your Ruby version is 2.2.3, but your Gemfile specified 2.1.3

### ISSUE THREAD

**Issue by mkistler** [CocoaPods/cocoadocs.org#382]
Attempt to `bundle install` cocoadocs give the error in the subject.  Is it really necessary to restrict cocoadocs to just this specific version of Ruby?

**Comment by segiddins** [comment]
Yes -- that is the version that is tested and deployed.

**Comment by orta** [comment]
You can, of course, do a quick work around for local experimentation by removing that line. However, we want to ensure consistency between local/production stacks :+1:
