### ISSUE TITLE
Docs saying Swift pod it can't parse Objective-C

### ISSUE THREAD

**Issue by rhodgkins** [CocoaPods/cocoadocs.org#385]
Hi,

[HTTPStatusCodes](https://github.com/rhodgkins/SwiftHTTPStatusCodes) is a Swift pod, but the [docs page](http://cocoadocs.org/docsets/HTTPStatusCodes/2.0.0/) is saying it can't parse Objective-C.

But the previous version, [1.0.3](http://cocoadocs.org/docsets/HTTPStatusCodes/1.0.3/) was fine!

Any ideas?!

Cheers,

Rich

**Comment by orta** [comment]
Likely Swift 2.0 crashing, I've not updated Xcode to 7.0 yet on the server. That page is what happens when something crashes.

**Comment by rhodgkins** [comment]
Ah ok! Thanks for the quick reply :)

**Comment by orta** [comment]
OK, just tested and this is working fine - http://cocoadocs.org/docsets/HTTPStatusCodes/2.0.0/

**Comment by esttorhe** [comment]
Question since [RxViewModel](cocoadocs.org/docsets/RxViewModel) is showing the same issue.

I updated to `2.1.0` before `CocoaDocs` migrated to `Xcode 7`.

Do I need to push a new version to trigger the docs? (I have to release a new version soon anyways) or is this an issue worth filing?

**Comment by orta** [comment]
> The 404 page offers a button to request that CocoaDocs takes a second look at running your library, the URL for this is http://api.cocoadocs.org:4567/redeploy/[pod]/latest

You can just make a HTTP call to that page ^ - once #392 is done I'll re-run all pods from the last 3 weeks.

**Comment by esttorhe** [comment]
:bow: got it!

thanks. First time I tried that was on mobile and the `404` label did not let me see the button.

I'll keep an eye on #392 then.

Thanks

**Comment by cezheng** [comment]
@orta Do I need to release a new version to make the docs page available? This swift 2.0 pod still hasn't generated the doc pages. http://cocoadocs.org/docsets/Fuzi/0.1.0/

**Comment by cezheng** [comment]
@orta I tried using the redeploy api but it doesnt seem to have any out put after an hour. Should I wait or try once more or do I need to release a new version? http://api.cocoadocs.org:4567/redeploy/Fuzi/latest

```
{"parsing":true}
```
http://cocoadocs.org/docsets/Fuzi/0.1.0/

**Comment by rhodgkins** [comment]
@orta thanks! :)
