### ISSUE TITLE
Problem generating docs

### ISSUE THREAD

**Issue by cezheng** [CocoaPods/cocoadocs.org#387]
Moving https://github.com/CocoaPods/cocoapods-docs/issues/6 to the right repo.

I also discovered the Kingfisher's Doc(in swift 2.0 style) pages are actually generated, but just not displaying correctly.
http://cocoadocs.org/docsets/Kingfisher/1.5.0/Extensions/UIButton.html#

Yet my Pod's doc pages just failed to even be generated
http://cocoadocs.org/docsets/Fuzi/0.1.0/
so I guess this is not a jazzy version problem.

also the error message "Could not find Objective-C Classes." is weird since this is a swift pod.

**Comment by orta** [comment]
We're not running swift 2 yet on CocoaDocs, perhaps this weekend when I get some free time.

**Comment by cezheng** [comment]
@orta I tried using the redeploy api but it doesnt seem to have any output. http://api.cocoadocs.org:4567/redeploy/Fuzi/latest

```
{"parsing":true}
```

And I also tried pushing a new version, but still the docs are not generated, same old error message "Could not find Objective-C Classes."
http://cocoadocs.org/docsets/Fuzi/0.1.1/

Any idea what happened? I successfully generated doc pages using jazzy 0.3.1 myself though

**Comment by orta** [comment]
> Could not find Objective-C Classes 

This is the message CD gives when jazzy crashes, I should probably update this. ( the latest Fuzi is working fine since CD started supporting Swift 2.1.)

**Comment by cezheng** [comment]
@orta I haven't tried it yet since I generated the docs by myself and put it on gh-pages, specifying the doc's link in podspec so those doc pages are not generated by cocoadocs. I will try letting cocoadocs do this for me in my next release.
