### ISSUE TITLE
Docs not generated, thus pod not showing up correctly on cocoapods.org

### ISSUE THREAD

**Issue by hsoi** [CocoaPods/cocoadocs.org#388]
Hello.

I just created a brand new Cocoapod, https://github.com/HsoiEnterprises/HELargeCenterTabBarController

All seems good, but yet it doesn't show up correctly on the cocoapods.org website.

There are docs:

http://cocoadocs.org/docsets/HELargeCenterTabBarController/1.0.0/

but there's mention of an error parsing the pod (couldn't find objective-c classes) -- I hope not, it's a Swift library. :-)

Checking metrics http://metrics.cocoapods.org/api/v1/pods/HELargeCenterTabBarController lists null for `cocoadocs`

Stats 404: http://cocoadocs.org/docsets/HELargeCenterTabBarController/1.0.0/stats.json

I did try to regenerate a couple times, but no luck.

And so, on cocoapods.org https://cocoapods.org/?q=helargecentertabbarcontroller  it just lists "site/docs/spec" and not "expand".

I've seen some other issues that make me wonder if this is because Swift 2 and Xcode 7.

Thank you.

**Comment by segiddins** [comment]
I don't think cocoadocs is yet using the swift 2 version of jazzy, which is what we use for documenting swift pods.

**Comment by hsoi** [comment]
Yeah, that's what a few other issues filed here lead me to believe.

Still, I hope it's able to be resolved soon as more and more pods are obviously going to be adopting Swift 2.

BTW, in resolving this I don't know if some docs may need to be regenerated -- either by their authors or by y'all. For example:

https://cocoapods.org/pods/ModelRocket

I know that's been updated to Swift 2, but was originally submitted under Swift 1.2. Thus, it has SOME sort of `cocoadocs` entry, but the entry on cocoapods.org is certainly showing the v1.0 README of the library, not the 1.1 Swift 2 version of things. So the docs will need to be regenerated, but not sure whose responsibility it might be to handle that.

**Comment by orta** [comment]
It's my responsibility, I'm probably going to have to use [Genouille](https://github.com/neonichu/grenouille) to determine swift versions in order to not re-run 1.2 versions once I get CD shipped to Xcode 7.

**Comment by hsoi** [comment]
:+1:

**Comment by segiddins** [comment]
@orta the latest version of jazzy can work with multiple swift versions, as long as the appropriate xcodes are all installed.

**Comment by orta** [comment]
smart, is there docs on how I can set that up? or will it search out the right Xcode in `/Applications` via info plist?

**Comment by segiddins** [comment]
It'll find any Xcode that spotlight can find

**Comment by orta** [comment]
someone did well, if that was you, good job, if it was @jpsim you did well.

**Comment by jpsim** [comment]
All credit to @segiddins for that one! You *do* need to explicitly specify the `--swift-version` however, Jazzy won't automatically determine which Swift version to build for.

**Comment by orta** [comment]
Cool, looks like I'll still need grenouille :+1:

**Comment by orta** [comment]
The libraries mentioned in here have been re-generated since I brought CD up to date today, and I've made another issue around multiple versions

**Comment by hsoi** [comment]
@orta have they been regenerated?  When I check the docs, metrics, stats.json... there appears to be no change (for HELargeCenterTabBarController nor ModelRocket).

What am I missing/misunderstanding here?

**Comment by orta** [comment]
hrm, it does look that way

**Comment by hsoi** [comment]
@orta any update on this?

**Comment by orta** [comment]
I'm afraid I've been pretty busy with Artsy work, and probably will be until the apple TV comes out alas, will carry on with OSS maintenance stuff after that, this is staying open so I know that it's on my TODO. If you'd you like you clone a copy of this repo and give the `preview` [command](https://github.com/CocoaPods/cocoadocs.org/) a run and see what breaks

**Comment by hsoi** [comment]
Hi @orta  How goes the battle here?

**Comment by orta** [comment]
Supporting multiple swift versions will probably never happen now, but I triggered a re-pased, some of the fixes between October and now fixed your libraries: 

http://cocoadocs.org/docsets/HELargeCenterTabBarController/1.0.0/
http://cocoadocs.org/docsets/ModelRocket/1.2.4/

**Comment by hsoi** [comment]
Well, it's a bummer... but it is what it is I guess.

Thanx.
