### ISSUE TITLE
What is wrong If I have following error?

### ISSUE THREAD

**Issue by kunass2** [CocoaPods/cocoadocs.org#390]
![screen shot 2015-09-23 at 16 59 40](https://cloud.githubusercontent.com/assets/9480650/10049055/1dbec7d4-6216-11e5-9eec-7e68f8582615.png)

**Comment by kunass2** [comment]
[Here](https://github.com/kunass2/BSTableViewReorder) is my repository. Did I miss sth?

**Comment by orta** [comment]
CocoaDocs is currently down, we're migrating to El Cap + Xcode 7 - https://status.cocoapods.org
