### ISSUE TITLE
docs not generating for updated obj-c pod.

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/cocoadocs.org#391]
I updated my pod with more complete documentation and cocoadocs fails to generate docs.
I have tried re-generating with no joy.

http://cocoadocs.org/docsets/RCBRightClick/0.1.4

I downloaded appledoc to test - and it does correctly parse my class with no errors (and correct-looking output).

I get a connection refused for:
http://api.cocoadocs.org:4567/error/RCBRightClick/0.1.4

thank you.

**Comment by orta** [comment]
CocoaDocs is still down - https://status.cocoapods.org
Looking like it'll be back up today.

**Comment by ConfusedVorlon** [comment]
thanks.

might be worth adding a link to  https://status.cocoapods.org/ to 

http://orta.io/rebase/why-cant-i-expand/ (which is the page I found first)
and http://cocoadocs.org/readme/

possibly even add it to the doc-specific 404 page?

**Comment by orta** [comment]
Good calls.

**Comment by orta** [comment]
I did a bunch of this.
