### ISSUE TITLE
FR: Rename integration size to download size and add integration size

### ISSUE THREAD

**Issue by beriberikix** [CocoaPods/cocoadocs.org#395]
_Moved from cocoapods/cocoapods#4315_

The current metric for integration size actually represents download size (discussed in cocoapods/cocoapods#3716.) I was wondering if you could separate out size into 2 metrics - actual integration size and download size. Integration size would represent the increase in final app size as submitted to the App Store while the download size refers to the size a Pod talks up on my dev machine.

While I agree both are important for the reasons mentioned in #3716, impact on final app size is the metric most folks we've spoken to care about. The two separate metrics can (and hopefully should) be weighted differently.

**Comment by orta** [comment]
Interesting, I don't know how much they would differ, will have to experiment before committing to an aye/nay

**Comment by beriberikix** [comment]
Cool, thanks for looking into it! As a point of reference, CocoaDocs reports that GoogleMaps has an integration size 84404 kb while adding it to an app adds ~11megs.

**Comment by orta** [comment]
Thanks, that's pretty considerable!

**Comment by perotinus** [comment]
I think pods with vendored targets would see a noticeable difference: right now, the vendored pods are generally shipped with all the architectures they support included, but the binary that developers ship to Apple only has the `armv7` and `arm64` slices.

I'm not so sure about other pods. From what I can see, pods that have `preserve_paths` that they don't include in the app would benefit; pods with large `README` files would benefit; pods with lots of comments in their header files would benefit; and probably some other pods too. It's not clear, though, that the size difference would be significant, or that pods would change significantly in relation to each other.

**Comment by orta** [comment]
I think, given how hard this one is to get right, it might be worth outright removing the QI for sizes - especially given that BitCode negates a lot of this stuff. May even be worth outright removing the whole stat, as being irrelevant when deciding to integrate a lib,

**Comment by finik** [comment]
What is this metric exactly and how is it calculated then? It is not download size either!

https://cocoapods.org/pods/bugsee is shown as 100mb, yet the download size ~20mb (with 5 archs, bitcode and symbols) and the actual integration size (the amount IPA is growing by) is 200kb. This is confusing, and I have people constantly asking about it. This is orders of magnitude off the real number. Can we please remove it?

**Comment by patchthecode** [comment]
@finik sounds like a bug.. see.. 😂

**Comment by orta** [comment]
Fixed, by me removing the feature entirely in https://github.com/CocoaPods/cocoadocs-api/pull/30
