### ISSUE TITLE
Sample project header files included

### ISSUE THREAD

**Issue by jgimenez** [CocoaPods/cocoadocs.org#396]
I have a repository with a `.framework` and some sample code.

The `Podfile` references the `vendored_framework` but doesn't mention any `source_files`, `public_header_files` nor `private_header_files`. It looks like CocoaPods understands this as "not to import any .h files". However CocoaDocs understands it as "import all .h files". I have no way to exclude the sample project from the documentation.

You can see here the repository structure and Podspec: https://github.com/bugfender/BugfenderSDK-iOS . The [generated docs](http://cocoadocs.org/docsets/BugfenderSDK/0.3.12/) contain also the sample project classes (all but Bugfender), which I'd like to avoid.

Also I wouldn't like to remove the sample code, since I find the `pod try` feature quite nice.

Am I doing something wrong? Thanks

**Comment by jgimenez** [comment]
@segiddins in my case the vendored framework headers are also included, I'd like the other headers not to be included. Will this patch also fix this case?

**Comment by segiddins** [comment]
@jgimenez try out the PR locally if you want to validate that it works?

**Comment by jgimenez** [comment]
Sorry Samuel, I tried but I got an error and couldn't work it out.

On Sunday, 11 October 2015, Samuel E. Giddins <notifications@github.com>
wrote:

> @jgimenez <https://github.com/jgimenez> try out the PR locally if you
> want to validate that it works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaPods/cocoadocs.org/issues/396#issuecomment-147205797>
> .
>


-- 

Jordi Giménez | Mobile Jazz
+34 644 350 850 | http://mobilejazz.com | PGP: 0xad23914606d3c5b6

**Comment by jgimenez** [comment]
Thanks!
