### ISSUE TITLE
Cocoadocs Quality Metrics do not pick up CHANGELOG in AFNetworking

### ISSUE THREAD

**Issue by kcharwood** [CocoaPods/cocoadocs.org#400]
Was looking through the [quality metrics](https://cocoapods.org/pods/AFNetworking/quality) for AFNetworking, and I noticed the CHANGELOG metric was not being applied despite the project [having one](https://github.com/AFNetworking/AFNetworking/blob/master/CHANGELOG.md).

**Comment by orta** [comment]
<img width="1280" alt="screen shot 2015-10-28 at 09 52 41" src="https://cloud.githubusercontent.com/assets/49038/10785112/b8b7a220-7d59-11e5-89e1-aa9b62ecf96e.png">

Carthage is crashing on the CocoaDocs server, and locking forever, so CD never gets to the doc uploading stage. I'll add a timeout loop around it.

**Comment by orta** [comment]
I updated carthage to yesterday's release and now it doesn't break the build. :+1: 

https://cocoapods.org/pods/AFNetworking#changelog
