### ISSUE TITLE
Version resolver ignores alpha buids

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#403]
http://cocoadocs.org/docsets/ReactiveCocoa/ goes to 3.0.0 - but 4.0.4-alpha1 is the latest. Looks [like](https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/docset_fixer.rb#L187)

```
    latest_version = versions.reverse_each.find { |v| v !~ /[a-zA-Z_-]/ } || versions.last
``` 

is the culprit, but do we want to redirect to alpha versions?

**Comment by segiddins** [comment]
I think it's intentional that we only link to the latest _stable_ version.

**Comment by orta** [comment]
CocoaPods.org goes to 4.0.4a1 so yes, https://cocoapods.org/pods/ReactiveCocoa

**Comment by orta** [comment]
This was fixed in https://github.com/CocoaPods/cocoadocs.org/pull/409
