### ISSUE TITLE
Docs for mixed Objective-C/Swift library

### ISSUE THREAD

**Issue by NachoSoto** [CocoaPods/cocoadocs.org#404]
_I couldn't see any issues regarding this, but apologies if it's a dupe._

As I understand it, `Cocoadocs` will decide to use either `Jazzy` or `Appledoc` depending on the language of the library.
For [`ReactiveCocoa`](https://github.com/ReactiveCocoa/ReactiveCocoa) this is unfortunate, because it contains more `Objective-C` code than `Swift`, so the docs don't pick up any of the new `Swift` types in `RAC 3/4`.

What does everyone think about this issue? I think there are a few possible options (assuming I'm understanding this problem right):
- **Support both languages:** probably the highest cost, but ideal solution.
- **Allow libraries to specify the language**: that way libraries like `RAC` could favor `Swift` docs over `Objective-C`, given that it's the new implementation. Not ideal, but possibly the simplest to implement.
- **Somehow generate 2 different sets of documentation, one per language**: not sure if it's possible in practice, but I can see this being another low-cost solution.

Thanks :star:!

I mean, :heart:!

**Comment by orta** [comment]
> I mean, :heart:!

hah.

So it's likely that https://github.com/jpsim/SourceKitten/pull/57 is going to probably be the answer for this, meaning a move to supporting only Jazzy. Though, how well that works on plain of static libraries is something I don't know yet.  

I don't think 2 sets of docs is feasible, at least not in a reasonable way. But allowing the library to select the language is an interesting choice, we already have [config files](http://cocoadocs.org/readme/) so libraries can use their own colour schemes or custom `pod try` pre-install hooks. So it's definitely an option if it looks like Objective-C Jazzy is way off.

**Comment by NachoSoto** [comment]
Thanks for the response @orta!

Looks like that PR was merged :) What would it take to move `CocoaDocs` to only-`Jazzy`?

**Comment by segiddins** [comment]
I'll look into it soon, but jazzy doesn't yet support mixed projects.

**Comment by NachoSoto** [comment]
Friendly ping :) what's the status of this?

**Comment by segiddins** [comment]
Still blocked by support in jazzy.

**Comment by NachoSoto** [comment]
Is there an issue in Jazzy or should I open one?

**Comment by segiddins** [comment]
Can't remember, but i know it's on our todo list.

**Comment by orta** [comment]
Going to close this, it's something that only Jazzy can do 👍
