### ISSUE TITLE
can not get the latest repo

### ISSUE THREAD

**Issue by coderyi** [CocoaPods/cocoadocs.org#406]
my cocoapods repo is [NetworkEye](https://github.com/coderyi/NetworkEye)  is 0.9.8 ,but i use "pod "NetworkEye" ", can not get the latest 0.9.8,  it is 0.9.7;

and  http://cocoadocs.org/docsets/NetworkEye/0.9.7/index.html   is error page,   but http://cocoadocs.org/docsets/NetworkEye/0.9.8/index.html  is right

**Comment by orta** [comment]
Both of these are working for me?

**Comment by coderyi** [comment]
but now this problem is ok
