### ISSUE TITLE
Filenames are case sensitive

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/cocoadocs.org#407]
Maya [isn't getting the QI boost](https://cocoapods.org/pods/Moya/quality) for having a changelog, and it looks like it's because [this function](https://github.com/CocoaPods/cocoadocs.org/blob/a9ec353364fc91101ac606b6b13eb962a8d37bcb/classes/readme_generator.rb#L40) does a case-sensitive compare. Since [switching to less scary filenames](https://github.com/Moya/Moya/commit/8a2f3673ee4279f92aed94a4082fbfd9a31bf3f8#diff-9b8fab691c00b9e5380b19ce882f3271), Moya hasn't been getting the boost :fearful: I'm not even 100% sure it's finding the correct read or is using a generated one.

Anyway, wasn't sure at what level to implement a fix, otherwise I'd have sent a PR. If anyone has direction on this, happy to send a change in.

**Comment by segiddins** [comment]
We could easily just downcase the path and the file name.

**Comment by ashfurrow** [comment]
Yeah that's what I was thinking, will send something in :+1:
