### ISSUE TITLE
Jazzy-generated docset doesn't contain a CFBundleName

### ISSUE THREAD

**Issue by Kapeli** [CocoaPods/cocoadocs.org#411]
SwiftDate 2.0.2 (http://cocoadocs.org/docsets/SwiftDate/2.0.2/publish/SwiftDate.tgz) has this in the Info.plist:

```xml
<key>CFBundleIdentifier</key>
<string>com.jazzy.</string>
<key>CFBundleName</key>
<string></string>
```

This causes Dash to display an empty name for this docset.

**Comment by orta** [comment]
looks like problem this is at Jazzy level
