### ISSUE TITLE
Pod page error

### ISSUE THREAD

**Issue by yannickl** [CocoaPods/cocoadocs.org#412]
Hi,

The pod page of my last project produce [error](http://api.cocoadocs.org:4567/error/FlowingMenu/0.2.0) and is not [generated](https://cocoapods.org/?q=flowingmenu).

I updated the pod to v0.2.0 and nothing has changed.

I think the problem is also related to https://github.com/CocoaPods/feeds.cocoapods.org/issues/279.

**Comment by orta** [comment]
So, the error looks like like a bad deploy of CocoaDocs, I've just shipped a new version with some fixes and have set off a re-parse for the last 5 days. Should cover updating this library.

WRT the feeds, it should be getting information directly from GitHub/Trunk - I don't think it relies on the CocoaDocs infrastructure at all, that's mainly so this kind of thing cannot happen :)

**Comment by yannickl** [comment]
Thank you, It works now! :+1: 

That's weird and annoying because the Cocoapods and CremeDeLaPod accounts have a lot of followers and it is a great way to promote the libs. :/

Can be a cosmic particle that's been there at the same time! ;)

**Comment by orta** [comment]
haha, yeah, sorry about that, will get around to that feeds issue soon enough, always hard trying to prioritize these kinda things

**Comment by yannickl** [comment]
Don't worry, I know that open-source projects take a lot of our free time and that's hard to be everywhere in the same time.

Thank you again for your great work! :+1:
