### ISSUE TITLE
Methods with question marks do not work

### ISSUE THREAD

**Issue by tsol-user** [CocoaPods/cocoadocs.org#413]
Trying to go to

http://cocoadocs.org/docsets/BrightFutures/3.2.0/Functions/??(_:_:).html

This is pretty obviously because the question marks aren't encoded, and the URL then turns into a URL fragment after the question mark.

You can see it working with other symbols here:

http://cocoadocs.org/docsets/BrightFutures/3.2.0/Functions/==(_:_:).html

**Comment by orta** [comment]
Thanks for the report!
You should move this to https://github.com/realm/jazzy :+1: - CD sits atom of their infrastructure for this.
