### ISSUE TITLE
Cocoadocs ignoring .jazzy.yml

### ISSUE THREAD

**Issue by pcantrell** [CocoaPods/cocoadocs.org#414]
Jazzy now supports a `.jazzy.yml` file to control document generation, but Cocoadocs.org appears to ignore it.

I noticed this for Siesta’s docs:

http://cocoadocs.org/docsets/Siesta/1.0-beta.5/

Here's how they should look:

http://bustoutsolutions.github.io/siesta/api/Classes/Service.html

(Note custom categories in the left nav and no Objective-C glue code showing up in docs.)

Cocoadocs is using Jazzy 0.4.1, which should support the config file. Not sure why it isn’t working.

**Comment by segiddins** [comment]
We'd have to manually pass the path to the config we create.
