### ISSUE TITLE
Updated pod listed as not documented despite not changing documentation since last version

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/cocoadocs.org#418]
I updated a pod today (https://cocoapods.org/pods/Gloss) - and all of a sudden its listed as not being documented. What's odd is that that documentation hasn't changed since the last version, which was listed as being at 82% (down from 100% from the equally documented version before - not sure why that happened either). any insight on documentation not being generated correctly?

**Comment by orta** [comment]
It's possible that updating to [Jazzy](https://github.com/realm/jazzy) 0.4.1 changed the amount of things that are potentially documentable, we get the doc % directly from a run of Jazzy on the Podspec.

Though looking at the API results, it looks like Jazzy is crashing on [your library](http://metrics.cocoapods.org/api/v1/pods/Gloss) and so we don't take points off, it's not fair to do that when it is out of your and potentially our control.

**Comment by hkellaway** [comment]
do you happen to know if there's a way i can address jazzy crashing on me?

**Comment by orta** [comment]
Well there's three ways
* Check the [API response](http://cocoadocs.org/readme/) for a CocoaDoc error too see if there's anything obvious: ( http://api.cocoadocs.org:4567/error/Gloss/0.6.2 ) - doesn't  seem it though
* you can try running jazzy against your library locally and see what's going on. 
* set up an instance of CocoaDocs to run the preview command: https://github.com/CocoaPods/cocoadocs.org#previewing-my-library-in-cocoadocs

**Comment by hkellaway** [comment]
alright, thanks!

**Comment by orta** [comment]
Fixed by Should be fixed with #422
