### ISSUE TITLE
Documentation not generated for updated pod

### ISSUE THREAD

**Issue by endoze** [CocoaPods/cocoadocs.org#419]
I just pushed a new version of my pod (RosettaStoneKit) yesterday and documentation wasn't generated a few hours after. I checked the API response for my pod's documentation (api.cocoadocs.org:4567/error/RosettaStoneKit/1.2.4) and received an error stating 

/Application/Xcode.app/Contents/Developer does not exist, use xcode-select --switch path/to/Xcode.app to specify the Xcode you wish to use for command line developer tools

I'm assuming this means the machine running cocoadocs isn't set up correctly at this point.

**Comment by orta** [comment]
Yep! this is definitely true, I spotted it today but there's a big CP thing happening today so didn't have time to work on CocoaDocs, should be able to find some time tomorrow

**Comment by endoze** [comment]
Ok great, thank you for all your hard work and contributions. These tools are so invaluable!

**Comment by DiegoArenaOlivera** [comment]
Hi , we are having an issue. We pushed to github and cocoapods yesterday. In cocoapods it is showing the new release that it is 4.7, but it is showing the documentation for the previous release.

Also when we try to open the documentation it give us a page with an error 404.

It is a way to update this? or it is an issue on your side? Thanks.
Issue: https://github.com/CocoaPods/cocoadocs.org/issues/420

**Comment by macteo** [comment]
Occurring to me too. Thanks @orta for your time.

**Comment by endoze** [comment]
Looks like the most recent version of documentation was generated for my cocoapod. Thanks again for all your hard work @orta!

**Comment by orta** [comment]
I set off a long-running process for the last 7 days of docs, so it should slowly appear for most, but not all, there's a jazzy migration bug we've found but not figured out.

**Comment by macteo** [comment]
Appeared for me. Thanks
