### ISSUE TITLE
Documentation not updated for the last release

### ISSUE THREAD

**Issue by DiegoArenaOlivera** [CocoaPods/cocoadocs.org#420]
Hi , we are having an issue. We pushed to github and cocoapods yesterday. In cocoapods it is showing the new release that it is 4.7, but it is showing the documentation for the previous release.

Also when we try to open the documentation it give us a page with an error 404.

It is a way to update this? or it is an issue on your side? Thanks.

**Comment by orta** [comment]
Issue our side, see #418 - turns out I didn't get much time to fix it today though.

**Comment by orta** [comment]
Should be fixed with #422

**Comment by DiegoArenaOlivera** [comment]
Fixed, Thanks
