### ISSUE TITLE
Feature request: "latest" alias in docsets URLs

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/cocoadocs.org#421]
So that we could call http://cocoadocs.org/docsets/XCDYouTubeKit/latest/Classes/XCDYouTubeClient.html for example and it would be a 302 redirect to http://cocoadocs.org/docsets/XCDYouTubeKit/2.4.3/Classes/XCDYouTubeClient.html  given that 2.4.3 is the latest version.

I’d propose a pull request but after looking at the code I still don’t understand how the routing works on cocoadocs.org with sinatra and the docsets uploaded to S3. 😕

**Comment by orta** [comment]
We couldn't do this I think, it's all static docs, perhaps if we posted to both [version number] + [latest] it could do an approximation of that?

**Comment by chrismaddern** [comment]
Hah - just went to go to do this and had a similar issue. Ended up on the same potential solution and wanted to discuss in an issue before implementing.

Definitely would be more useful with this capability.

**Comment by orta** [comment]
I'm 👍  with uploading docs to both the version number and a folder called latest - will put it on my TODO next time I do CD work.

This does mean that if you rename that function/class then the link will be broken though, can't fix that in a reasonable way.
