### ISSUE TITLE
Cocoadocs Quality Metrics do not pick up SPM and Docs

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/cocoadocs.org#427]
Hi,

When I look here https://cocoapods.org/pods/CryptoSwift/quality I'm concerned about 2 metrics:
1. applied "Badly Documented" - this just happened some time ago without any significant change to the project documentation. Changed from Great Documentation to Badly Documented. I'm trying to understand what happened.
2. Missing "Supports Swift Package Manager" while the support is there for 2 versions already.

please let me know if you have any thoughts about that. Thanks in advance.

**Comment by krzyzanowskim** [comment]
Documentation generated locally:

![screen shot 2016-02-03 at 01 58 35](https://cloud.githubusercontent.com/assets/758033/12769653/d092fd10-ca19-11e5-8af2-9f01ccac9a0a.png)

online: http://cocoadocs.org/docsets/CryptoSwift/0.2.2/
![screen shot 2016-02-03 at 02 00 13](https://cloud.githubusercontent.com/assets/758033/12769664/e57005a2-ca19-11e5-8478-51cf16d2f6b2.png)

and yes jazzy reported problems like this:

Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: class AES, class AES, class AES, class AES
Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: enum Error, enum Error, enum Error, enum Error

**Comment by orta** [comment]
> Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: class AES, class AES, class AES, class AES
> Found conflicting type declarations with the same name, which may indicate a build issue or a bug in Jazzy: enum Error, enum Error, enum Error, enum Error

There's an issue for Jazzy about those, @AliSoftware was having the same problem.

The SPM one is worrying though, first time this has been brought up as unreliable.
