### ISSUE TITLE
Apache 2 license doesn't match

### ISSUE THREAD

**Issue by benasher44** [CocoaPods/cocoadocs.org#428]
In https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/spec_extensions.rb, it looks like the following license types would match okay in a podspec:
- 'Apache License, Version 2.0"
- 'Apache 2.0'
- 'Apache2'

In [our repo](http://github.com/Yelp/YLTableView/), we specified 'Apache 2'. This seems a bit more natural than either 'Apache 2.0' or 'Apache2' (this one seems like a typo to me). Can we add 'Apache 2' to the list? Right now, this appears to be the reason why the license is listed on our pod's page as "Custom".

**Comment by orta** [comment]
Yeah, definitely, send a PR adding that ( or change the 2.0 to 2 ) 👍🏾 - I based all of these off a list of licenses + the number of times they came up in CocoaPods a few years back

**Comment by benasher44** [comment]
Okay! I'll get a PR up soon.

**Comment by benasher44** [comment]
There ya go!

**Comment by benasher44** [comment]
@orta now that #429 is in, would we just see the license change from Custom to Apache 2 the next time we `pod trunk push` for our pod here: https://cocoapods.org/pods/YLTableView ?

**Comment by orta** [comment]
Yes, or you can use the redeploy request ( see the README ) to trigger a re-parse for the latest version, which should update

**Comment by benasher44** [comment]
@orta the redeploy request worked. Thanks!
