### ISSUE TITLE
Swift docsets still don't have CFBundleNames

### ISSUE THREAD

**Issue by Kapeli** [CocoaPods/cocoadocs.org#430]
Related to: https://github.com/realm/jazzy/issues/418.

This doesn't seem to be fixed. AlamoFire 3.2.0 was released on the 8th of February and it doesn't have a CFBundleName in its Info.plist: http://cocoadocs.org/docsets/Alamofire/3.2.0/publish/Alamofire.tgz

**Comment by Kapeli** [comment]
@orta Any ETA for this one? :blush:

**Comment by orta** [comment]
Nope, no ETA from me I'm afraid - got a lot of Artsy work on atm

**Comment by orta** [comment]
This is fixed by #439
