### ISSUE TITLE
Doc not generated for keytechkit v0.1.15 after updated

### ISSUE THREAD

**Issue by vvanchesa** [CocoaPods/cocoadocs.org#431]
http://cocoadocs.org/docsets/keytechkit/0.1.15

Got a 404, the "Potential Error Info" button shows no log or anything. 

appledoc works locally
Any help?

**Comment by jzucker2** [comment]
Just had the same thing happen for me:
http://cocoadocs.org/docsets/BeKindRewind/0.9.0

**Comment by orta** [comment]
Have you looked at: http://orta.io/rebase/why-cant-i-expand/ ?

**Comment by jzucker2** [comment]
I tried following those directions. Didn't even get a 404 for my framework for the last two builds that failed to generate documentation. I'd investigate my own issues if I knew how to start. For the record, my Cocoapods page is fine, it's just the docs page that isn't generating

**Comment by orta** [comment]
Hrm, so I took a quick look, http://cocoadocs.org/docsets/BeKindRewind/0.9.0/ doesn't exist but http://cocoadocs.org/docsets/BeKindRewind/0.9.1/ does - wonder what happened with the 0.9.0 version

**Comment by jzucker2** [comment]
There was a timeout when I pushed 0.9.0, maybe that affected this? I'm happy with 0.9.1 existing. The previous version is still pre-release development, so it's not super important. Just seemed like something was off. Thanks so much for the help!

**Comment by orta** [comment]
Github has been having some API issues lately

![screen shot 2016-02-25 at 3 31 10 pm](https://cloud.githubusercontent.com/assets/49038/13333398/d15e11cc-dbd4-11e5-94b7-53a9d90a4b1c.png)

Which can introduce some irregularities in our infrastructure. Could have been that.

**Comment by jzucker2** [comment]
Thanks! Well I have no issues then. Don't keep this open just for my sake. Really appreciate the quick response.

**Comment by vvanchesa** [comment]
For me - I tried the API pages mentioned in http://orta.io/rebase/why-cant-i-expand/  but the API pages will not open and send a "page not found" error. For the previous version 0.1.14 everything works fine. What have I overseen?

**Comment by vvanchesa** [comment]
Now the 0.1.15 Version of the documentation is online. 
In the meantime I have installed the local version of cocoaDocs and generated a preview successfully. so at least i've learned to build and test the docs. 
Thank you. Issue can be closed.
