### ISSUE TITLE
External images in Swift docsets don't work (archives-only)

### ISSUE THREAD

**Issue by Kapeli** [CocoaPods/cocoadocs.org#432]
If you download and extract http://cocoadocs.org/docsets/RAMAnimatedTabBarController/1.2.1/publish/RAMAnimatedTabBarController.tgz and open `Contents/Resources/Documents/index.html` you'll notice that none of the images work.

The images at http://cocoadocs.org/docsets/RAMAnimatedTabBarController/1.2.1/ work, so my guess is that something in the archival process is turning the absolute image links into relative ones which don't exist.

**Comment by segiddins** [comment]
Confirmed that's the issue. Think the issue _might_ be the CocoaDocs stuff is running before jazzy creates the docset, but not certain.
