### ISSUE TITLE
"Expand" option not available for BWWalkthrough 

### ISSUE THREAD

**Issue by ariok** [CocoaPods/cocoadocs.org#433]
Hi! I've released a repo (https://github.com/ariok/BWWalkthrough) on Cocoa Pods. It seems that something goes wrong during docs generation since currently I can see "site", "doc" and "spec" options only when browsing the pod from cocoapods.org.

**Comment by segiddins** [comment]
Please read http://orta.io/rebase/why-cant-i-expand/. Additionally, your docs are available at http://cocoadocs.org/docsets/BWWalkthrough/1.0.1/

**Comment by orta** [comment]
Did you find an answer for this?

**Comment by ariok** [comment]
not really, I closed the issue because now the "expand" action is there ... but without any intervention by me. I thought you guys did something actually :P

**Comment by orta** [comment]
"Magic"

On my phone, replies will be curt.
