### ISSUE TITLE
Docs won't generate for BRCybertron (source sequence is illegal/malformed utf-8)

### ISSUE THREAD

**Issue by msqr** [CocoaPods/cocoadocs.org#434]
Hello, I'm trying to see why docs won't generate for https://github.com/Blue-Rocket/BRCybertron. When I run cocoadocs.org locally, I get the following error:

```
cocoadocs.org/activity/cocoadocs_specs/Specs/BRCybertron/0.1.0/BRCybertron.podspec.json
-------------
source sequence is illegal/malformed utf-8
------
["~/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/multi_json-1.10.1/lib/multi_json/adapters/json_common.rb:21:in `to_json'", 
...
cocoadocs.org/classes/readme_generator.rb:13:in `create_changelog'", "./cocoadocs.rb:409:in `document_spec'", "./cocoadocs.rb:541:in `document_spec_at_path'", "./cocoadocs.rb:270:in `preview'", "./cocoadocs.rb:115:in `initialize'", "./cocoadocs.rb:573:in `new'", "./cocoadocs.rb:573:in `<main>'"]
```

I'm guessing it's parsing the `README.md` file, which does contain some Japanese characters, but I don't see any malformed UTF-8 sequences there as far as I can tell.

Is there some other file causing this error, or any way to resolve this issue?

**Comment by orta** [comment]
Probably related to #522
