### ISSUE TITLE
Doc are not generated for syncano-ios

### ISSUE THREAD

**Issue by jaskooo** [CocoaPods/cocoadocs.org#440]
Hello, 
I don't why, but docs are not generated on cocoadocs.org for **syncano-ios** library.
Locally after `bundle exec ./cocoadocs.rb preview syncano-ios` i got this
```
cocoadocs.org/activity/cocoadocs_specs/Specs/syncano-ios/4.1.1/syncano-ios.podspec.json-------------
undefined method `real_path' for nil:NilClass
------
["/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:89:in `block in get_source_files_for_target'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:88:in `map'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:88:in `get_source_files_for_target'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:27:in `block (2 levels) in testimate'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:26:in `each'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:26:in `reduce'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:26:in `block in testimate'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:16:in `each'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:16:in `reduce'", "/Users/jasiek/Developer/cocoadocs.org/classes/testing_idealist.rb:16:in `testimate'", "./cocoadocs.rb:485:in `document_spec'", "./cocoadocs.rb:541:in `document_spec_at_path'", "./cocoadocs.rb:270:in `preview'", "./cocoadocs.rb:115:in `initialize'", "./cocoadocs.rb:573:in `new'", "./cocoadocs.rb:573:in `<main>'"]
```
but documentation is generated.

Here http://api.cocoadocs.org:4567/error/syncano-ios/latest everything seems to be fine.

Thanks for help in advance

**Comment by lifcio** [comment]
Hey guys,

Would anyone be able to help us? We cannot find the source of the problem by ourselves. I see the other links posted as github issues here (#444 and #442) were fixed, but we're not able to get ours up and running.

**Comment by orta** [comment]
Looks like you're crashing our testing idealist, perhaps you have unconventional build phases in your Xcode project? Looks like this is where it's coming from - https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/testing_idealist.rb#L84

**Comment by orta** [comment]
As I'd rather it generate the cocoapods page correctly, I'm going to catch exceptions and give `-1` as the number of tests in your projects, you're welcome to take a look with your projects to discern why it's crashing though, would love a PR changing whatever causes it.

**Comment by lifcio** [comment]
Ok. We'll take a look at what might have changed between 4.0.8 and 4.0.9 version of our lib, when the docs stopped generating for us. If we find anything, we'll be happy to make a PR. Thanks!
