### ISSUE TITLE
Jazzy not chosen as doc generator for Swift library

### ISSUE THREAD

**Issue by Kacper20** [CocoaPods/cocoadocs.org#441]
Hello,

I'm preparing library to official release and i was trying to make Cocoadocs generate library documentation.
[Link to library](https://github.com/Polidea/RxBluetoothKit) 
When i'm submitting pod version, under cocoadoc address i'm constantly getting message : Pod parsing failed, could not find Objective- files.

To do checks if everything is good on my side I've built it locally as you said in README, using preview option. It looks just right.

I was looking into sources of cocoadocs and for me it looks like appledoc is chosen instead of jazzy while running parsing in cocoadocs server. I've found that your algorithm is just counting number of files and chosing the greater value - but in entire repo i have only couple of .h files. Locally for me it looks just fine, so I'm stuck because i can't debug online version and check how it works. Maybe something is wrong on my side - in this case please point me where should i find issues.

Pod is named `RxBluetoothKit` 

Thank you for your help in advance,

Kacper

**Comment by orta** [comment]
this is likely that Xcode 7.3 isn't installed on the CD server yet, I was hoping to get it done this weekend when there's usually less new Pods activity :+1:

**Comment by Kacper20** [comment]
That sounds great! Thank you very much for quick answer :-)

**Comment by Kacper20** [comment]
Works now, thanks a lot!

**Comment by orta** [comment]
ace
