### ISSUE TITLE
CocoaDocs redirects to older version of docs

### ISSUE THREAD

**Issue by dontgitit** [CocoaPods/cocoadocs.org#449]
Hi,

I'm not sure if this is intentional (or a known bug, kind of relating to #421), but going to http://cocoadocs.org/docsets/IterableSDK/ redirects to http://cocoadocs.org/docsets/IterableSDK/0.1.1/; however that's 1.) not the newest version, and 2.) the "versions" dropdown doesn't include the newest versions (currently, the newest version is 2.0.0)

CocoaPods seems to be picking up the newest version just fine (https://cocoapods.org/pods/IterableSDK)

Is there some way to tell CocoaDocs to redirect to either the latest, or a specific version if no version is provided?

**Comment by orta** [comment]
Mine is redirecting to v2.0.0 - it's likely just caching on your computers (and there's a limitation on our hosting that you can't say "temporary" redirect, but more permanent

**Comment by dontgitit** [comment]
Hmm, confirmed redirecting to newest version in incognito. 

So I guess there's nothing we can do about this?

**Comment by orta** [comment]
Nope, unless you work at Amazon ;)

https://github.com/CocoaPods/cocoadocs.org/issues/112

**Comment by dontgitit** [comment]
Hmm... yeah if there's no trailing `/`, it issues a 302... but it issues a 301 on the page it redirects to (with a trailing `/`) anyways.

I guess that means it's best practice (at least for now) to always link to a specific version of the docset... thanks!
