### ISSUE TITLE
landscape.io badge is displayed on Pod page

### ISSUE THREAD

**Issue by T-Pham** [CocoaPods/cocoadocs.org#451]
Two of my pods have a landscape.io badge in their README.md file.
The cocoapods page for one of them is displaying the badge, while the other one doesn't.
<img width="607" alt="screen shot 2016-06-20 at 1 52 15 pm" src="https://cloud.githubusercontent.com/assets/1930855/16184418/cc976c86-36ee-11e6-974f-47ebd6e00850.png">

My pods are here:
https://cocoapods.org/pods/NoOptionalInterpolation Not displaying
http://cocoapods.org/pods/UITextField-Navigation Displaying

Also, the title of the page is missing the name of the pod. So instead of "UITextField-Navigation on CocoaPods.org", it only says " on CocoaPods.org".

**Comment by orta** [comment]
Cool, I've never heard of https://landscape.io - will remove it from READMEs also - thanks 👍 

and titles are removed if they're the top element, given that the title is literally above it in the page.

**Comment by T-Pham** [comment]
Thanks for your reply @orta.

I just realised that I should have created this issue on CocoaPods/cocoapods.org instead of here, CocoaPods/cocoa**docs**.org. :D

**Comment by orta** [comment]
nah, cocoadocs makes the cocoapods READMEs - you did it in the right place!

**Comment by T-Pham** [comment]
Wow. It's good to know. Thanks!
