### ISSUE TITLE
CocoaDocs cannot run two docs simultaneously if Jazzy is used

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#452]
Was working on Eigen while jazzy was doing it's thing. Was totally deterministically working until I started trying to run tests.

![screen shot 2016-06-21 at 9 57 39 am](https://cloud.githubusercontent.com/assets/49038/16231997/b77f8196-3796-11e6-919d-c270b94f6bc5.png)

This is likely the biggest cause of flakiness in CocoaDocs' documentation generation. I'd love some ideas on how I can do a queuing system without a tonne of external dependencies.

My tests failed too

![screen shot 2016-06-21 at 10 01 20 am](https://cloud.githubusercontent.com/assets/49038/16232083/227ccd28-3797-11e6-824f-ad1de511f33a.png)

**Comment by segiddins** [comment]
@orta does everything run in a clean tmpdir? That would go a long way towards making things robust

**Comment by orta** [comment]
It's mainly about the Xcode parts of the system that's outside of my control alas, it does look like Jazzy uses tmp dirs correctly ( and eigen is obviously in a different path to everything Jazzy does ) and within CocoaDocs everything is scoped per pod+version

**Comment by segiddins** [comment]
Ah. But don't we already have https://github.com/CocoaPods/cocoadocs-queue ?

**Comment by orta** [comment]
that was if we want to move to federated CocoaDocs generation, e.g. multiple machines. I don't want to have more services if I can avoid it.

**Comment by segiddins** [comment]
Ah, I thought we were using it :/

**Comment by orta** [comment]
I dunno what changed, but I've seen 4 docs go by while RealmSwift has been doing it's thing and I've not seen a problem.
