### ISSUE TITLE
Quick receives a ✖️ for documentation, despite extensive Documentation directory

### ISSUE THREAD

**Issue by modocache** [CocoaPods/cocoadocs.org#454]
[The Quick CocoaPod page](https://cocoapods.org/pods/Quick) shows Quick has a poor documentation rating:

![screen shot 2016-06-21 at 10 43 00 am](https://cloud.githubusercontent.com/assets/552921/16233655/0c7d6cde-379d-11e6-9e9e-b751b4774c21.png)

I guess this is because the README is relatively short. However, the README was shortened to **improve** the documentation. Instead, Quick places its extensive documentation in its Documentation directory. The README covers:
- A basic example of using Quick
- A basic example of installing Quick via CocoaPods
- The fact that it is Apache 2 licensed

The Documentation directory covers, in both English, Japanese, and some Chinese:
- Setting Up Tests in Your Xcode Project
- Effective Tests Using XCTest: Arrange, Act, and Assert
- Don't Test Code, Instead Verify Behavior
- Clearer Tests Using Nimble Assertions
- Organized Tests with Quick Examples and Example Groups
- Testing OS X and iOS Applications
- Reducing Test Boilerplate with Shared Assertions
- Configuring How Quick Behaves
- Using Quick in Objective-C
- Installing Quick, via Git submodules, Carthage, CocoaPods, and SwiftPM
- Installing Quick File Templates

These topics used to be covered in the README, which made it incredibly long and daunting. The Quick project split them up to make the documentation more approachable.

Perhaps CocoaPods could pick up on `.md` files that look like documentation that aren't the README? Or follow relative project links in the README to find additional documentation?

**Comment by segiddins** [comment]
That `documentation` is for inline API docs only, if I recall

**Comment by orta** [comment]
Hrm, that's complicated, this is based on API documentation - e.g. did I ensure every class has names etc

**Comment by modocache** [comment]
Hmm, I consider Quick's headers to be fairly well documented. I just searched the number of `public` symbols in Quick's Swift source files using the following:

```
$ git grep "public " -- Sources | wc -l
      82
```

Then I searched for how many of these had a docblock immediately prior:

```
$ git grep --before 1 "public " -- Sources | grep "*/" | wc -l
      59
```

That seems *pretty* good to me, and I think the public Objective-C symbols are in a similar state (although harder to grep for). But I guess CocoaPods wants better than this...?

**Comment by segiddins** [comment]
I think the issue is that cocoadocs is documenting it as an objc pod

**Comment by modocache** [comment]
I'm not sure how that affects its documentation rating, but here are a few data points:

- Quick has seven header files (not including header files that are part of its own test targets).
- One of those header files is the umbrella header. [[1]](https://github.com/Quick/Quick/blob/5fb172bcda04ed72791f7379f011b207a10440c4/Sources/Quick/Quick.h)
- Three of those files document every symbol. [[1]](https://github.com/Quick/Quick/blob/5fb172bcda04ed72791f7379f011b207a10440c4/Sources/Quick/NSString%2BQCKSelectorName.h) [[2]](https://github.com/Quick/Quick/blob/5fb172bcda04ed72791f7379f011b207a10440c4/Sources/Quick/QuickSpec.h) [[3]](https://github.com/Quick/Quick/blob/5fb172bcda04ed72791f7379f011b207a10440c4/Sources/Quick/Configuration/QuickConfiguration.h)
- One documents most symbols. [[1]](https://github.com/Quick/Quick/blob/5fb172bcda04ed72791f7379f011b207a10440c4/Sources/Quick/DSL/QCKDSL.h)
- Two are explicit bridging headers for Swift code, which use `SWIFT_CLASS` and `SWIFT_EXTENSION`. These are undocumented, although technically the Swift interfaces they're bridging are documented. [[1]](https://github.com/Quick/Quick/blob/5fb172bcda04ed72791f7379f011b207a10440c4/Sources/Quick/World.h) [[2]](https://github.com/Quick/Quick/blob/5fb172bcda04ed72791f7379f011b207a10440c4/Sources/Quick/DSL/World%2BDSL.h)

Let me know if there's anything we can do to improve our documentation rating, or to help debug this. Thanks!

**Comment by orta** [comment]
#478 will make this default to Swift now - next update should get better doc ratings from Jazzy

**Comment by orta** [comment]
I've removed the tick entirely due to #508 now 👍
