### ISSUE TITLE
Docs not expandable

### ISSUE THREAD

**Issue by fousa** [CocoaPods/cocoadocs.org#455]
I pushed different version of our `Delirium` pod. And for some reason I am not able to expand the pod, for all our other pods this work.

![screenshot 2016-06-22 08 52 46](https://cloud.githubusercontent.com/assets/45648/16257163/e2c06a12-3856-11e6-854c-71f89f4c4671.png)

Is this a known issue?

**Comment by orta** [comment]
Was likely #452  - I just redeployed and it was fixed
