### ISSUE TITLE
Status of api.cocoadocs.org?

### ISSUE THREAD

**Issue by sxg** [CocoaPods/cocoadocs.org#458]
Hey,  I recently pushed a new version of my library [ForecastIO](https://github.com/sxg/ForecastIO), and it looks like the docs haven't updated for version 2.1.0 (version 2.0.0 docs are still up). I went through the usual steps of pinging the API (api.cocoadocs.org endpoints) for more info, but it seems like the API isn't working. [Here's the endpoint](http://api.cocoadocs.org:4567/error/ForecastIO/2.1.0) I'm trying to GET. This issue doesn't seem to be specific to my pod either.

**Comment by orta** [comment]
Thanks for the poke, hadn't noticed - it's back now 👍
