### ISSUE TITLE
Kakapo is not searchable

### ISSUE THREAD

**Issue by MP0w** [CocoaPods/cocoadocs.org#459]
I can find Kakapo by searching in the homepage, but the docs are there http://cocoadocs.org/docsets/Kakapo/0.1.0/
I thought it was because of pre-release version but today we released 0.1.0

**Comment by orta** [comment]
I triggered a re-build, and it's showing now - http://cocoapods.org/pods/Kakapo 👍 

Not sure what happened there. Should show up in the search index in an hour or so, it takes time for that to discover new libs.

**Comment by MP0w** [comment]
Thank you! FYI now searching for kakapo in Cocoadocs returns 2 duplicates

**Comment by MP0w** [comment]
Seems fine now, ty again
