### ISSUE TITLE
Documentation generated using AppleDoc instead of Jazzy

### ISSUE THREAD

**Issue by svdo** [CocoaPods/cocoadocs.org#460]
I have a pod `SelfSignedCert` for which the documentation is generated incorrectly. In [version 1.0.1](http://cocoadocs.org/docsets/SelfSignedCert/1.0.1/) AppleDoc is used instead of Jazzy. I have no idea why. There is also an error reported in the API: [Unable to find a specification for `SecurityExtensions (~> 1.0)](http://api.cocoadocs.org:4567/error/SelfSignedCert/1.0.1). This is incorrect, that pod does exist.

I already did this:

- Have the documentation regenerated
- Run jazzy myself, manually (no errors, expected output)
- Run cocoadocs locally to see if I got more output (no errors, expected output)

Please note that the documentation for [version 1.0.0](http://cocoadocs.org/docsets/SelfSignedCert/1.0.0/) was correctly generated.

Could it be that something is going wrong with cocoadocs updating its own copy of the cocoapods master repo?

Thanks!

**Comment by orta** [comment]
I don't think your Podspec is set up correctly, it's pulling in a bunch of the Pods directory, and all of Quick/Nimble. 

Given that Quick/Niumble has a lot of objective-c in them, then when CocoaDocs tries to determine the type of project  it is (by looking at the LOC ) then it determines that it is an Obj-C project

**Comment by orta** [comment]
Oh wait, yeah, what is this about?

```
Jazzy failed: [!] Unable to find a specification for `SecurityExtensions (~> 1.0)` depended upon by `SelfSignedCert`
["/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:57:in `resolve'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.7.0/lib/jazzy/podspec_documenter.rb:18:in `block in sourcekitten_output'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/cocoapods-1.0.1/lib/cocoapods/config.rb:41:in `with_changes'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.7.0/lib/jazzy/podspec_documenter.rb:15:in `sourcekitten_output'", "/Users/cocoadocs/.rvm/gems/ruby-2.1.3/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:60:in `build'", "cocoadocs.rb:438:in `document_spec'", "cocoadocs.rb:535:in `document_spec_with_name'", "cocoadocs.rb:154:in `block in doc'", "cocoadocs.rb:147:in `each'", "cocoadocs.rb:147:in `doc'", "cocoadocs.rb:203:in `cocoadocs_doc'", "cocoadocs.rb:163:in `cocoadocs'", "cocoadocs.rb:102:in `initialize'", "cocoadocs.rb:560:in `new'", "cocoadocs.rb:560:in `<main>'"]
```

**Comment by svdo** [comment]
I don't understand how it can pull Quick and Nimble in. How did you come to that conclusion? And again, when I clone cocoadocs and run the generation locally, it works as expected (= uses Jazzy).

Regarding the error, that's the one I referred to in my original report. I don't understand how that can happen. Like I said, the documentation generator works as expected and the Pod itself also works.

**Comment by svdo** [comment]
Just for completeness, `SelfSignedCert.podspec` has these dependencies:

    s.dependency "IDZSwiftCommonCrypto", "~> 0.7"
    s.dependency "SwiftBytes", "~> 0.2"
    s.dependency "SecurityExtensions", "~> 1.0"

`SecurityExtensions.podspec` has these:

    s.dependency "IDZSwiftCommonCrypto", "~> 0.7"

`SwiftBytes.podspec` has no dependencies. `IDZSwiftCommonCrypto` neither.

**Comment by orta** [comment]
Had a think about this, I think the Jazzy dep resolver is using ` ~/.cocoapods/repos/master` whereas CocoaDocs' is using `./activity/Specs` - I can make a spec update the core one too

**Comment by svdo** [comment]
Well done, that fixes it for me, thank you!!

**Comment by orta** [comment]
Awesome 👍
