### ISSUE TITLE
"Expand" option not available for AvatarImageView and ProgressObserver

### ISSUE THREAD

**Issue by ayushn21** [CocoaPods/cocoadocs.org#462]
Hey,

I just published 2 pods in the last week called "AvatarImageView" and "ProgressObserver". The docs for both appear correctly on CocoaDocs but there is no "Expand" option on cocoapods.org. Also the automated tweet for a new pod was not sent out for both libraries.

Lastly I think I've somehow broken search. Please see the screenshot below:
<img width="1185" alt="screen shot 2016-08-13 at 2 47 23 am" src="https://cloud.githubusercontent.com/assets/4924039/17640816/c5a383d8-6100-11e6-8f6f-13ab3f6812e6.png">

I'd appreciate your help with this issue.

Thanks,
Ayush

**Comment by orta** [comment]
Working fine now, likely the Xcode 8 migration 

![screen shot 2016-10-12 at 11 00 25](https://cloud.githubusercontent.com/assets/49038/19305909/18318ed0-906b-11e6-810b-0c58487d920c.png)
