### ISSUE TITLE
Expand option not available for PullToRefreshPaginationManager

### ISSUE THREAD

**Issue by riteshhgupta** [CocoaPods/cocoadocs.org#463]
Hey,

I have published [PullToRefreshPaginationManager](https://cocoapods.org/?q=PullToRefreshPaginationManager) couple of months back and as per [why-cant-i-expand](http://orta.io/rebase/why-cant-i-expand/) blog I don't see any issue with my pod. I'm able to see the [docs](http://cocoadocs.org/docsets/PullToRefreshPaginationManager/0.1/), [metrics](http://metrics.cocoapods.org/api/v1/pods/PullToRefreshPaginationManager), [no-error](http://api.cocoadocs.org:4567/error/PullToRefreshPaginationManager/0.1) etc.

<img width="1209" alt="screenshot 2016-08-19 19 02 51" src="https://cloud.githubusercontent.com/assets/8268122/17811202/127763bc-663f-11e6-824c-771e18ea5f35.png">

I'd appreciate your help with this issue!

Thanks,
Ritesh Gupta

**Comment by orta** [comment]
Not too sure what it is, I re-triggered it and it worked fine - http://cocoapods.org/pods/PullToRefreshPaginationManager - it should appear in search soon enough
