### ISSUE TITLE
Description and documentation have both vanished

### ISSUE THREAD

**Issue by pcantrell** [CocoaPods/cocoadocs.org#464]
Siesta has an extensive description in [its podspec](https://github.com/bustoutsolutions/siesta/blob/master/Siesta.podspec). That description used to show up on the [Cocoapods page](https://cocoapods.org/pods/Siesta/)  — but now it doesn’t.

The library also now has an ✗ for documentation, where it used to have a ✓ (and a high score to boot). It’s a Swift lib, and the [docs _do_ compile with Jazzy](https://bustoutsolutions.github.io/siesta/api/).

Is this a duplicate issue? I think not: #454 and #427 sound similar, but:

- they appear to be about the quality metric, not docs disappearing entirely, and
- neither mentions the description disappearing.

**Comment by orta** [comment]
Thanks for the detailed writeup, I've shipped a fix ( https://github.com/CocoaPods/cocoadocs.org/commit/883651b72c9789b7f0b9ff5b0d718375bd86fd90 ) and re-deployed your docs : https://cocoapods.org/pods/Siesta/

Looks my pretty recent readme changes were causing a crash in a lookup, I've added a nil check which seems to cover everything pretty well. 👍

**Comment by pcantrell** [comment]
Wow, lickety split fast! Thanks.

**Comment by orta** [comment]
Gotta do these kind of thing doc things quickly, easy to end up forgetting and never getting back to it
