### ISSUE TITLE
Cocoapods.org quality index generation time

### ISSUE THREAD

**Issue by DenHeadless** [CocoaPods/cocoadocs.org#465]
Hey! 
I was just wondering, is there a way to track when pod website is generated?
Right now for some cocoapods pod page simply does not show, along with their quality index.

For example, this pod was created 3 days ago: https://github.com/MLSDev/AppRouter. There's no pod quality index or page, however it's documentation is working, which at least means that build was working and jazzy generated docs.

**Comment by orta** [comment]
I wonder if it hit the same crash as #464

**Comment by orta** [comment]
They're usually less than 15m, unless you're shipping many pods at once, Jazzy has to compile all targets on each platform to generate all docs

**Comment by orta** [comment]
Nice logo! Alright, yeah, I think it was #464 - re-deploying just now fixed it - http://cocoapods.org/pods/AppRouter

**Comment by DenHeadless** [comment]
Thank you very much! :rocket: :beer:
