### ISSUE TITLE
Documentation is not generated for Swift 3 open classes and funcs.

### ISSUE THREAD

**Issue by T-Pham** [CocoaPods/cocoadocs.org#466]
It seems like so.
My pod previously had 100% documentation rate. I recently upgraded it to Swift 3 and changed all `public` keyword to `open`. Now the documentation rate is shown as 0%.

New documentation page: http://cocoadocs.org/docsets/RoundedSwitch/2.0.0/
Old documentation page: http://cocoadocs.org/docsets/RoundedSwitch/1.0.3/

**Comment by T-Pham** [comment]
Just found out that the issue has been reported here https://github.com/realm/jazzy/issues/646.

**Comment by orta** [comment]
Yeah, I've not updated CocoaDocs to swift 3, there's another issue about this so I'm going to close this as a dupe - was aiming to do it this weekend.
