### ISSUE TITLE
0% Code Documentation for Swift 3

### ISSUE THREAD

**Issue by luispadron** [CocoaPods/cocoadocs.org#467]
I am getting a bad rating index due to CocoaPods thinking I have no code documentation.
The weird thing is I have ran Jazzy and it gives me 100% code documentation.

I am using Swift 3, and have `.swift-version` file in my repo

[Here](https://github.com/CocoaPods/Specs/blob/master/Specs/UICircularProgressRing/0.9.6/UICircularProgressRing.podspec.json) is my Podspec

[Here](http://cocoadocs.org/docsets/UICircularProgressRing/0.9.6/) is the CocoaDocs for my repo, notice the 0% code documentation 

And finally, [here](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html) is my docs/ folder that Jazzy created for me in my repo, notice 100% code documentation 

I'm new to CocoaPods so I may be doing something wrong, however my last version of the Pod said 50% documentation (which is still wrong) but better than 0%.

**Comment by orta** [comment]
Thanks for the issue, this is known, I plan on adding Xcode 8 support this weekend, and I don't want to keep dupes around https://github.com/CocoaPods/cocoadocs.org/issues/466
