### ISSUE TITLE
Documentation is not generated for Swift 3.0 classes

### ISSUE THREAD

**Issue by daltonclaybrook** [CocoaPods/cocoadocs.org#469]
The Cocoadocs page for the latest release of my pod `TweenController` is missing two classes.

Latest version: http://cocoadocs.org/docsets/TweenController/0.3.0/index.html
Prior version: http://cocoadocs.org/docsets/TweenController/0.2.0/index.html

My best guess is: The prior version was written in Swift 2.2, and declared classes as `public class`, while the latest version is in Swift 3.0, and declares classes as `open class`. Perhaps the 'open' keyword is not being handled correctly.

**Comment by orta** [comment]
This probably needs to go on realm/jazzy - until they support that, we can't on CocoaDocs 👍

**Comment by daltonclaybrook** [comment]
@orta ah, excellent. Thanks for the quick response!
