### ISSUE TITLE
"Expand" option not available for SDWebImage-CircularProgressView

### ISSUE THREAD

**Issue by NikKovV** [CocoaPods/cocoadocs.org#470]
Repo: https://github.com/NikKovV/SDWebImage-CircularProgressView
Cocoapods: https://cocoapods.org/?q=SDWebImage-cir
Cocoadocs: http://cocoadocs.org/docsets/SDWebImage-CircularProgressView/0.1.1/index.html

[Tests](http://orta.io/rebase/why-cant-i-expand/): 
http://api.cocoadocs.org:4567/redeploy/SDWebImage-CircularProgressView/latest
http://api.cocoadocs.org:4567/error/SDWebImage-CircularProgressView/0.1.1
http://metrics.cocoapods.org/api/v1/pods/SDWebImage-CircularProgressView

As i can figure out, that it should work, but doesn't. Help, please.

**Comment by orta** [comment]
Looking good now, likely the Xcode 8 changes
