### ISSUE TITLE
Send pod_version_id

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/cocoadocs.org#471]
Related: https://github.com/CocoaPods/cocoadocs-api/issues/24#issuecomment-247816455

Add `pod_version_id` to the data which is transmitted to the API.

Add here: https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/stats_generator.rb#L33

The API will be updated to accept this data and then disseminate it.

Related but not a blocker: https://github.com/CocoaPods/Humus/issues/17

**Comment by fulldecent** [comment]
Reopen

**Comment by dnkoutso** [comment]
@fulldecent sure, but its been more than a year for this issue, have you tried to fix it?

**Comment by fulldecent** [comment]
Looks like nobody wants this. Closing.
