### ISSUE TITLE
Cocoadocs docset is a bit different than the one generated locally with jazzy

### ISSUE THREAD

**Issue by MP0w** [CocoaPods/cocoadocs.org#472]
ATM the only difference I found is the 99% coverage instead of 100% 🤓
http://cocoadocs.org/docsets/Kakapo/2.0.0/index.html
Locally it is right, any idea why would be different?
http://cocoadocs.org/docsets/Kakapo/1.0.1/index.html was right

**Comment by segiddins** [comment]
Maybe the CocoaPods-generated dummy class?

**Comment by MP0w** [comment]
@segiddins I don't think so, unless something changed recently... because it was correct before
