### ISSUE TITLE
“Use Legacy Swift Language Version” errors

### ISSUE THREAD

**Issue by pcantrell** [CocoaPods/cocoadocs.org#473]
Siesta docs aren’t working: http://cocoadocs.org/docsets/Siesta/1.0-rc.1/#

When I run Cocoadocs on it locally, I get:

```
Looking at Siesta master 

 > Git download
Using config file /Users/paul/work/opensource/cocoadocs.org/activity/download/Siesta/1.0-rc.1/Siesta/.jazzy.yaml
Analyzing dependencies
Fetching podspec for `Siesta` from `/Users/paul/work/opensource/cocoadocs.org/activity/download/Siesta/1.0-rc.1/Siesta`
Downloading dependencies
Installing Alamofire (4.0.1)
Installing Siesta (1.0-rc.1)
Generating Pods project
Pod installation complete! There are 4 dependencies from the Podfile and 2 total pods installed.
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/ct/_03srt6h8xj44m00r6bfmd400000gn/T/xcodebuild-464B7ACC-80D4-4004-837A-0D17C44A3AFE.log
Failed to generate documentation
appledoc version: 2.2.1 (build 1333)
```

…and in the error log it mentions:

```
Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO

=== CLEAN TARGET Siesta-iOS OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET Siesta-iOS OF PROJECT Pods WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by orta** [comment]
Could be that we need to do a Jazzy update, last time I tried to do this https://github.com/CocoaPods/cocoadocs.org/pull/468 I found a rabbit hole, was going to wait till CP and jazzy had stabilised

**Comment by thebluepotato** [comment]
I've extensively tested cocoadocs preview with the latest commit https://github.com/CocoaPods/cocoadocs.org/commit/03e8a58a82687a928c1f47654b5355570fe7ad1b and I've found that this issue arises from the fact that the Pods.xcodeproj generated inside the temp directory does not have a defined `SWIFT_VERSION`.
In `sourcekitten_output` in jazzy/lib/jazzy/podspec_documenter.rb (in your fork : https://github.com/orta/jazzy/blob/rc/lib/jazzy/podspec_documenter.rb#L26), adding "SWIFT_VERSION=3.0" at the end of the `xcodebuild` invocation fixes that and cocoadocs runs flawlessly. However, I really can't understand **why** the Pods.xcodeproj doesn't have that setting already, seeing that only cocoapods 1.1.0.rc3 was used! `pod install` is run inside the same function and some basic printing showed me that `Pod::VERSION` is indeed 1.1.0.rc3. That's my Podfile.lock : 
```
PODS:
  - Alamofire (4.0.1)
  - AlamoFuzi (1.0.2):
    - Alamofire (~> 4.0)
    - Fuzi (~> 1.0)
  - Fuzi (1.0.0)

DEPENDENCIES:
  - AlamoFuzi (from `/Users/jonaszaugg/Documents/Projects/cocoadocs.org/activity/download/AlamoFuzi/1.0.2/AlamoFuzi`)

EXTERNAL SOURCES:
  AlamoFuzi:
    :path: "/Users/jonaszaugg/Documents/Projects/cocoadocs.org/activity/download/AlamoFuzi/1.0.2/AlamoFuzi"

SPEC CHECKSUMS:
  Alamofire: 7682d43245de14874acd142ec137b144aa1dd335
  AlamoFuzi: 86db2bffb02d29c06cb11671d1b812f45d6338f2
  Fuzi: e88177b7cfdf3aa2b828c096c73551232a7f5c72

COCOAPODS: 1.1.0.rc.3
```
I'm at my wits end : I just can't understand why the right version of cocoapods would miss that build setting...
I hope this helps a little...

**Comment by orta** [comment]
Thank @thebluepotato - yeah, without some metadata from a Podspec, we really can't know what version of Swift to use, I think it's safe to move the default in Jazzy to 3.0 FWIW

@jpsim I don't see anything in the README about choosing a Swift version, do you handle that?
@DanToml / @benasher44 - with [this part of the API](https://github.com/orta/jazzy/blob/rc/lib/jazzy/podspec_documenter.rb#L26) can we dictate a swift version externally?

**Comment by jpsim** [comment]
> I don't see anything in the README about choosing a Swift version, do you handle that?

Unfortunately the readme doesn't mention anything regarding that, but [the changelog has some info](https://github.com/realm/jazzy/blame/master/CHANGELOG.md#L109-L123):

> If Swift version is not specified, look for Swift toolchain or clang location
> in the following order:
> 
>   * `$XCODE_DEFAULT_TOOLCHAIN_OVERRIDE`
>   * `$TOOLCHAIN_DIR`
>   * `xcrun -find swift`
>   * `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`
>   * `/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`
>   * `~/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`
>   * `~/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`
> 
> This will be especially useful once jazzy supports generating docs for
> Swift Package Manager modules with a toolchain not tied to an Xcode release.

A `--swift-version` parameter can also be specified.

**Comment by orta** [comment]
👍 I think we'll need to make some changes in the Podspec -> Project generator to take that swift-version into account

**Comment by pcantrell** [comment]
FWIW, there’s code in CocoaPods to inspect `.swift_version` — but it’s only [in the project generator used by `pod try`](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/validator.rb#L250-L263), not in the [generic installed that Jazzy uses](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer.rb).

A few days ago I looked into how one might move it out of validator & into installer, but the internal architecture of CocoaPods is tangled and unfamiliar enough to me that I threw up my hands at it.

**Comment by orta** [comment]
I'm not sure that's gonna work on the long run, as I believe we also allow people to include their own version to the linter via a command-line flag as of RC3, which means we can't use CocoaPods' tooling to force that on the entire ecosystem ;)

**Comment by orta** [comment]
Potentially the JSON that CocoaPods sends up to the Specs repo can contain the derived Swift version, meaning it doesn't need to be inside the podspec API, but could be

**Comment by orta** [comment]
I've started work on this - https://github.com/CocoaPods/cocoapods-trunk/pull/77 ^

**Comment by pcantrell** [comment]
Saw the merge of #77. LMK if and when (and how) you’d like me test the fix for this issue.

**Comment by thebluepotato** [comment]
I've tried with setting both CocoaPods and cocoapods-trunk to master only to remember that of course one would need to "re-trunk" the Pod first to send the Swift version to the JSON podspec... Is it possible to "trunk" the same version again or do we have to make a x.x.1 update of our Pods?

**Comment by orta** [comment]
Not possible, no - it'll require a new release I'm afraid

**Comment by orta** [comment]
and there needs to be work done on CocoaDocs side to support the new attributes too

**Comment by thebluepotato** [comment]
@orta Oh I see! And the need for updates on the CocoaDocs side would have been my second question. Therefore we patiently wait!

**Comment by orta** [comment]
Alright, I've got a version of this that works locally, http://cocoadocs.org/docsets/Siesta/1.0-rc.2/ 

It requires some Jazzy changes, but should be in prod by the weekend

**Comment by pcantrell** [comment]
Awesome. Thanks @orta! Looks like you’ve got it all sorted already, but do let me know if I can be helpful — especially on the jazzy side of things, which I know a bit better than the pod side.

**Comment by orta** [comment]
You can review my PR, should be coming in within the hour

**Comment by orta** [comment]
OK, that should be deployed - I bet if you use the redeploy it'll work too
