### ISSUE TITLE
pod showing up multiple times

### ISSUE THREAD

**Issue by cbernardone** [CocoaPods/cocoadocs.org#474]
Can you please correct. Our pod is showing up multiple times. please search on "jkool" (https://cocoapods.org/?q=jkool). Thank you.

**Comment by orta** [comment]
Well, that proves that https://github.com/CocoaPods/cocoapods.org/pull/289#issuecomment-244786210 doesn't work, anyway - this is the wrong repo ( cocoapods.org vs cocoadocs.org ) - this will fix itself in a few minutes, it's just the search blipping.

**Comment by cbernardone** [comment]
It still has multiple and its been several hours. Only on "Any". "iOS' and "ObjC" appear to be okay. Could you please advise?
