### ISSUE TITLE
No Docs generated for classes end members declared as `open` (Swift 3)

### ISSUE THREAD

**Issue by r-dent** [CocoaPods/cocoadocs.org#477]
I wondered why my pod doesn't generate any documentation. After a bit of research [i found](https://github.com/CocoaPods/cocoadocs.org/issues/476) that it seems to has to do with the new `open` declaration in Swift 3. Comments for open classes and members seem just not to be parsed.

I checked the docs of a few other pods and they seem to have the same issue. In the [docs for Alamofire 4 (Swift 3)](http://cocoadocs.org/docsets/Alamofire/4.0.1/) there are no Docs for any classes. They are all defined `open`. In [the 3.x (Swift 2)](http://cocoadocs.org/docsets/Alamofire/3.0.0/) version they were generated.
I saw the same in [JTAppleCalendar](http://cocoadocs.org/docsets/JTAppleCalendar/6.0.0/) and [my own pod](http://cocoadocs.org/docsets/EliminationMenu/0.2.0/).

**Comment by orta** [comment]
Please send errors like this to https://github.com/realm/jazzy which is the project that does the actual documentation

**Comment by r-dent** [comment]
Hmm.. They seem to have [this](https://github.com/realm/jazzy/issues/646) fixed ([PR](https://github.com/realm/jazzy/pull/647)) in version [0.7.2](https://github.com/realm/jazzy/releases/tag/v0.7.2) already. And locally [it also seem to work](https://github.com/CocoaPods/cocoadocs.org/issues/476).

So i thought the problem is more to search here?

**Comment by orta** [comment]
Then this is likely a dupe of #476 and #473
