### ISSUE TITLE
Problems with relative img links

### ISSUE THREAD

**Issue by jberkel** [CocoaPods/cocoadocs.org#482]
Hi,  there is a problem with relative image urls, screenshots don't show in

http://cocoadocs.org/docsets/SQLite.swift/0.11.0/

from

https://github.com/stephencelis/SQLite.swift

Had a quick look through the issues here and saw that this feature was added a while ago and should just work (#113, #123). Or is there anything else needed in the README?

**Comment by orta** [comment]
Maybe there's problems there when it's inside Jazzy instead of Appledoc?

**Comment by jberkel** [comment]
@orta don't know much about jazzy. i'll see if i can reproduce the problem locally.

**Comment by jberkel** [comment]
Not much luck generating anything locally, has the dir structure changed?

```bash
$ bundle exec ./cocoadocs.rb preview SQLite.swift
Cloning into '/Users/jan/projects/ios/sqlite.swift/cocoadocs.org/activity/cocoadocs_specs'...
Checking out files: 100% (120362/120362), done.
Could not find spec at /Users/jan/projects/ios/sqlite.swift/cocoadocs.org/activity/cocoadocs_specs/Specs/SQLite.swift
$
$ ls activity/cocoadocs_specs/Specs
0                       6                       a
1                       7                       b
2                       8                       c
3                       9                       d
4                       LSDBManager             e
5                       MaterialMotionPopFamily f
$
```
