### ISSUE TITLE
Old documentation for SwiftyZeroMQ latest

### ISSUE THREAD

**Issue by azawawi** [CocoaPods/cocoadocs.org#483]
[SwiftyZeroMQ 1.0.19](http://cocoadocs.org/docsets/SwiftyZeroMQ/1.0.19/) is working correctly while the newer versions namely [1.0.20](http://cocoadocs.org/docsets/SwiftyZeroMQ/1.0.20/) and [1.0.21](http://cocoadocs.org/docsets/SwiftyZeroMQ/1.0.21/) are giving 404 pages.

How can I see the error log of the failing docsets?

**Comment by paulw11** [comment]
I am also seeing missing documentation for updates to [SubscriptionMonitor](https://cocoapods.org/pods/SubscriptionMonitor).  It appears that the documentation process is broken.  http://api.cocoadocs.org:4567/ is not responding

**Comment by orta** [comment]
Ah yeah, looks like the server went down sometime last night, I've brought it back up and started re-parsing the last day's worth of pods. Probably caused https://github.com/CocoaPods/CocoaPods/issues/6175 too.

**Comment by orta** [comment]
There are 252 specs from yesterday - so it may take some time.

**Comment by azawawi** [comment]
Thanks for the update. It is been for like 5 hours and but unfortunately it is still the same. Is it still running?

**Comment by orta** [comment]
it could take all day, imagine compiling 252 projects in LLVM for every target architecture on a Mac Mini

**Comment by azawawi** [comment]
@orta Cool. Thanks :+1:

**Comment by azawawi** [comment]
@orta Any update on this one? What is the pending project count to be compiled so far? Thanks for your time.

**Comment by orta** [comment]
http://cocoadocs.org/docsets/SwiftyZeroMQ/1.0.21/ is done 👍

**Comment by azawawi** [comment]
@orta Big thanks :+1:
