### ISSUE TITLE
New documentation is not being generated

### ISSUE THREAD

**Issue by sivu22** [CocoaPods/cocoadocs.org#485]
I updated [SimpleKeyboard 0.1.2](http://cocoadocs.org/docsets/SimpleKeyboard/0.1.2/) 6 days ago, and no doc was generated since then. Therefore the pod will not expand.

I also get no stats and no errors. Tried multiple times to reparse, still no luck.

Jazzy builds successfully the documentation locally.

Any help would be appreciated.

**Comment by orta** [comment]
Weird, I asked for it to be re-parsed and it seems to work now - not sure what's up there

**Comment by orta** [comment]
http://cocoadocs.org/docsets/SimpleKeyboard/0.1.2/

**Comment by sivu22** [comment]
@orta thanks!
