### ISSUE TITLE
Cococadocs for HockeySDK-Mac 4.1.1 missing

### ISSUE THREAD

**Issue by TroubleMakerBen** [CocoaPods/cocoadocs.org#487]
Hey guys,

we've releases HockeySDK-Mac 4.1.1 about 10 days ago, yet, cocoadocs doesn't show 4.1.1 to be available. In addition, the pod itself (See [CocoaPods](https://cocoapods.org/?q=hockeysdk)) itself show the readme for 4.1.0 although the version (4.1.1) is correct.
I've checked for an error via [your API](http://api.cocoadocs.org:4567/error/HockeySDK-Mac/4.1.1) and triggered a re-parse, which didn't help.
Any idea what caused the issue or what we can do to make 4.1.1 available on Cocoadocs?

Thx for the help guys, I appreciate it.

🖖
Benny

**Comment by orta** [comment]
Interesting, not sure why, but me running the request seems to have worked 👍 , I swear this app just prefers it when _I_ do it. - http://cocoadocs.org/docsets/HockeySDK-Mac/4.1.1/

**Comment by TroubleMakerBen** [comment]
Oh, come on @orta,
It's okay, you can admit that there is a magic button for you somewhere that fixes all the things! ;)
Now, in honest, thanks a lot for this! =)

**Comment by TroubleMakerBen** [comment]
Hey @orta,

We just released new versions of our SDKs and cocoados for our [iOS SDK](http://cocoadocs.org/docsets/HockeySDK/4.1.3/) show the old docs (for 4.1.1) Do you have any idea why that is? HockeySDK-Mac has the same issue, while HockeySDK-tvOS seems to be okay. Really weird.
