### ISSUE TITLE
Please update jazzy to latest

### ISSUE THREAD

**Issue by svdo** [CocoaPods/cocoadocs.org#488]
The maintainers of jazzy have fixed an issue (https://github.com/realm/jazzy/issues/661#issuecomment-263131462) that causes documentation generation for some multi-platform swift3 pods to fail. My pod 'RichString' is one of these.

The jazzy issue was fixed in their commit https://github.com/realm/jazzy/commit/85735045ac22d5beda638929d511d8f32557cde4.

Could you please update jazzy on cocoadocs.org so that documentation generation works again?

Thanks!

**Comment by segiddins** [comment]
Care to file a PR for this? Thanks!

**Comment by svdo** [comment]
I'd be happy to, but I have no idea how CocoaDocs works and what I would have to do I'm afraid. If you could point me towards the things that need to be changed...

**Comment by svdo** [comment]
First hurdle: `bundle exec ./cocoadocs.rb preview RichString` doesn't work.

```
From git://github.com/CocoaPods/Specs
 * branch            master     -> FETCH_HEAD
Could not find spec at /Users/stefan/Documents/Projects/iPhoneProjects/3dparty/cocoadocs.org/activity/cocoadocs_specs/Specs/RichString
```

RichString is not directly under `Specs`, but under `Specs/e/4/7/RichString`...

**Comment by orta** [comment]
looks like `preview` is not using the new API for handling sharded repo

**Comment by orta** [comment]
This is done & deployed
