### ISSUE TITLE
CocoaDocs uses AppleDoc instead of Jazzy for RealmSwift docs

### ISSUE THREAD

**Issue by icanzilb** [CocoaPods/cocoadocs.org#491]
RealmSwift's [CocoaDocs docs](http://cocoadocs.org/docsets/RealmSwift/) shows a lot of classes, categories, constants, etc. from the Objective-C part of the repo. (For example [RLMArray](http://cocoadocs.org/docsets/RealmSwift/2.1.1/Classes/RLMArray.html))

We do specify that the pod includes only the Swift source files in our [Podspec file](https://github.com/realm/realm-cocoa/blob/master/RealmSwift.podspec#L19) but it seems that the rule gets ignored.

I mentioned this to @jpsim and he suggests that CocoaDocs uses wrongfuly AppleDoc instead of Jazzy and that's why the ObjC classes show up instead of the Swift ones. 

If this is something we're missing to do on our side, please let us know. Otherwise, it feels like it's a bug in the machine. 🤖

**Comment by orta** [comment]
We count Obj-C files vs Swift files and use the one that there is the most of, which in your case must be Obj-C - but I thought this was being done based on the podspec, so it does sound like a bug

**Comment by icanzilb** [comment]
We suspect so. Here's the relevant source files line from the Podspec `s.source_files = 'RealmSwift/*.swift'` so it should be 100% Swift files in that pod.

**Comment by segiddins** [comment]
@orta is it possible CocoaDocs stopped running specs `prepare_command`s recently?

**Comment by orta** [comment]
Just did a quick check, this is still broken after #508. Shame.

+ No, I don't think CocoaDocs has made any changes around `prepare_commands`

**Comment by orta** [comment]
OK - when I tested this all locally it failed. 

The fix is https://github.com/CocoaPods/cocoadocs.org/commit/2ca28ad5e5a142ac49769dc184704a8ce5d0a662

Which I've run locally and got a working legit version with Jazzy: http://cocoadocs.org/docsets/RealmSwift/2.7.0/

Going to test it running on the server instead.

**Comment by icanzilb** [comment]
this is fantastic @orta, thanks for looking into this !

**Comment by orta** [comment]
OK - server shipped it correctly - http://cocoadocs.org/docsets/RealmSwift/2.7.0/

**Comment by jpsim** [comment]
Thanks Orta!
