### ISSUE TITLE
MusicTheory 1.0.5 returns a 403 Forbidden

### ISSUE THREAD

**Issue by danielbreves** [CocoaPods/cocoadocs.org#492]
[MusicTheory 1.0.5](http://cocoadocs.org/docsets/MusicTheory/1.0.5) returns a 403 Forbidden, both when requesting docsets as well as attempting a redeploy. There are no errors listed here: http://api.cocoadocs.org:4567/error/MusicTheory/1.0.5.

**Comment by orta** [comment]
This is looking good as of http://cocoadocs.org/docsets/MusicTheory/1.0.6/ - likely fixed by #508
