### ISSUE TITLE
Cocoadocs for HockeySDK not updated

### ISSUE THREAD

**Issue by TroubleMakerBen** [CocoaPods/cocoadocs.org#496]
Hey @orta,

With last year's release of HockeySDK, we're seeing the issue again that [the cocoadocs](http://cocoadocs.org/docsets/HockeySDK) point to the correct version (4.1.3) but contain the docs for 4.1.1. There doesn't seem to be an error for 4.1.3.

Maybe you can do the same magic you did in #487?

Thanks a ton! =)

PS: 4.1.2 had the same issue, maybe we started doing something wrong with 4.1.2?!

**Comment by orta** [comment]
I re-ran this since #508 and every thing seems fine now 👍
