### ISSUE TITLE
RxRealm docs: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by icanzilb** [CocoaPods/cocoadocs.org#497]
RxRealm (and RxRealmDataSources as well) don't have their docs generated, the docs include only the GH Readme: http://cocoadocs.org/docsets/RxRealm/0.4.1/

The TOC displays the following message: "_Error Parsing Pod. Could not find Objective-C Classes._"

This makes me think CocoaDocs uses the wrong doc parser trying to find .h/.m files instead of .swift

I checked if there was an error logged for RxRealm: http://api.cocoadocs.org:4567/error/RxRealm-Swift/0.4.1 and the result is "_Could not find any errors, perhaps CocoaDocs has not ran the processing?_" (Not sure, but I think it means there were no errors?)

Then I tried to redeploy: http://api.cocoadocs.org:4567/redeploy/RxRealm.swift/latest and this errors with "undefined method `map' for nil:NilClass" 

After some searching in Google it looks like this is an error ruby will throw so I'm not sure what can I do more? It seems this is the root of the problem so that's why I've put this error message as the issue title.

Let me know how can help cocoadocs to generate the docs for my pods :)

**Comment by orta** [comment]
I'd recommend running through the preview and taking a look: https://github.com/CocoaPods/cocoadocs.org#previewing-my-library-in-cocoadocs

If Jazzy fails it falls back to Appledoc, so Jazzy could not be working on the lib

**Comment by icanzilb** [comment]
okay, will give that a try, thanks!

**Comment by orta** [comment]
I gave this a re-run since #508 and it's working: http://cocoadocs.org/docsets/RxRealm/0.6.0/

`RxRealm.Swift`isn't a library on CP, which is why it's dying - should really have a nicer message
