### ISSUE TITLE
Docs not generated, README is not available

### ISSUE THREAD

**Issue by Ssimboss** [CocoaPods/cocoadocs.org#499]
Hello,

This is my first experience. I've created a new CocoaPod:
https://github.com/Ssimboss/Image360

All seems to be good, but as I see here:
https://cocoapods.org/pods/Image360

My pod is marked as undocumented, even I have created documentation in source-files with Markdown and put **.swift-version** file to my repository.

Also, I can't see any content on OVERVIEW tab, even I have created a README.md

Any ideas?

Thank you

**Comment by orta** [comment]
Have you deployed since you fixed the README?

**Comment by Ssimboss** [comment]
@orta, at the moment I can't remember exactly the moment when I deployed the last version(0.1.3) of my pod. MB it was when I've already fixed README.

**Comment by Ssimboss** [comment]
@orta I've just updated my project, committed it, pushed to GitHub & pushed pod via trunk. As I see, my problem is still actual.

**Comment by orta** [comment]
Looks like it was hitting some edge cases in the README handlers and crashes on generating docs - this is fixed, and deployed https://cocoapods.org/pods/Image360
