### ISSUE TITLE
My pod "GoogleMobileAdsMediationAdColony" is not expanding in cocoapods search result.

### ISSUE THREAD

**Issue by amadkhilji** [CocoaPods/cocoadocs.org#503]
We have released a new pod "GoogleMobileAdsMediationAdColony". Everything seems to be working ok but the pod itself is neither expanding nor opening the [URL](https://cocoapods.org/pods/GoogleMobileAdsMediationAdColony). In fact it re-directs to our [home page](https://firebase.google.com/docs/admob/ios/mediation).
![screen shot 2017-01-31 at 10 43 50 am](https://cloud.githubusercontent.com/assets/1125063/22479333/39bb7366-e7a2-11e6-869e-946e9627ced5.png)

Google Mobile Ads Mediation Team!

**Comment by orta** [comment]
I've triggered a re-deploy using the instructions from the [new issue template](https://github.com/CocoaPods/cocoadocs.org/blob/master/.github/ISSUE_TEMPLATE.md#are-you-here-to-write-a-my-pod-xxx-isnt-showing), and it's working now 👍
