### ISSUE TITLE
Missing section in generated doc

### ISSUE THREAD

**Issue by jgimenez** [CocoaPods/cocoadocs.org#504]
CocoaDocs takes the `README.md` file and puts it as the entry document of the documentation. I see, however, that strangely a full section of the document is missing.

See http://cocoadocs.org/docsets/BugfenderSDK/1.4.1/index.html and compare against https://github.com/bugfender/BugfenderSDK-iOS/blob/1.4.1/README.md. The whole **Using CocoaPods** section is missing.

Is this a bug or am I missing something?

**Comment by orta** [comment]
We remove CocoaPods sections from the READMEs, the page has information on how to install. More discussion in https://github.com/CocoaPods/cocoadocs.org/issues/401
