### ISSUE TITLE
SkyWite pod expand view not available 

### ISSUE THREAD

**Issue by isamankumara** [CocoaPods/cocoadocs.org#507]
I have added my library call "SkyWite"

Doc Is not full completed 
http://cocoadocs.org/docsets/SkyWite/1.0/index.html

No errors
http://api.cocoadocs.org:4567/error/SkyWite/1.0
http://api.cocoadocs.org:4567/redeploy/SkyWite/latest
http://metrics.cocoapods.org/api/v1/pods/SkyWite

But I can't see any expand view for that

**Comment by orta** [comment]
Did you fix something? I just ran a run of it and it went through fine for 1.3? http://cocoapods.org/pods/SkyWite

**Comment by isamankumara** [comment]
yes that's works 1.3 but document says 100% covered . But not available  http://cocoadocs.org/docsets/SkyWite/1.3/index.html

**Comment by orta** [comment]
For that I'd recommend checking out the Jazzy documentation - maybe you're using private files or not including all the source files inside your podspec.

**Comment by isamankumara** [comment]
One additional thing why I can't see download count and install count?
