### ISSUE TITLE
UBTokenBar Docs have not parsed for days

### ISSUE THREAD

**Issue by maxwellE** [CocoaPods/cocoadocs.org#509]
Hello Cocoapods,

I uploaded a pod about 3 days ago and it still has not had its docs generation run, how much longer do I need to wait? Thanks

Error log: http://api.cocoadocs.org:4567/error/ubtokenbar/1.0.1

**Comment by orta** [comment]
This lib seems to be locking the CocoaDocs process - 

<img width="1370" alt="screen shot 2017-05-20 at 12 51 21" src="https://cloud.githubusercontent.com/assets/49038/26275534/0af3079c-3d5b-11e7-9511-9d3bf51b01b3.png">

**Comment by orta** [comment]
The split in #508 means that the CocoaPods side will still work: http://metrics.cocoapods.org/api/v1/pods/UBTokenBar

**Comment by orta** [comment]
Just checked the site, it's working http://cocoadocs.org/docsets/UBTokenBar/1.0.1/
