### ISSUE TITLE
Pod showing 404 for updated SnapLayout version

### ISSUE THREAD

**Issue by sp71** [CocoaPods/cocoadocs.org#510]
I went to the [error link](http://api.cocoadocs.org:4567/error/SnapLayout/1.2.2) but no luck. I noticed jazzy did work for my [older SnapLayout version](http://cocoadocs.org/docsets/SnapLayout/1.1.0/). I ran `jazzy` within the following directory `SnapLayout/Example/Pods` and it worked perfectly. Unsure what could be causing the issue. Any suggestions/tips would be awesome.

**Comment by orta** [comment]
Fixed by #508  - http://cocoadocs.org/docsets/SnapLayout/1.6.3/
