### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by ababeel** [CocoaPods/cocoadocs.org#512]
cocoapods.org search does not work anymore, whatever I type in the search field, there are no results, the page moves up but shows nothing, only direct links to the pods page are working

tried on Chrome, Safari , Firefox , Android , iOS

in https://status.cocoapods.org/ 
Queries on search.cocoapods.org shows empty bar too

**Comment by ababeel** [comment]
started working right after I finished creating the issue , happened also few days ago

**Comment by zezha-msft** [comment]
Seems that the search is still not working. :cry:

**Comment by ababeel** [comment]
the issue comes back randomly, I hope someone will have a look

**Comment by orta** [comment]
This is a search.cocoapods.org issue - we know about it, and it's being fixed over time.
