### ISSUE TITLE
Docs not expandable

### ISSUE THREAD

**Issue by aceisScope** [CocoaPods/cocoadocs.org#513]
We have this [PaymentHighway](https://cocoapods.org/?q=paymenthighway) published on CocoaPods and the pods works. It's written in Swift 3.0. 
However the cocoadocs are` null` in the metrics so it basically shows a **404** page for the docs. Unfortunately the error url `http://api.cocoadocs.org:4567/error/[Podname]/[Version]` is not working so I couldn't check what's the problem under the hood.
Another issue we have noticed is the "Copy to Clipboard" button gives the following line indicating the version number as `1.0`, though the version number of the library is actually `1.0.5`.
```
pod 'PaymentHighway', '~> 1.0'
```

I did try to use jazzy directly in the project folder and it generates docs successfully.

**Comment by Decybel07** [comment]
I have this same problem with my [L10n-swift](http://cocoapods.org/pods/L10n-swift)

**Comment by aceisScope** [comment]
This issue remains after we updated the framework to `1.0.6`.  :-(

**Comment by orta** [comment]
Copy to clipboard should be `x.y`- not `x.y.z` - so thats 👍 

The lib not working itself is odd, as it's giving issues with Jazzy

```
04:31:22 web.1      | Fetching podspec for `PaymentHighway` from `/Users/cocoadocs/cocoadocs.org/activity/download/PaymentHighway/1.0.6/PaymentHighway`
04:31:22 web.1      | Downloading dependencies
04:31:22 web.1      | Installing Alamofire (4.4.0)
04:31:22 web.1      | Installing CryptoSwift (0.6.9)
04:31:23 web.1      | Installing PaymentHighway (1.0.6)
04:31:23 web.1      | Generating Pods project
04:31:23 web.1      | Skipping User Project Integration
04:31:23 web.1      | Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
04:31:23 web.1      | Running xcodebuild
04:32:14 web.1      | Could not parse compiler arguments from `xcodebuild` output.
```

**Comment by aceisScope** [comment]
@orta  Thanks for the comment.
I also tried running `jazzy` under my root folder and it seems to work fine. 
```
Running xcodebuild
Parsing RequestAdapter.swift (1/11)
Parsing Extensions.swift (2/11)
Parsing Networking.swift (3/11)
Parsing SPHAddCardViewController.swift (4/11)
Parsing Router.swift (5/11)
Parsing SPHFormatter.swift (6/11)
Parsing Crypto.swift (7/11)
Parsing SPHFormLabel.swift (8/11)
Parsing SPHTextField.swift (9/11)
Parsing SecureSigner.swift (10/11)
Parsing SPH.swift (11/11)
34% documentation coverage with 46 undocumented symbols
included 70 public or open symbols
skipped 40 private, fileprivate, or internal symbols (use `--min-acl` to specify a different minimum ACL)
building site
building search index
downloading coverage badge
jam out ♪♫ to your fresh new docs in `docs`
```

**Comment by codeOfRobin** [comment]
I'm having this issue with my pod too - `KayakoMessenger`(0.1.1)  . [Docs](http://cocoadocs.org/docsets/KayakoMessenger/0.1.1) were generated though, but I don't get an 'expand' button

**Comment by ravijain412** [comment]
we are also having the same issue with our cocoa pods docs http://cocoadocs.org/docsets/HyperTrack/0.4.43/. It says "Error Parsing Pod". When I tried running jazzy under my root folder, it worked fine.

**Comment by aceisScope** [comment]
For our case it was automatically fixed somehow. No changes were made from our side, but recently when I checked the docs it's just fine.
