### ISSUE TITLE
CocoaDocs not generated

### ISSUE THREAD

**Issue by tezpark** [CocoaPods/cocoadocs.org#515]
Hello.

I created a brand new Cocoapod, 
    https://github.com/tezpark/TezButton
    https://github.com/tezpark/TezAlertView

All seems good, but yet it doesn't generated documentation on the cocoadocs.

Checking metrics 
    http://metrics.cocoapods.org/api/v1/pods/TezButton 
    http://metrics.cocoapods.org/api/v1/pods/TezAlertView
lists null for cocoadocs

Stats 404: 
    http://cocoadocs.org/docsets/TezButton/0.2/stats.json
    http://cocoadocs.org/docsets/TezAlertView/0.3/stats.json

I did try to regenerate a couple times, but not generated.

And so, on cocoapods.org https://cocoapods.org/?q=tez it just lists "site/docs/spec" and not "expand".

Please check this issues.

Thank you.

**Comment by Decybel07** [comment]
I have this same problem with my [L10n-swift](http://cocoapods.org/pods/L10n-swift)

**Comment by ElizaSapir** [comment]
Hey,

Same problem for me:
https://cocoapods.org/?q=playkit

I get 404 for docs:
http://cocoadocs.org/docsets/PlayKit/0.2.0

Thanks!

**Comment by orta** [comment]
Fixed by #508 

- http://cocoadocs.org/docsets/TezButton/0.2/
- http://cocoadocs.org/docsets/TezAlertView/0.3/
- http://cocoadocs.org/docsets/PlayKit/0.2.1/

**Comment by tezpark** [comment]
I saw resolved.
Thank you for fixing problem!
