### ISSUE TITLE
CococaDocs for FlexibleImage missing.

### ISSUE THREAD

**Issue by Kawoou** [CocoaPods/cocoadocs.org#517]
Hey guys,

I released FlexibleImage to CocoaPods about 12 days ago. However, CocoaDocs has not been generated.
Any idea what caused the issue or what we can do to make 1.5 available on CocoaDocs?

Thx for the help guys, I appreciate it.

🖖
Kawoou

**Comment by orta** [comment]
Fixed by #508 and successfully redeployed - http://cocoadocs.org/docsets/FlexibleImage/1.5/
