### ISSUE TITLE
EmojiOne - not expandable

### ISSUE THREAD

**Issue by ranesr** [CocoaPods/cocoadocs.org#518]
I released a pod for [EmojiOne](https://github.com/ranesr/EmojiOne). But, Site for EmojiOne pod points to GitHub repo. Docs are not expandable when I search for EmojiOne.

**Comment by Decybel07** [comment]
I have this same problem with my [L10n-swift](http://cocoapods.org/pods/L10n-swift)

**Comment by orta** [comment]
Fixed by #30 http://cocoadocs.org/docsets/EmojiOne/1.1.0/
