### ISSUE TITLE
Pod page not generate and expand option not available

### ISSUE THREAD

**Issue by shien7654321** [CocoaPods/cocoadocs.org#520]
I released a pod for [STLimitTextField](https://cocoapods.org/pods/STLimitTextField). But, it don't generate CocoaPods.org page, site for STLimitTextField pod points to GitHub repo. Docs are not expandable when I search for STLimitTextField.
![](http://i4.buimg.com/588926/f55e8dad0e5a5134.png)
I'd appreciate your help with this issue.
Thanks!😃

**Comment by Decybel07** [comment]
I have this same problem with my [L10n-swift](http://cocoapods.org/pods/L10n-swift)

**Comment by Spandana2245** [comment]
I have the same issue.

**Comment by TMTBO** [comment]
The same to me. And i got a message: "Unable to find an Xcode with swift version 3.1."

**Comment by orta** [comment]
Closing as http://cocoadocs.org/docsets/STLimitTextField/0.0.4/ is now good as of #508
