### ISSUE TITLE
total_test_expectations shows 0 on Cocoapods

### ISSUE THREAD

**Issue by pirishd** [CocoaPods/cocoadocs.org#523]
I have created a pod called [InstantMock](https://cocoapods.org/pods/InstantMock).

In that pod, the `total_test_expectations` value shows `0` on Cocoapods: see 
[metrics](https://github.com/CocoaPods/cocoadocs.org/files/1027439/cocoapods.txt) on
http://metrics.cocoapods.org/api/v1/pods/InstantMock. However, the pod has actual tests.

I cloned the cocoadocs project and ran
```
bundle exec ./cocoapods-simple.rb https://raw.githubusercontent.com/CocoaPods/Specs/7c83448fd0aab9f8615a847ef337df2d0d80be3c/Specs/5/7/e/InstantMock/0.2.1/InstantMock.podspec.json
```
Results [here](https://github.com/CocoaPods/cocoadocs.org/files/1027435/cocoadocs.txt) show what seems to be a good value.
```
:total_test_expectations=>271
```
What could be done to have the value updated on CocoaPods?

**Comment by pirishd** [comment]
I think I got the issue. Apparently it comes from the `©` character in the headers added by Xcode when creating a new Swift file, like in the following line:
```
//  Copyright © 2017 pirishd. All rights reserved.
```
Removing this character in all the Swift files of the Test target makes detection work again.

**Comment by orta** [comment]
That seems so arbitrary, I wonder what breaks it

**Comment by nmdias** [comment]
I have this issue as well.  http://metrics.cocoapods.org/api/v1/pods/FeedKit

I have FeedKit seriously tested. However total_test_expectations returns 0. I'm not sure if it's related, but the doc_percent is also null. It should be at 99%.

It was working fine, until I published new releases.

I don't use the © character..

**Comment by skladek** [comment]
To add more detail, it doesn't appear to be an issue with the © character specifically, but with some level of non standard characters. I had a string parsing library that was showing as untested until I removed emoji from my tests. My other projects without odd characters in the tests worked correctly after I removed the © character.

@nmdias Check to make sure you're not using some other special character. I haven't dived in enough to know what sort of encoding Cocoadocs is using so it's hard to say exactly what character that would be, but it may be a place to start.

**Comment by orta** [comment]
Sounds like a quick audit of the test check code to make it use uft8 everywhere would probably fix this

**Comment by nmdias** [comment]
So, I ran `pcregrep --color='auto' -n "[\x80-\xFF]" file.swift` on all my test files and found a few non utf8 characters that were introduced in the most recent commits.

After removing them and updated the pod, metrics now returns `total_test_expectations = 1569`. 

`doc_percent` is still returning `null` however. I have caught some non utf-8 characters in the documentation, maybe I didn't catch them all... Will update later.

**Comment by orta** [comment]
It'd probably be easier for you to try fix CocoaDocs than to ensure that no UTF8 ever ends up in your test suite TBH

**Comment by nmdias** [comment]
Not really, no. As much as I'd like to contribute I wouldn't even know where to start, nor do I know..I wanna say Ruby?

**Comment by segiddins** [comment]
What ruby version is cocoadocs running on the server, @orta ? It's possible newer ruby versions have fixed unicode bugs

**Comment by orta** [comment]
It's possible, it's on 2.1.3, but I don't plan on making any changes to the server infra anymore, probably just somewhere the files aren't being looked at as utf8

**Comment by nmdias** [comment]
I know it's not a definite solution, but if you'd like to look for non utf-8 characters here's a quick solution.

```swift
func searchNonUTF8Characters() {
    
    let allowedCharacters: [Character] = (0..<127).map { (i) -> Character in
        let scalar = UnicodeScalar(i)!
        let character = Character(scalar)
        return character
    }
    
    let path = "/Path/To/Framework/Sources" // or /Path/To/Framework/Tests
    
    FileManager.default
        .enumerator(atPath: path)?
        .forEach({ (entry) in
            let url = URL(fileURLWithPath: path).appendingPathComponent(entry as! String)
            guard let contents = try? String(contentsOf: url) else { return }
            contents.characters.forEach({ (char) in
                if !allowedCharacters.contains(char) {
                    print("char: \(char) in: \(url.lastPathComponent)")
                }
            })
    })
    
}

searchNonUTF8Characters()
```

Throw that in a macOS command line tool app and update the path to your framework.
