### ISSUE TITLE
Pod version in "Installation Guide" is not correct for DJI SDK and UILibrary

### ISSUE THREAD

**Issue by oliverou** [CocoaPods/cocoadocs.org#524]
# Report

## What did you do?

Run `pod trunk push DJI-UILibrary-iOS.podspec` and `pod trunk push DJI-SDK-iOS.podspec` to publish the DJI-UILibrary-iOS and DJI-SDK pods. Here are the successful log messages:

![screen shot 2017-06-06 at 3 39 34 pm](https://cloud.githubusercontent.com/assets/13310805/26820676/39db4532-4ad6-11e7-8dcf-a3e37b566cdb.png)
![screen shot 2017-06-06 at 4 36 12 pm](https://cloud.githubusercontent.com/assets/13310805/26820692/4982cc08-4ad6-11e7-8ab1-a87f356d50bd.png)

## What did you expect to happen?

The pod version in the **Installation Guide** of [DJI UILibrary iOS](https://cocoapods.org/pods/DJI-UILibrary-iOS) and [DJI SDK iOS](https://cocoapods.org/?q=DJI%20SDK) CocoaPods webpages should show the correct latest version **4.1.1**.

## What happened instead?

When you click the **Installation Guide**, it shows **4.1** instead:

![screen shot 2017-06-06 at 4 38 03 pm](https://cloud.githubusercontent.com/assets/13310805/26820793/acd29932-4ad6-11e7-9d51-86324d26e529.png)

![screen shot 2017-06-06 at 4 40 06 pm](https://cloud.githubusercontent.com/assets/13310805/26820839/e093d164-4ad6-11e7-936c-ae1b3a61ba7e.png)

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.6 (15G1510)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ca6abb53f68c3fd8c741527abeb5a2f57a6d1aea
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# platform :ios, '9.0'

target 'UILib Sample' do
  pod 'DJI-SDK-iOS', '~> 4.1.1’
  pod ‘DJI-UILibrary-iOS’, '~> 4.1.1’
end
```

## Project that demonstrates the issue

DJI SDK iOS: <https://cocoapods.org/pods/DJI-SDK-iOS>
DJI UILibrary iOS: <https://cocoapods.org/pods/DJI-UILibrary-iOS>
Github Podspec for iOS SDK: <https://github.com/CocoaPods/Specs/blob/master/Specs/3/a/a/DJI-SDK-iOS/4.1.1/DJI-SDK-iOS.podspec.json>
Github Podspec for UILibrary: <https://github.com/CocoaPods/Specs/tree/master/Specs/DJI-UILibrary-iOS/4.0.1.1.0.0/DJI-UILibrary-iOS.podspec.json>

**Comment by orta** [comment]
This is not a bug, we recommend `x.y` not `x.y.z` because that's does what most people are expecting when using the `~>` operator 👍

**Comment by oliverou** [comment]
@orta , thanks for the quick reply. **x.y.z** is our version format to publish new version of DJI SDK and UILibrary. And I believe it's a common format for other pods too. It would be great if you can help to make it show correctly on the Cocoapods website though, otherwise it may make our developers confused. Thanks a lot! BTW I try to use '4.1.1' in the podfile to install, it works though.

**Comment by orta** [comment]
You can learn how the different operators work here: https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions

I'm happy for the site to continue recommending the `x.y` because it would include all you bug fixes, and you minor patches. Your README is welcome to recommend the patch only version though.
