### ISSUE TITLE
Building the website

### ISSUE THREAD

**Issue by Palleas** [CocoaPods/cocoadocs.org#526]
Hi there - since Buddybuild will be taking over cocoadocs.org, I have a question about the actual website and specifically how you are currently generating it. 

The way I understand it, the website is 100% static HTML and the search queries cocoapods' API?

**Comment by segiddins** [comment]
Nope, the website runs on heroku. Search queries the search API (https://github.com/CocoaPods/search.cocoapods.org)

**Comment by Palleas** [comment]
Are we talking about cocoadocs.org?

**Comment by segiddins** [comment]
Ah, sorry, I read CocoaPods.org. I believe all of cocoadocs.org is statically hosted on AWS.

**Comment by Palleas** [comment]
So basically, this is what I'm doing for the website: 

1- Running `webpages.rb`
2- Sending the content of "activity/website" to S3 in the same bucket at the docsets

Am I missing something?

**Comment by orta** [comment]
Yeah, that sounds about right - there's only one or two pages, so I didn't put much effort into the automation on the index page.

It is what you say - a few files in the same bucket as all the docsets, which I think you manually upload to it 👍

**Comment by Palleas** [comment]
I call this a success and I'm closing this: http://cocoadocs.buddybuild.com/

Thanks for your help!
