### ISSUE TITLE
Searching is down

### ISSUE THREAD

**Issue by codeblooded** [CocoaPods/cocoadocs.org#528]
I went to go check to see if a pod was available, and it appears searching isn't working. I'm getting a strange response. There is no count of available pods or anything... just a blank response:

<img width="1287" alt="screen shot 2017-06-30 at 3 22 08 pm" src="https://user-images.githubusercontent.com/1209285/27752767-54102c80-5da8-11e7-8a93-c572c7f8dfd4.png">

The status site says CocoaPods search is _operational_; however, when I visit search.cocoapods.org, I get a Heroku Application Error...
<img width="513" alt="screen shot 2017-06-30 at 3 26 57 pm" src="https://user-images.githubusercontent.com/1209285/27752858-ba0a40f2-5da8-11e7-83e4-792ff2687060.png">

It also appears as other people are having this issue, too. The metrics on the status site are not showing any queries for the last several hours:
<img width="882" alt="screen shot 2017-06-30 at 3 29 43 pm" src="https://user-images.githubusercontent.com/1209285/27752948-0c1b6510-5da9-11e7-8dc2-fb8dad586a9b.png">

Would love to help; just don't think I can. I don't have access to the heroku project or anything.
Sorry if this is not the right place to post this issue. I've followed the project for a while, but I've never actually contributed.

**Comment by orta** [comment]
Cocoa *Docs* isn't quite the right place, we do have an issue for this on search.cocoapods.org and cocoapods.org https://github.com/CocoaPods/cocoapods.org/issues/322 / https://github.com/CocoaPods/search.cocoapods.org/issues/110

So I'll close this, we want to move to AWS to fix these problems - but that's taking time on our side alas

If that's something you're interested in jamming on, I can get you in the CocoaPods slack and you can work with me + @DanToml on it

**Comment by codeblooded** [comment]
@orta I'd love to help in any way possible :)
