### ISSUE TITLE
No Description page for `FilesProvider`

### ISSUE THREAD

**Issue by amosavian** [CocoaPods/cocoadocs.org#529]
I recently had to rename my pod from `FileProvider` to `FilesProvider`. But I can't get to [description page](https://cocoapods.org/pods/FilesProvider) and it redirects to the [github page](https://github.com/amosavian/FileProvider). The old one is shown.

Btw, is there anyway to transfer download statistics from old one to new one?

**Comment by segiddins** [comment]
> is there anyway to transfer download statistics from old one to new one?

No, but you can deprecate the old one in favor of the new one so the site will help redirect users

**Comment by amosavian** [comment]
I did deprecate in favor of new one. But the new one doesn't have any description page.
[The Old One](https://cocoapods.org/pods/FileProvider)
[The New One](https://cocoapods.org/pods/FilesProvider)

How can I have that description page for the new one?

**Comment by orta** [comment]
Did you go through the advice in the issue template?

**Comment by amosavian** [comment]
I think so. I have [docset for new repo](http://cocoadocs.org/docsets/FilesProvider/0.18.0/). It says [redploy parsing is true](http://api.cocoadocs.org:4567/redeploy/FilesProvider/latest) and it says [no error for latest version](http://api.cocoadocs.org:4567/error/FilesProvider/0.18.0). I have no other idea by myself.

**Comment by amosavian** [comment]
Oh the page is created. Thanks a lot.

**Comment by amosavian** [comment]
Sorry another question @orta . My imageshield badge says documentation percentage is `null%` while it says 90% indes docsets. This is true for both old and new repo.

![badge](https://img.shields.io/cocoapods/metrics/doc-percent/FilesProvider.svg)

**Comment by orta** [comment]
Yeah, that's a property I removed when I split out CocoaPods from CocoaDocs, you should remove the badge 👍

**Comment by amosavian** [comment]
Thanks for your quick answer and of course your patience.

I have another question, probably related to jazzy. Why overrided/derived methods and properties in subclasses doesn't have inherited description from superclass' one? e.g [see this one](http://cocoadocs.org/docsets/FilesProvider/0.18.0/Classes/LocalFileProvider.html#/s:FP13FilesProvider17FileProviderBasic19contentsOfDirectoryFT4pathSS17completionHandlerFTGSaCS_10FileObject_GSqPs5Error___T__T_) while the protocol [has a description](http://cocoadocs.org/docsets/FilesProvider/0.18.0/Protocols/FileProviderBasic.html#/s:FP13FilesProvider17FileProviderBasic19contentsOfDirectoryFT4pathSS17completionHandlerFTGSaCS_10FileObject_GSqPs5Error___T__T_). 

Also methods from Foundation protocols are marked as undoumented [like this one](http://cocoadocs.org/docsets/FilesProvider/0.18.0/Classes/LocalFileProvider.html#/s:FC13FilesProvider17LocalFileProvider4copyFT4withGSqV10ObjectiveC6NSZone__P_).

**Comment by orta** [comment]
That's Jazzy's domain.
