### ISSUE TITLE
Overview is empty on CocoaPods web site

### ISSUE THREAD

**Issue by evgenyneu** [CocoaPods/cocoadocs.org#533]
Hi, the [overview page](https://cocoapods.org/pods/Cosmos) does not show the readme for the Cosmos library version 11.0.3 in all browsers I tried (Chrome, Safari, Firefox). I did `pod trunk push` about 12 hours ago with CocoaPods 1.2.0.beta.1. I did click "re-parse" button recently as well. The Cosmos library version 11.0.3 is available for installation through cocoapods.

CocoaDocs shows 404 error: [http://cocoadocs.org/docsets/Cosmos/11.0.3/](http://cocoadocs.org/docsets/Cosmos/11.0.3/)

The errors page says everything is fine: [http://api.cocoadocs.org:4567/error/Cosmos/11.0.3](http://api.cocoadocs.org:4567/error/Cosmos/11.0.3)

The previous version of the library did show documentation: [http://cocoadocs.org/docsets/Cosmos/10.0.0/](http://cocoadocs.org/docsets/Cosmos/10.0.0/)

Thanks

**Comment by evgenyneu** [comment]
I tried building the documentation locally with `bundle exec ./cocoadocs.rb preview Cosmos` and it worked.

**Comment by omaralbeik** [comment]
We're having the same problem for https://cocoapods.org/pods/SwifterSwift

**Comment by radiofreejohn** [comment]
Not sure how effective this will be if Cocoadocs is down, or broken, but [this](http://cocoadocs.org/readme/) says you can trigger a redeploy/reparse by hitting their API: `http://api.cocoadocs.org:4567/redeploy/[Podname]/[Version]`

**Comment by wuhao5** [comment]
we are having the same problem too: https://cocoapods.org/pods/EarlGrey

**Comment by wuhao5** [comment]
@radiofreejohn Just did what you suggested, not sure if it needs a few minutes to populate but I still could't see any update.

**Comment by tirodkar** [comment]
Also, with EarlGrey, we're not able to see the CHANGELOG changes either. As @evgenyneu mentioned, I didn't see any issues in the error check, but the CocoaDocs link 404'ed for me.

http://cocoadocs.org/docsets/EarlGrey/1.10.1/

Also, the previous version worked fine.

@radiofreejohn don't you need to have an admin key in order to do so?

**Comment by radiofreejohn** [comment]
Given how tied the docs are to Cocoapods, I'm not sure I totally get this, but it sounds like Cocoadocs is deprecated? http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/

https://twitter.com/orta/status/887119733186842624

Don't shoot the messenger.

**Comment by orta** [comment]
Yeah, the CocoaDocs side eventually became not worth the time-tradeoffs for me personally, thus the deprecation announcement back in March when I came to the conclusion that I wasn't interested in handling the next upgrade cycle

I'm definitely interested in why your CocoaPods pages aren't working though, that's a completely separate process running on the same server.

**Comment by radiofreejohn** [comment]
@orta Ah, that makes sense then, for some reason I thought they were coupled.

**Comment by lgauthier** [comment]
I'm having the same blank overview page issue as well. For others' reference, it looks like some issues have been opened for it in the cocoapods.org repo. CocoaPods/cocoapods.org#321

**Comment by Fidetro** [comment]
We're having the same problem : https://cocoapods.org/?q=FFDB

**Comment by mayankk2308** [comment]
Same issue: https://cocoapods.org/pods/MKDataDetector

**Comment by HamzaGhazouani** [comment]
Same issue: https://github.com/HamzaGhazouani/HGPlaceholders

**Comment by patchthecode** [comment]
same issue --> https://cocoapods.org/pods/JTAppleCalendar

**Comment by gk-brown** [comment]
Same here: https://cocoapods.org/pods/HTTPRPC

**Comment by orta** [comment]
Got around to giving this half a day.

Looks like https://github.com/CocoaPods/cocoadocs.org/pull/527 broke uploading README/CHANGELOGs as the `aws` cli had different CLI mechanics around uploading single files vs folders.

I got a few of the projects mentioned working in here to verify the fix in https://github.com/CocoaPods/cocoadocs.org/commit/057304f4810b2607abbea9a66d41839985141ed0, if it's not working on cocoapods.org run through the instructions on how to debug: https://github.com/CocoaPods/cocoadocs.org/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by mayankk2308** [comment]
Well, the error message for **cocoadocs** parsing I get is *Unable to find an Xcode with swift version 3.1.* I did specify that swift version for my repo as I was getting multiple build warnings when **linting** my spec.

**Comment by gk-brown** [comment]
Re-running the docs via http://api.cocoadocs.org:4567/redeploy/[pod]/latest (as described [here](https://github.com/CocoaPods/cocoadocs.org/blob/master/.github/ISSUE_TEMPLATE.md)) resolved the issue for me.

**Comment by HamzaGhazouani** [comment]
Hi @orta it's working after Re-running the docs, but after the update of my pod, I got the same issue 
https://github.com/HamzaGhazouani/HGPlaceholders
