### ISSUE TITLE
Add to dash link gives a 404 error

### ISSUE THREAD

**Issue by ChaoticWyrme** [CocoaPods/cocoadocs.org#535]
The add to Dash link on several, possibly all, docsets is broken. While the link should be 
dash-feed://http://cocoadocs.org/docsets/RainbowSwift/2.0.1/publish/RainbowSwift.xml it is actually 
dash-feed://http://cocoadocs.org/docsets/RainbowSwift/2.0.1/RainbowSwift.xml
The second link gives a 404 error, and as such the link doesn't work.

**Comment by Palleas** [comment]
Hi there - this issue appears to be fixed? It's working for me.

<img width="708" alt="screen shot 2017-09-15 at 5 06 42 pm" src="https://user-images.githubusercontent.com/48797/30489721-48b59d94-9a38-11e7-8d90-32f1a58fef58.png">

Feel free to reopen if I'm missing something!
