### ISSUE TITLE
The FirebaseCommunity pod is redirecting to the homepage

### ISSUE THREAD

**Issue by davidair** [CocoaPods/cocoadocs.org#536]
Navigate to https://cocoapods.org/pods/FirebaseCommunity

Expected: to see the generated page
Actual: redirected to home page at firebase.com

The docs were generated properly here: http://cocoadocs.org/docsets/FirebaseCommunity/0.0.1/

This seems similar to #519

**Comment by paulb777** [comment]
Looks fixed now.
