### ISSUE TITLE
Cocoadocs can't generate doc for private instance of gitlab, Need IP address

### ISSUE THREAD

**Issue by dhirajjadhao** [CocoaPods/cocoadocs.org#537]
Hi
Recently i have created a pod for my organisation "SSOManager" but cocoadocs wasn't getting generated as the repo can't be accessed by it as its being hosted on our private edition of Gitlab and third parties are restricted from accessing. I need IP range of cocoadoc server so that i can whitelist them so that cocoadoc can clone repo and generate docs for the same

**Comment by orta** [comment]
`/cc` @palleas

**Comment by dhirajjadhao** [comment]
@orta @Palleas can i get the update on this please

**Comment by Palleas** [comment]
Hi @dhirajjadhao! We're about to make the switch to buddybuild's infrastructure. Could you had the following CIDR range and let me know once it's done? https://apidocs.buddybuild.com/misc/get-ip_ranges.html

I'll see if I'm able to build the docs then.
