### ISSUE TITLE
Not able to expand my pod

### ISSUE THREAD

**Issue by WilliamDenniss** [CocoaPods/cocoadocs.org#539]
My pod `OpenLocationCodeFramework` isn't expanding. If you click on it from the search results it will open the webpage directly.

## Steps to Reproduce
1. Search "openlocation", i.e. https://cocoapods.org/?q=openlocation

# Expected Results
Able to expand the pod `OpenLocationCodeFramework` (second on list a time of writing).

# Actual Results
No expand link, tapping the title directly opens the web site.

**Comment by idokleinman** [comment]
+1 Same here.
I had a pod called [Spark-SDK](https://cocoapods.org/?q=spark-sdk) which has been deprecated in favor of a new pod called P[article-SDK](https://cocoapods.org/?q=particle-sdk).
The old one has the "Expand" button and a page with download stats while the new one, which is identical in form and function only shows "Docs" and "Site" buttons and does not lead to the page with the download stats.

What is the reason for that and how can it be solved?

**Comment by WirecardMobileServices** [comment]
+1 Our pod SUPRAcceptSDK does not have the Expand button either - it was published on 22/09/2017
Can you check please?
Docs are created http://cocoadocs.org/docsets/SUPRAcceptSDK/2.1.0/
However there is "aria-hidden"=>"true" ... issues with MD files

**Comment by idokleinman** [comment]
Any word on this issue from Cocoapods team?

**Comment by orta** [comment]
I only have so much time i the day I'm afraid, have you gone through the recommendations in the issue tempates?

**Comment by WirecardMobileServices** [comment]
Did the redeploy, checked for metadata and errors yesternight - did not work. 
Just checked now - the Expand button popped in the existence :-)

Re-submit podspec:
http://api.cocoadocs.org:4567/redeploy/SUPRAcceptSDK/latest

Check for errors:
http://api.cocoadocs.org:4567/error/SUPRAcceptSDK/2.1.0

Cocoapods metrics
http://metrics.cocoapods.org/api/v1/pods/SUPRAcceptSDK

Cocoapods home
http://cocoapods.org/pods/SUPRAcceptSDK

**Comment by WilliamDenniss** [comment]
Following @WirecardMobileServices's suggestion (viewed the 4 links substituted with my pod name), and waiting a few hours worked for me. Thanks!

**Comment by jalingo** [comment]
I'm trying these links with my pod name substituted, but they all error out
