### ISSUE TITLE
Pod link redirecting to website.

### ISSUE THREAD

**Issue by SanjithKanagavel** [CocoaPods/cocoadocs.org#541]
I have published SDK two days before. Looks like its visible while you search but its redirecting when you click on search result. And Cocoa Docs is giving 404. 

Tried this http://api.cocoadocs.org:4567/error/FreshchatSDK 
`{"message":"Could not find any errors, perhaps CocoaDocs has not ran the processing?", "trace" :[]}`

and also to redeploy : http://api.cocoadocs.org:4567/redeploy/FreshchatSDK/latest
`{"parsing":true}`

Can anyone please help with this ?

**Comment by SanjithKanagavel** [comment]
Closing this because i moved it here : https://github.com/CocoaPods/cocoapods.org/issues/334

**Comment by SanjithKanagavel** [comment]
Closing this. Since problem got solved. Thanks.

**Comment by SanjithKanagavel** [comment]
I don't know got it fixed by itself. Looks like there was some problem as they were migrating to new infrastructure.

**Comment by jpgupta** [comment]
Getting the same issue with my own pod, I suspect it might just fix itself in a few days but planting a flag here in case others are also experiencing the same thing / maybe I'm doing something wrong with the spec?

https://github.com/MyLabs/ParseArrayHelper
