### ISSUE TITLE
"area-hidden" text is shown in the headers

### ISSUE THREAD

**Issue by evgenyneu** [CocoaPods/cocoadocs.org#542]
There is weird "area-hidden" text added to the headers.

<img width="400" alt="cocoa_docs_area_hidden_in_headers" src="https://user-images.githubusercontent.com/880411/30768763-7570cdfe-a050-11e7-93f6-77aee75a12db.png">

CocoaPods version: 1.3.1
Xcode: 9.0 (9A235)
Swift: 4.0

[http://cocoadocs.org/docsets/Cosmos/12.0.1/index.html](http://cocoadocs.org/docsets/Cosmos/12.0.1/index.html)

[https://cocoapods.org/pods/Cosmos](https://cocoapods.org/pods/Cosmos)

Thanks!

**Comment by pirishd** [comment]
I've got the same issue on my Pod: https://cocoapods.org/pods/instantmock
Same as @evgenyneu: Xcode 9.0 (9A235) and Swift 4

**Comment by orta** [comment]
Looks like the GitHub API for markdown is returning bad HTML:

```sh
~/dev/projects/cocoapods/Strata/cocoadocs.org master ❯ pry

[1] pry(main)> require "octokit"
=> true

[2] pry(main)> Octokit.client_id = 'xxx'
=> "xxx"

[3] pry(main)> Octokit.client_secret = 'yyy'
=> "yyy"

[4] pry(main)> Octokit.markdown("## hello", mode: "markdown", context: "danger/danger")
=> "<h2>\n<a id=\"user-content-hello\" class=\"anchor\" href=\"#hello\" aria-hidden=\"true\"><span>{:\"aria-hidden\"=&gt;\"true\", :class=&gt;\"octicon octicon-link\"}</span></a>hello</h2>\n"

[5] pry(main)> Octokit.markdown("## hello", mode: "gfm", context: "danger/danger")
=> "<h2>hello</h2>"
```

**Comment by orta** [comment]
I think it's fine to switch to GFM, we'd lose some pretty anchors, but they're not exactly an essential feature

**Comment by evgenyneu** [comment]
Thanks for looking at it, people.

> I think it's fine to switch to GFM

Sorry, what does that mean? Do I need to do anything to fix the documentation for my pods?

**Comment by orta** [comment]
You can request a re-deploy (they are statically generated) for the docs, and it should update the READMEs with the new param to the GitHub API

**Comment by evgenyneu** [comment]
Thanks for clarifying @orta. I've requested the redeploy (http://api.cocoadocs.org:4567/redeploy/Cosmos/12.0.1), but it did not fix the headers. Did I do it correctly?

[https://cocoapods.org/pods/Cosmos](https://cocoapods.org/pods/Cosmos)

**Comment by dnkoutso** [comment]
@evgenyneu seems fixed?

**Comment by evgenyneu** [comment]
@dnkoutso, yes, it is fixed now. Thank you!

**Comment by evgenyneu** [comment]
Did anyone do anything special to fix the headers in https://cocoapods.org/pods/Cosmos repository? The reason I ask is because I have several other repositories that have the same problems with headers. I've sent the redeploy requests (http://api.cocoadocs.org:4567/redeploy/bla_bla) a day ago, but the headers are still messy. Thank you.

**Comment by evgenyneu** [comment]
Alright, I found out the answer. I needed to completely redeploy the project to CocoaPods `pod trunk push` to fix the headers in the readme. Thanks.

**Comment by evgenyneu** [comment]
I'm still having the problems with the headers, even after doing the redeploy `pod trunk push`. How can I fix it?

https://cocoapods.org/pods/SigmaSwiftStatistics

CocoaPods version: 1.3.1
Xcode: 9.0 (9A235)
Swift: 4.0

**Comment by pirishd** [comment]
@evgenyneu, I have the same issue on my pod https://cocoapods.org/pods/instantmock.

From what I understand, and this is just my guess (@orta, correct me if wrong), the API responsible for generating the documentation, on address `api.cocoadocs.org:4567` is not responding. Thus, the latest doc for your pod and for mine on http://cocoadocs.org does not correspond to the latest version pushed.

**Comment by orta** [comment]
Yep, looks like the server went down

**Comment by orta** [comment]
OK, I ran the redeploy and that's fixed Cosmos, InstantMock and SigmaSwiftStatistics

**Comment by pirishd** [comment]
Thanks a lot @orta!

**Comment by orta** [comment]
You're welcome, thanks for letting me know
