### ISSUE TITLE
GoogleWebRTC's docs have not updated

### ISSUE THREAD

**Issue by davidair** [CocoaPods/cocoadocs.org#544]
GoogleWebRTC has released 1.1.20011 a day ago, but the documentation page did not get updated (the README.md file has changed, but those changes did not reflect on the landing page).

Navigating to http://cocoadocs.org/docsets/GoogleWebRTC redirects to http://cocoadocs.org/docsets/GoogleWebRTC/1.0.136171/, which is an older version.

Running "bundle exec ./cocoadocs.rb preview GoogleWebRTC" locally on the latest clone of CocoaDocs works and does not report any errors.

**Comment by Palleas** [comment]
Hi there! We're moving cocoadocs.org to a new architecture tomorrow. If the issue persists we'll investigate further.

**Comment by dreese** [comment]
I've had this same issue with https://cocoapods.org/pods/FastSocket

Lastest version is `1.6`, which is correct. But http://cocoadocs.org/docsets/FastSocket redirects to http://cocoadocs.org/docsets/FastSocket/1.4/ which is old.

I verified that the docs parse correct with `jazzy` and `appledoc`. I don't mind that http://cocoadocs.org is out of date, but it would be really nice to have the README on the https://cocoapods.org page be current.

**Comment by orta** [comment]
This should probably be fixed by https://github.com/CocoaPods/trunk.cocoapods.org/pull/235 and https://github.com/CocoaPods/cocoadocs.org/pull/555 - you're welcome to run through the help instructions [in the CocoaPods.org README](https://github.com/CocoaPods/cocoapods.org#getting-help)

**Comment by dreese** [comment]
Working for me. Thanks!
