### ISSUE TITLE
Readme of my pod is not updated

### ISSUE THREAD

**Issue by ChristineXYS** [CocoaPods/cocoadocs.org#560]
My pod is https://cocoapods.org/pods/pointzi. 

The readme of this page still shows 1.1.0, however, my pod has 1.1.2 released. There have been two released's readme not update. 
The source code's repo is https://github.com/StreetHawkSDK/pointzi_ios. Its readme has updated, and not synced to cocoapods' page. 

Would you please check what's going on? Please let me know if anything need my assistance. 

Thanks & regards, 
Christine

**Comment by zacoid55** [comment]
@ChristineXYS it's the same as #556 and #557 - it's been this way for a while it seems

**Comment by orta** [comment]
This is now fixed, I've updated the docs on how to fix these issues yourself too 👍  - #561
