### ISSUE TITLE
Parsing error for Pod README

### ISSUE THREAD

**Issue by zacoid55** [CocoaPods/cocoadocs.org#562]
I tried the `curl http://199.19.84.242:4567/redeploy/[MyPod]/latest` command and got this error:

`{"parsing":false,"error":"undefined method \``map' for nil:NilClass"}`

**Comment by orta** [comment]
did you add your pod name in the command?

**Comment by zacoid55** [comment]
Ah! It was case sensitive - my apologies I'll close this, thank you
