### ISSUE TITLE
Example Screenshot image using relative path does not show

### ISSUE THREAD

**Issue by miller-ms** [CocoaPods/cocoadocs.org#564]
Example image does not show on current trunk push.  It's the same readme as used in the past that worked except now I made some changes to try to correct the problem before posting this issue. 

https://cocoapods.org/pods/MMSProfileImagePicker

**Comment by Palleas** [comment]
Did you check if there was any error in the generation of the documentation?

**Comment by miller-ms** [comment]
It seems there was a problem in generation. I get a 404 error on the documentation page. I requested a reparse.  It didn't seem to help. Not sure what to do. I see that other contributors are having the same problem, so I suspect it's not something I submitted.
