### ISSUE TITLE
The number of stars is not updated 

### ISSUE THREAD

**Issue by HamzaGhazouani** [CocoaPods/cocoadocs.org#565]
In the latest few months the number of stars is not updated

**Comment by Palleas** [comment]
Hi there - do you have an example of a pod in this situation? Thanks!

**Comment by HamzaGhazouani** [comment]
Hi @Palleas, I think all pods have not been updated.
You can check this one for example: https://cocoapods.org/pods/HGCircularSlider
Thanks

**Comment by HamzaGhazouani** [comment]
Hi @Palleas, Any news about this issue ?

**Comment by Palleas** [comment]
Not right now, but there's been some development today that should help moving this migration forward. I'll make sure to update this PR once I have some news.

**Comment by HamzaGhazouani** [comment]
Perfect 👍

**Comment by gk-brown** [comment]
I have noticed this on one of my projects as well:

https://github.com/gk-brown/MarkupKit

The project currently has 444 stars but the pod only shows 433:

https://cocoapods.org/pods/MarkupKit

**Comment by orta** [comment]
This isn't related to CocoaDocs - the stats are grabbed by https://github.com/CocoaPods/metrics.cocoapods.org where they are grabbed every few days. It should always be a little out of date.

**Comment by gk-brown** [comment]
Can we re-open this please? The star count on MarkupKit is more than a little out of date (it has not been updated for a number of weeks).

**Comment by vigneshuvi** [comment]
I have noticed this on one of my projects as well:

https://github.com/vigneshuvi/SwiftCSVExport

The project currently has 33 stars but the pod only shows 26:

https://cocoapods.org/pods/SwiftCSVExport
