### ISSUE TITLE
api.cocodocs.org does not exists.

### ISSUE THREAD

**Issue by anelad** [CocoaPods/cocoadocs.org#568]
API specified in [Cocoadocs Developer Documentation](http://cocoadocs.org/readme/) does not exists.

All GET requests sent to `api.cocoadocs.org` or `api.cocoadocs.org:4567 ` fails.

<img width="715" alt="screen shot 2017-12-15 at 13 22 01" src="https://user-images.githubusercontent.com/5767654/34037912-87e2eb16-e19b-11e7-8866-b356c1b4110a.png">

**Comment by Palleas** [comment]
Hi there - you can use `https://cocoadocs.buddybuild.com` in the mean time. We'll make sure to fix that.

**Comment by futuretap** [comment]
Hm, not sure what a `NoSuchKey` error actually means and if I can fix it at all: https://cocoadocs.buddybuild.com/error/FTLinearActivityIndicator/1.0.2
