### ISSUE TITLE
redeploy times out

### ISSUE THREAD

**Issue by jjochen** [CocoaPods/cocoadocs.org#569]
my pod CHANGELOG/README/Documentation isn't updating at https://cocoapods.org/pods/JJFloatingActionButton

I tried to trigger a redeploy but it fails:

```sh
$ curl http://199.19.84.242:4567/redeploy/JJFloatingActionButton/latest
curl: (7) Failed to connect to 199.19.84.242 port 4567: Operation timed out
```

**Comment by LittleGreenViper** [comment]
This happens to me, as well.

**Comment by LittleGreenViper** [comment]
::thumbsup
Looks like it worked. I'll try the README out shortly.
Thanks!

**Comment by orta** [comment]
No worries - I forgot to note in here, the CocoaPods mac mini had it's IP changed last week ,took this week for it to come back up
