### ISSUE TITLE
Cocoapods.org Flags My VERY EXTENSIVE README as "Minimal"

### ISSUE THREAD

**Issue by LittleGreenViper** [CocoaPods/cocoadocs.org#571]
I have an issue where Cocoapods.org declares my README as "minimal."

[It is NOT "minimal"](https://cocoapods.org/pods/BMLTiOSLib). In fact, it seems to be one of the most extensive README docs I've seen. It gives step-by-step usage and installation instructions.

I assume that the issue is that I am using some flavor of MarkDown that disagrees with Cocoapods, but I changed the MD format, and CP still says that it is "minimal."

What do I need to do to at least stop CP from insulting my README? Add a video tag?

**Comment by orta** [comment]
The QIs are documented in https://guides.cocoapods.org/making/quality-indexes.html - it includes the gem we use for markdown scoring and how we build the QIs on them 👍

**Comment by LittleGreenViper** [comment]
Oh, I get it.

It's because I use inline code (```...```) ALL OVER THE PLACE. I assume that I should be using some other form of markdown for code blocks. I'll try to figure out what I should use.

**Comment by amorde** [comment]
@LittleGreenViper I believe it is looking for some actual code samples, using the same syntax as the inline blocks just with line breaks before and after the ```

For reference here is Github's Markdown syntax: https://guides.github.com/features/mastering-markdown/#syntax

**Comment by LittleGreenViper** [comment]
Got it. I tweaked up the README a bit. I'll bet CP likes it more now.

Thanks!
