### ISSUE TITLE
Cocoadocs Refuses to Parse My Project

### ISSUE THREAD

**Issue by LittleGreenViper** [CocoaPods/cocoadocs.org#572]
For whatever reason, [I always get a 404](http://cocoadocs.org/docsets/BMLTiOSLib).

I've triggered reparse manually numerous times, and banged on the button in the 404 screen a couple of times, to no avail.

The project parses fine in Jazzy. [Here are the Jazzy Docs](https://bmlt.magshare.net/bmlt-doc/07-BMLTiOSLib/index.html).

Is there something I'm doing wrong?

**Comment by jjochen** [comment]
Same for me: http://cocoadocs.org/docsets/JJFloatingActionButton/0.5.0

`jazzy --podspec JJFloatingActionButton.podspec` works fine.

**Comment by acton393** [comment]
There are something wrong with the process of parsing, mine  cannot be parsed until now, as I submit  two days ago.

**Comment by Sorix** [comment]
Mine too, http://cocoadocs.org/docsets/CloudCore/2.0.0/ shows 404, `jazzy` locally is showing awesome documentation.

**Comment by jjochen** [comment]
Any news, anyone?

**Comment by LittleGreenViper** [comment]
Still 404.
It's not a showstopper for me. Happy to help diagnose it, any way I can.
Happy new year, everyone!

**Comment by LittleGreenViper** [comment]
Whoops. This is not closed.

Bad usability. Buttons too close together, and no confirmation.

**Comment by jjochen** [comment]
Is this a duplicate of #556 or #547?

**Comment by LittleGreenViper** [comment]
It may be related, but it still happens. Might be the same as #556. Probably not exactly the same as #547.

**Comment by jjochen** [comment]
http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/

**Comment by LittleGreenViper** [comment]
Cool. I can close this, then. As I said, it's not something I rely on. I have my own Jazzy docs.

Thanks for everything. This is a great service.

**Comment by jjochen** [comment]
You can set the link to your docs in the podspecs:
`spec.documentation_url = 'http://www.example.com/docs.html'`
