### ISSUE TITLE
My project iToolbar is doesn't found

### ISSUE THREAD

**Issue by ericpinet** [CocoaPods/cocoadocs.org#574]
When I try pod install for my iToolbar I have this issue:

[!] Unable to find a specification for `iToolbar`

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this.  This repo is for the website.
