### ISSUE TITLE
Github stats do not update after reparse or trunk push

### ISSUE THREAD

**Issue by amichnia** [CocoaPods/cocoadocs.org#575]
For some time now (at least couple last releases of library), github stats do not updated on cocoa pods.org page after trunk push. Manually triggering re-parse did not solve the problem (it updated readme, version and changelog only)

Link to project:
[https://cocoapods.org/pods/SwiftyMocky](https://cocoapods.org/pods/SwiftyMocky)

**Comment by yacir** [comment]
I have the same issue with the [CollectionViewSlantedLayout](https://cocoapods.org/pods/CollectionViewSlantedLayout).

**Comment by benhurott** [comment]
+1

**Comment by jjochen** [comment]
That’s because of https://github.com/CocoaPods/metrics.cocoapods.org/issues/45
But nothing is happening there :-(

**Comment by orta** [comment]
Good point, we should close this issue.
