### ISSUE TITLE
[Question] My pod redirect to github page, and docs are not available 

### ISSUE THREAD

**Issue by Berk-Kaya** [CocoaPods/cocoadocs.org#577]
Hello, I have published C2Alert but CocoaPods redirect me to its github page, and when I click docs it gives me 404 error. Any ideas?

**Comment by orta** [comment]
Did you run through the recommendations in the issue template?

**Comment by rvi** [comment]
Same here: http://cocoadocs.org/docsets/ONVIFCamera/

**Comment by Berk-Kaya** [comment]
Yes I have made all of the recommendations on issue template.

**Comment by Berk-Kaya** [comment]
curl http://207.254.41.223:4567/redeploy/C2Alert/latest  -> Timed out
http://cocoadocs.org/docsets/C2Alert -> 404
http://api.cocoadocs.org:4567/error/C2Alert/0.1.0 -> Not responding

**Comment by Berk-Kaya** [comment]
Not sure how, but its fixed.
