### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoadocs.org#67]
### How it should work for people who aren't me:

`gem install cocoadocs`
`cocoadocs install` -> Uses Podfile to generate documentation for all mentioned pod files. Will put in Xcode folders which still work in XCode5. There should be options to set different folders.

### How CocoaDocs _should_ for CocoaDocs.org:

Server is separate from cocoadocs, it just queues up the commands that are basically  `cocoadocs doc ARAnalytics 2.1.2 --s3-folder cocoadocs.org`

The cocoadocs.org homepage should be taken out into the server.

I won't be coming back to CocoaDocs till after the cocoapods.org work has finished, so this is a long time coming if it's me.

/cc @kylef

**Comment by segiddins** [comment]
@orta since jazzy exists now, and this issue hasn't really been touched in a while, can we close?

**Comment by orta** [comment]
Yep
