### ISSUE TITLE
Unable to add specific doc version to Dash (AFNetworking 1.3.3)

### ISSUE THREAD

**Issue by djbriane** [CocoaPods/cocoadocs.org#68]
I'm trying to add the docs for AFNetworking 1.3.3 to Dash via the handy link you provide (which is awesome btw). However, this is always pulling the 2.0.0 docset which is significantly different than 1.3.3. I've tried a few ways to get at the older docset without any luck, such as:

http://cocoadocs.org/docsets/AFNetworking/1.3.3/AFNetworking.xml 

Is there a way to do this I'm not seeing (my alternative is to generate the docset myself but wanted to ask before I go through the trouble).

Thanks!

**Comment by adamziel** [comment]
@Kapeli So is it possible to have documentation for e.g. 5 different versions of NodeJS?

**Comment by Kapeli** [comment]
This issue is really old. Dash now supports multiple versions in Preferences > Downloads. You can install as many as you want.

![screen shot 2016-03-23 at 00 38 32](https://cloud.githubusercontent.com/assets/1445635/13970127/97a3d280-f08f-11e5-98ca-3c25c3bd16ed.png)

**Comment by adamziel** [comment]
Ah I didn't notice - this is awesome! Thanks!
